### ISSUE TITLE
Howto add subtitles

### ISSUE THREAD

**Issue by notDavid** [donmelton/video_transcoding#103]
Hi, i'm probably just too tired to see what i'm doing wrong... could you advise why this isn't working?

```
transcode-video --subtitle "1,2" --mp4 --preset slow --handbrake-option optimize 1.mkv
/usr/local/bin/transcode-video: invalid option: --subtitle
Try `/usr/local/bin/transcode-video --help` for more information.

transcode-video -s 1 --mp4 --preset slow --handbrake-option optimize 1.mkv
/usr/local/bin/transcode-video: ambiguous option: -s
Try `/usr/local/bin/transcode-video --help` for more information.

$ transcode-video --version
transcode-video 0.12.2
Copyright (c) 2013-2016 Don Melton
```

( i would like to add subtitles 1 and 2...)

**Comment by donmelton** [comment]
@notDavid This is the right place to ask, tired or not! :) Thanks for opening this issue.

To add both of your subtitles, do something like this:

```
transcode-video --add-subtitle 1 --add-subtitle 2 "/path/to/Movie.mkv"
```

The `transcode-video` tool doesn't have options called `--subtitle` or `-s`. To find out which options are available, use the builtin help like this:

```
transcode-video --help
```

To find out more about subtitles, check out the "Understanding subtitles" section of the "README" document:

https://github.com/donmelton/video_transcoding#understanding-subtitles

I hope that helps.

**Comment by notDavid** [comment]
great thanks for the quick response :)

- i was looking at the subtitle commands of `HandBrakeCLI --help` instead of `transcode-video --help`... that's why i tried the -s and --subtitle

\o/
