### ISSUE TITLE
Yet more Windows instructions 

### ISSUE THREAD

**Issue by samhutchins** [donmelton/video_transcoding#115]
As an alternative to complicated things like Cygwin, the Linux subsystem for Windows, and Docker I've written a short guide on installing these tools natively on Windows:

https://gist.github.com/samhutchins/3b06c3af60f5849ab825a6e5926efdc3

It's pretty straightforward, add a folder to your PATH then download a bunch of .exe's into it, then install Ruby and `gem install video_transcoding`. I've just updated it to match the requirements as of 0.15.0

**Comment by donmelton** [comment]
@samhutchins Thanks! I can probably work this into the next release. Are you going to keep these instructions up to date?

**Comment by samhutchins** [comment]
@donmelton For as long as I'm following your project, yeah

**Comment by donmelton** [comment]
@samhutchins And that might be for awhile, I hope. :)

OK, some questions and comments...

You specifically list RubyInstaller 2.2.6 but looking at the download page, Ruby is already up to version 2.3.3 on that page. And I'm running version 2.4.0 on my Mac. Is it better to have the older version? Seriously, I have no idea on Windows.

Also, you might want to point out that download page for FFmpeg binaries is actually the "official" page and not some random website.

**Comment by samhutchins** [comment]
@donmelton I say Ruby 2.2.6 because it's what the right side of the page recommends and I know very little about Ruby. If the rest of the world has moved on, I'll bump the version

I'll add the note about ffmpeg. The only random website is the download for mp4v2, and it bugs me that that's the case. I had a brief look into it today and it looks like you only use it for naming audio tracks in transcode-video and setting an enabled flag in convert-video. Is there any way for another tool (like ffmpeg) to twiddle that metadata?

**Comment by donmelton** [comment]
@samhutchins OK, that makes sense for Ruby. And the added note for FFmpeg looks good. Thanks.

I'm sorry, but we're stuck with MP4v2. It's the only tool which can reliably detect and set certain attributes on MP4 files. At least the site you're pointing to is a link off of doom9.org.

**Comment by samhutchins** [comment]
@donmelton Ah well. And yeah, doom9 is better than nothing. I with the builds on the mp4v2 google code page worked, I've no idea why they don't though :-(

**Comment by JMoVS** [comment]
I up this. This should become the guide on how to get it running on windows for now. Maybe, if at some point linux subsystem gets better, it may be more wise but not currently. So put my gist on the backburner (or mention it for the adventourous who want to be able to auto-update), but not as go-to.

**Comment by donmelton** [comment]
@JMoVS Agreed! But I want to include all these instructions as options. That'll make the "Installation" section rather wordy but for Windows it may be necessary.

**Comment by JMoVS** [comment]
What do you mean by "include all these instrucions as options"?

**Comment by donmelton** [comment]
@JMoVS Oh, sorry. That was poorly worded, wasn't it? :)

Not options on the command line. I meant I'll probably expand the "Installation" section in the "README" document to include "options" more carefully labeled, possibly with bullet points, for dealing with Windows. And I'll probably list the Cygwin scenario second or third now.

**Comment by JMoVS** [comment]
Just a little bit unclear. ;-)

An installation section layout out the different options sounds good!

To be honest, I never knew how to get started with Cygwin - is there any Gist as to how to get it working?

Also, hurray for homebrew just working on Mac OS :D

**Comment by donmelton** [comment]
@JMoVS I've done it on Cygwin. Once! But I never wrote up detailed instructions anywhere.

That last time I installed on Windows, I used what are essentially @samhutchins 's steps here. Thank god he wrote them down for everyone else! :)

**Comment by JMoVS** [comment]
Well then, as @samhutchins doesn't require cygwin and it doesn't provide any real benefit (that I would recognize), why not drop it?

**Comment by donmelton** [comment]
@JMoVS Hmmmm, I will strongly consider that.

**Comment by JMoVS** [comment]
_Don Melton on the **less is more** trip_ :D

**Comment by JMoVS** [comment]
Ok, I've created a repo and put my installing guide into it. Thereby, people can post issues, submit PR's and get notifications. From now on, the readme is here:
[Installing video_transcoding on lxss](https://github.com/JMoVS/installing_video_transcoding_on_lxss/blob/master/README.md)

**Comment by donmelton** [comment]
@JMoVS Sweet! OK, I'll change the link in the README soon then.

**Comment by JMoVS** [comment]
@donmelton What do you think of:

@samhutchins and me working in this repo (I'd mark him as repo maintainer) and we'd have two installation guides in the repo and a top level overview readme outlining the (currently) two different ways?

Thereby, you could link to the repo and issues related to his method as well as mine can be properly addressed.

**Comment by donmelton** [comment]
@JMoVS That's a GREAT idea! If @samhutchins is up for that. Let me know what you decide.

**Comment by samhutchins** [comment]
@JMoVS sure

**Comment by JMoVS** [comment]
Ok, repo is here: https://github.com/JMoVS/installing_video_transcoding_on_windows

I've invited @samhutchins as collaborator.

**Comment by donmelton** [comment]
@JMoVS Excellent! I'm watching it now. :)

And I'll include a draft of the "Installation" section here as soon as I write it so both you and @samhutchins can review it.

**Comment by JMoVS** [comment]
@donmelton I just accepted the rewording and the pull request. I think it's now in a solid state to be linked. Thank you and @samhutchins for the contribution and feedback!

https://github.com/JMoVS/installing_video_transcoding_on_windows

**Comment by donmelton** [comment]
@JMoVS and @samhutchins OK, how does this read as replacement text in my "README" document:

> On Windows, it's best to follow one of the two methods, manually installing binaries or installing into the [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux), as described here:
>
> <https://github.com/JMoVS/installing_video_transcoding_on_windows>

I want to make it short and sweet. And, as you might have noticed, any mention of the VideoHelp and Cygwin sites are gone.

**Comment by samhutchins** [comment]
Look good

**Comment by JMoVS** [comment]
good to go

**Comment by donmelton** [comment]
@JMoVS and @samhutchins OK, the change is live! Thanks for all your fine work!
