### ISSUE TITLE
gem install fails

### ISSUE THREAD

**Issue by JMoVS** [donmelton/video_transcoding#116]
Hi,

I don't know why it fails but this looks dubious to me:

```
justin:~$ sudo gem install video_transcoding
[sudo] password for justin:
Fetching: video_transcoding-0.15.0.gem (100%)
ERROR:  Error installing video_transcoding:
        video_transcoding requires Ruby version >= 2.0.
justin:~$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux-gnu]
```

**Comment by donmelton** [comment]
@JMoVS Seeing as how I have exactly the same version of Ruby on macOS and it installs fine, I suspect there's something wrong with your RubyGems setup on Linux.

Can you try re-intalling Ruby and RubyGems?

**Comment by JMoVS** [comment]
well, it just so happens that I made a fresh windows 10 copy today to finally get my gist to really work (https://github.com/donmelton/video_transcoding/issues/115 @samhutchins may be able to confirm this). So yes, this is some artefact on my old machine. The fresh one doesn't show this behavior.

**Comment by donmelton** [comment]
@JMoVS Thanks for bringing it to my attention. I suspect the artifact was some old or partially updated version of RubyGems. Let me know if you ever see this again.
