### ISSUE TITLE
Gem update from 0.14 to 0.15 acts on /usr/bin/convert-video - "operation not permitted"

### ISSUE THREAD

**Issue by rhapsodians** [donmelton/video_transcoding#117]
Hi Don,

Not sure if this is a bug but shouldn't convert-video live in /usr/local/bin instead of /usr/bin?
I'm getting errors on updating and installing (see below):

```
MacBook-Pro:bin joe$ sudo gem update video_transcoding
Updating installed gems
Updating video_transcoding
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/convert-video
```

Happy to work around it if it's my set-up by enabling root and giving my default user rwx access but it may throw others not savvy with the permissioning/security around /usr/bin and /usr/local/bin

Thanks,
Joe

**Comment by rhapsodians** [comment]
Extra note:   it also fails to update when run as root. [running latest Sierra 10.12.2]

```
sh-3.2# whoami
root
sh-3.2# gem update video_transcoding
Updating installed gems
Updating video_transcoding
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/convert-video
sh-3.2# 
```

**Comment by donmelton** [comment]
@rhapsodians You should never have to use `sudo` when you `gem install` if you have Homebrew installed. Because you used `sudo`, the problem you have now is that your Gems are in installed in multiple places. Try uninstalling `video_transcoding` as root with `sudo gem uninstall video_transcoding`.

**Comment by rhapsodians** [comment]
I've double-checked and everything for used by video_transcoding is in `/usr/local/bin` as actual ruby scripts or auto-sym-linked back one directory (`../Cellar/`) as installed by Homebrew. HandbrakeCLI is a manual install as I store multiple versions in /usr/local/bin and just symlink the version back to `HandbrakeCLI`.

Let me uninstall as root and try again ... I'll let you know if that resolves it.
Thanks.

**Comment by donmelton** [comment]
@rhapsodians BTW, it's always best to `brew install ruby` instead of using the version of Ruby built into macOS. That way your Gems are always installed in `/usr/local/bin` as long as you don't use `sudo`. New versions of Homebrew no longer include Ruby by default so you have to explicitly install it.

**Comment by rhapsodians** [comment]
and I think that's part of the problem/solution - I'm using the default ruby in macOS. Just (re)installing it now.

**Comment by donmelton** [comment]
@rhapsodians I should probably add something to the "README" document to recommend doing `brew install ruby` now. It's not actually required but things work a lot smoother that way. :)

**Comment by samhutchins** [comment]
FWIW you can also put `export GEM_HOME=~/.gem` in `~/.bash_profile`.

**Comment by rhapsodians** [comment]
It's not my day ... bad news is that it [`brew install ruby`] failed to install properly as one of the files `readline-6.3.8.diff` gives me a file not found (404) error.

**Comment by donmelton** [comment]
@samhutchins Oh yeah, I forgot about that trick! Thanks. But recommending to users that they edit their `~/.bash_profile` worries me. :)

@rhapsodians Ouch! Hopefully your whole Homebrew won't need to be reinstalled. It's actually not that hard to do, but it is a bit of a pain.

**Comment by rhapsodians** [comment]
I think I'll have to endure the pain cleaning it up and doing it all again ... but it will have to wait until later when I get a chance. Some of us still have to work for a living! ;-)

**Comment by rhapsodians** [comment]
Hi Don,

I think you can close this now as it was my installation. A full deletion of Homebrew + installed items followed by a full reinstall of all the video_transcoding items worked fine (including the latest ruby (`ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`)

Now gem update video_transcoding works without sudo but I did have to force the system to pick-up the newly installed ruby instead of the macOS default by `brew link --overwrite ruby`. Other than that, I'm off to play with some subtitles and the new v0.15.

Thanks for the help.

**Comment by donmelton** [comment]
@rhapsodians I'm glad that all worked out!
