### ISSUE TITLE
question about audio options

### ISSUE THREAD

**Issue by platonium** [donmelton/video_transcoding#119]
Hi, with all the recent changes, was wondering if someone could help me with the following options that I'm using with the transcode-video command.  I would like to get English, Chinese and Japanese audio tracks in whatever form they appear in originally.  Is the following what I still should be using?

Thank you again to Don and the community for doing all this work and letting me draft behind. :)

--add-audio eng,zho,jpn --copy-audio all

**Comment by donmelton** [comment]
@platonium Yes, that's exactly the two options you should be using to get English, Chinese and Japanese audio tracks in whatever form they appear in originally.

And you are very welcome, sir!

Any other questions?

**Comment by platonium** [comment]
That is it thank you again.
