### ISSUE TITLE
Perry Mason TV series

### ISSUE THREAD

**Issue by Bob-Collins** [donmelton/video_transcoding#125]
When I use transcode-video to transcode the Perry Mason TV series to use in Plex, I have noticed that the "pans", etc., or large amounts of movement are choppy and stepped instead of smooth and flowing.  What am I doing wrong?  

The command I used was:
transcode-video --crop 0:0:0:0 "C:\in\Perry Mason\Season 01\Perry Mason - s01e02 - The Case of the Sleepwalker's Niece.mkv"

Everything else that I have watched appears to be fine and doesn't exhibit this issue.  

Please help!

**Comment by donmelton** [comment]
@Bob-Collins Thanks for filing an issue. Can I assume this episode of "Perry Mason" has been ripped from a DVD and not a Blu-ray Disc?

Because if your source is a DVD then it's likely the video is interlaced or contains combing artifacts due to poor mastering of that disc. You can try applying a filter to correct that.

I would first recommend you try "detelecine" and force the original frame rate, if you know what that rate is. Possibly something like this:

```
transcode-video --filter detelecine --force-rate 23.976 "/path/to/Movie.mkv"
```

If that doesn't improve things then I would try "decomb" like this:

```
transcode-video --filter decomb "/path/to/Movie.mkv"
```

I hope that helps.

BTW, there's no need to use `--crop 0:0:0:0` since `transcode-video` does not crop by default.

**Comment by Bob-Collins** [comment]
Thanks, I had tried the force of the frame rate and detelecine before I got your reply, and it looks like those worked.  Yes, it is a rip from DVD to a single MKV file.

Again, to anyone ripping the old Perry Mason series from DVD, you will want to use the "--filter detelecine --force-rate 23.976" options, from I can tell in preliminary tests.

Thanks!

**Comment by donmelton** [comment]
@Bob-Collins Wow! You are now officially an expert user for figuring that out on your own. And I hope you continue to help others around here. That's awesome!

And I'll consider adding that `--filter detelecine --force-rate 23.976` trick to the "README" document in a more prominent place. It's already in the "FAQ" section but it needs more context for folks to understand the utility of it.

Also, my apologies for taking over four hours to respond initially but I just got up here on the West Coast to the United States. :) I assume you're in Europe or on the East Coast?

**Comment by Bob-Collins** [comment]
Yes, East coast here, and I am hardly an expert, just trying to figure this all out.  I figure older stuff like Perry Mason are definitely film, and should probably be limited to 24 fps, while newer stuff is video at 30 fps.  Not sure what the detelecine does, but the combination of the 2 seems to have resolved my issue with it, now I just need to redo the first four season which I had already done before, and then do the last 5 seasons.

**Comment by donmelton** [comment]
@Bob-Collins Well, this is the way you become an expert. :)

The "detelecine" filter is weird but useful. As you guessed, it has to do with the conversion of film to video. You can find out more about the original process here:

https://en.wikipedia.org/wiki/Telecine

The filter tries to reverse that process by dropping duplicate frames to restore the pre-telecine frame rate. However, it can't always know what that frame rate is so you have to force it.

I'm sorry that you have to redo four seasons know. Thankfully these are DVD rips so they'll be much faster than full 1080p transcodes.

**Comment by Bob-Collins** [comment]
Yes, they are all DVD rips, and I am using a batch file to get them all, so I just let the machine run and it keeps churning them out.  One thing I want to play with is specifying and output path, and having the different seasons wind up separated already, but things are fine just dumping all into the same directory where I am running the command from.

I would like some tips from you on creating scripts for Windows, and maybe having it just process every file in a directory instead of me having to specify each filename explicitly on a command line.  Currently I am using something like this:

call transcode-video --force-rate 23.976 --filter detelecine --crop 0:0:6:4 "E:\Plex\Perry Mason\Season 01\Perry Mason - s01e01 - The Case of the Restless Redhead.mkv"
call transcode-video --force-rate 23.976 --filter detelecine --crop 0:0:0:0 "E:\Plex\Perry Mason\Season 01\Perry Mason - s01e02 - The Case of the Sleepwalker's Niece.mkv"
call transcode-video --force-rate 23.976 --filter detelecine --crop 0:0:0:0 "E:\Plex\Perry Mason\Season 01\Perry Mason - s01e03 - The Case of the Nervous Accomplice.mkv"

I know I don't need to specify the all zeros on the crop, but there are a few titles where it is needed, so it is easier to just paste it in for every file.

**Comment by donmelton** [comment]
@Bob-Collins That seems efficient. And I understand your crop usage now. Makes sense.

I wish I could advise you on scripting on Windows but I don't have any current experience on that platform. However, @samhutchins and @JMoVS, the authors of our Windows installation documentation, might be able to point you in the right direction.

**Comment by JMoVS** [comment]
@Bob-Collins Yeah, if you look at the readme, Sam and me created a repo where we documented two ways. But the way Sam documented with using binaries is definitely the recommended way. I guess (@samhutchins can chime in here) that using windows shell scripts should serve you well.

**Comment by Bob-Collins** [comment]
I have things installed already, I was asking for some assistance or guidance on using scripts or .bat files in Windows to control transcode-video.

**Comment by JMoVS** [comment]
@Bob-Collins ah sry, ok. I don't have much personal experience with that, but I guess @samhutchins has?

**Comment by samhutchins** [comment]
If the settings are all the same you could probably do something like this in the bat file:

```
for %%i in (*.mkv) do call transcode-video --force-rate 23.976 --filter detelecine "%%i" --output "%%~ni_out.%%~xi"
```

When I last did a batch like this I write some crappy python script, but I can't find it any more :-(. I went to python because parsing the crop values out of a text file in a batch file sounds like a pretty horrible way to spend an evening

**Comment by donmelton** [comment]
Thanks for the scripting foo, @samhutchins! :)

Yeah, I don't bother cropping TV episodes unless it's something extreme like original `4:3` aspect ratio content in a `16:9` frame, i.e. with big "pillar box" black bars on either side. Which is exactly the case for the "Twin Peaks" released on Blu-ray.

**Comment by samhutchins** [comment]
No problem.

Since it's a one-liner you can do that directly in the CMD window, but use single `%` instead:

`for %i in (input\*.mkv) do call transcode-video "%i" --output "output\%~ni.mkv"`

**Comment by Bob-Collins** [comment]
Thanks for the help!

**Comment by donmelton** [comment]
OK folks, I will close this for now since the original issue has been resolved. But feel free to continue commenting.

**Comment by Bob-Collins** [comment]
So would it hurt to use the --force-rate 23.976 --filter detelecine when transcoding old TV shows, even if they did not need it or exhibit the choppiness originally?

**Comment by donmelton** [comment]
@Bob-Collins Probably not, but you should check that with a few videos first. And it would slow down transcoding slightly.
