### ISSUE TITLE
MKV to MKV, reducing size but leaving interlaced?

### ISSUE THREAD

**Issue by markmarz** [donmelton/video_transcoding#126]
Hi Don,

This may sound strange, but what I'm getting at is trying to solve the problem that some interlaced DVD rips just don't deinterlace as well as I'd like. I have a little Perl script that produces a 3 minute cut of an MKV produced by MakeMKV for each deinterlace method offered: default, deinterlace, detelecine and decomb. It also outputs the same cut as the original MKV. The output goes to a share Plex sees, so I can easily compare all 5 on a TV screen.

In some cases, usually TV shows, it's easy to see the loss of quality compared to the original MKV. I'm not an expert on all the possible transcode-video & Handbrake options, but I have experimented with --target big in combination with --cvbr, and still no go.

What I usually do in a case like this is just forget about transcode-video and stick the MKV right on my Plex server. My Plex clients are a Raspberry PI 2 and 3 running Kodi with a beta plugin called Plex for Kodi. This client displays the MKV beautifully without requiring a Plex transcode.  Of course now I have extra large MKVs on my server.

So I was thinking. If Kodi & Plex & Raspberry do such a nice job deinterlacing, why not let them do that against a reduced size MKV? I may be completely off-base here, but does it make any sense to have an option for transcode-video to apply his marvelous algorithms without deinterlacing, producing either an MKV or MP4? My hope is that I'd get the benefit of reduced size, and let the client handle deinterlacing.

My apologies if this boils down to a dumb question, I don't know if in my ignorance I'm asking for something counter to the design.

Thanks,
Mark M

**Comment by donmelton** [comment]
@markmarz There's no option in `HandBrakeCLI` to preserve interlaced input when transcoding. You could pass options through to the x264 encoder and enable interlaced transcoding mode, but that really only works well if the input is actually progressive, i.e. not interlaced.

So, your feature request is, unfortunately, not really practical. Sorry about that.

I realize you experimented with the various filters already, but it's likely that "detelecine" would have worked for you if you also forced a frame rate. This is what I do problematic videos like the ones you describe:

```
transcode-video --filter detelecine --force-rate 23.976 "/path/to/Movie.mkv"
```

That's assuming, of course, that the original or correct frame rate is `23.976` FPS.

**Comment by markmarz** [comment]
@donmelton Oh, well, too bad on the interlacing option. OTOH I'm looking forward to experimenting with the frame rate in combination with detelecine. I've had good luck with detelecine in general, I'm confident your frame rate suggestion will help a lot.

Thanks!
Mark

**Comment by donmelton** [comment]
@markmarz If it doesn't, open another issue and let me know. Good luck, sir!

**Comment by docmcfreckles** [comment]
I've successfully been able to preserve interlaced video by using the -E switch to add bff or tff tag for the x264 encoder.  it does have some drawbacks as I get a warning about interlaced and weightp not being compatible, and the need to determine field order. In addition I made sure to specify --filters for no telecine, no decomb, no comb detect, no deinterlace.

**Comment by docmcfreckles** [comment]
@donmelton I've successfully been able to preserve interlaced video by using the -E switch to add bff or tff tag for the x264 encoder.  it does have some drawbacks as I get a warning about interlaced and weightp not being compatible, and the need to determine field order. In addition I made sure to specify --filters for no telecine, no decomb, no comb detect, no deinterlace.

**Comment by markmarz** [comment]
Hi Don,

Thanks very much for your diligence!

Unfortunately I'm not clear on the -E switch. I've checked the Handbrake
CLI guide and the only -E option I can find is for Audio, although I did
find an -e switch for Video. I've played around with -Ebff and -Etff, -ebff
and -etff and they're all invalid.

Here's one attempt:
transcode-video --target big --filter no-detelecine --filter no-decomb
--filter no-comb-detect --filter no-deinterlace --force-rate 29.970 -Ebff
 "E:\dvd_input\Monk\Season 01/Monk - S01E04.mkv" -o
"E:\dvd_output\Monk\Season 01\Monk - S01E04 bff.mkv"

Please correct my attempt when you get a chance. Thank you very much!

- Mark M.

**Comment by donmelton** [comment]
@docmcfreckles Yeah, the hard thing is knowing whether to use the top or bottom field first. :) Also, you can disable `weightp` with `--encoder-option weightp=0` or `-E weightp=0` so you don't get the warning.

@markmarz The `-E` option that @docmcfreckles mentioned is not from `HandBrakeCLI`, it's from `transcode-video`. And it's a shorthand for `--encoder-option`. And you need a space between the option and the argument, plus a value for that argument key, like this: `E bff=1`

Here's a corrected version of your command line:

```
transcode-video --target big --filter no-detelecine --filter no-decomb \
--filter no-comb-detect --filter no-deinterlace --force-rate 29.970 -E bff=1 \
"E:\dvd_input\Monk\Season 01/Monk - S01E04.mkv" -o \
"E:\dvd_output\Monk\Season 01\Monk - S01E04 bff.mkv"
```

Does that help?

**Comment by markmarz** [comment]
Thank you!

**Comment by docmcfreckles** [comment]
@markmarz  as don mentioned the tricky bit is determining whether you have bff or tff in your interlaced content. the metadata that the encoder gives isn't always accurate. One shortcut I've used is to have ffmpeg give you it's best determination for a section of the video
```
ffmpeg -filter:v idet \ # use the video filter idet
-ss 00:10:00 \ # fast forward 10 minutes into the source
-frames:v 1000 \ # sample 1000 frames
-an \ # strip audio
-f rawvideo \ # output the frames as raw video for the idet filter to operate on
-y /dev/null \ # dump the output to /dev/null (*nixism) after we're done with it
-i title01.mkv```

I used this for my box set of Married with Children, where the opening credits were shot on film, telecine'd with a 3:2 pulldown but the body of the show was shot video, necessitating the jump ahead in the source.

The authoritive way (that the internet told me) to determine bff/tff is to split the fields with something like avisynth and then view them by hand to determine order but I don't have the patience and the whole thing confused me as I didn't know what I was looking at. hence the "good enough" solution by getting ffmpeg to guess given above.

**Comment by markmarz** [comment]
Ah, Don's top/bottom comment went right over my head. Thank you for
clarifying this and offering a workable method to figure it out.

The output I get from your ffmpeg invocation includes:
  Stream #0:0(eng): Video: mpeg2video (Main), yuv420p(tv, *top first*),
720x480 [SAR 32:27 DAR 16:9], SAR 186:157 DAR 279:157, 29.97 fps, 29.97
tbr, 1k tbn, 59.94 tbc

top first = TFF, right?

**Comment by markmarz** [comment]
Ah, Don's top/bottom comment went right over my head. Thank you for
clarifying this and offering a workable method to figure it out.

The output I get from your ffmpeg invocation includes:
  Stream #0:0(eng): Video: mpeg2video (Main), yuv420p(tv, **top first**),
720x480 [SAR 32:27 DAR 16:9], SAR 186:157 DAR 279:157, 29.97 fps, 29.97
tbr, 1k tbn, 59.94 tbc

top first = TFF, right?

**Comment by donmelton** [comment]
@docmcfreckles You are officially a geek knowing that trick. :) Seriously, I forgot all about the `idet` filter in `ffmpeg`. Thanks!

@markmarz Yes, that means "top first" so you would use `-E tff=1` on your `transcode-video` command line instead.

**Comment by docmcfreckles** [comment]
@markmarz actually, that is the information that comes from the encoder metadata, not what ffmpeg thinks of the input... at the bottom you should see a report:
```
video:506250kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
[Parsed_idet_0 @ 0x557144f17600] Repeated Fields: Neither: 18980 Top:     2 Bottom:     1
[Parsed_idet_0 @ 0x557144f17600] Single frame detection: TFF:     0 BFF: 17429 Progressive:   143 Undetermined:  1411
[Parsed_idet_0 @ 0x557144f17600] Multi frame detection: TFF:     0 BFF: 18965 Progressive:     4 Undetermined:    14
```

if most of the frame detection falls in the `TFF:` column, ffmpeg thinks it's tff, if most falls in `BFF:` then ffmpeg thinks it's bff, and if it `Progressive:` wins, congrats you don't have to bother with interlaced...

@donmelton thanks for the kudos, but, I can't claim credit, i'm a lowly hacker who can just google better than the average bear ;-)

**Comment by markmarz** [comment]
Thanks for the clarification! The upshot for me is to favor alternatives to
preserving interlacing if possible. Too much uncertainty.

In my use case I can live with interlaced video even though I can't take
advantage of transcode-video, because my clients do a good job handling
interlaced video.
