### ISSUE TITLE
Force frame rate & detelecine works best; still some artifacts; conflict with --cvbr?

### ISSUE THREAD

**Issue by markmarz** [donmelton/video_transcoding#127]
Hi Don,

Your suggestion to force output frame rate to match input, plus detelecine, worked very well. Here's the options I used to generate sample output:
 --mp4 --target big -H start-at=duration:240 -H stop-at=duration:300 -H _markers -H detelecine  --force-rate 29.970

It's by far the best deinterlacing result for problematic videos. There are still some artifacts on very close inspection: I've found looking at the curved roof line of moving cars is a good place to hunt them down. My guess is this is the best result possible, at least for a reasonable amount of experimentation per video. If I put too much time into various options it can get to the point where it's not worth my time and I just revert to the original MKV.

All that said, --target big --cvbr does conflict with --force-rate, right? The result is not good, and I can see that the frame rate is not what was forced.

Oh, one other question: when matching output frame rate to input frame rate, which input frame rate do I use in the case where more than one is shown in MediaInfo? I guess NOT the Original frame rate; right?

`Frame rate mode                          : Variable`
`Frame rate                               : 24.576 FPS`
`Original frame rate                      : 29.970 (30000/1001) FPS`

Thanks,
Mark M

**Comment by donmelton** [comment]
@markmarz I'm glad that worked out! :)

There's no conflict with those options, but `--cvbr` is an advanced and experimental ratecontrol system designed to stabilize x264 VBV behavior. And it will sometimes produce lower quality even with `--target big` added.

My recommendation is that you use the default rate control system instead and avoid `--cvbr` for now.

As to your frame rate question, you are correct -- that's not the original value. Bonus points for using MediaInfo to check, but realize it doesn't always get that right. Which is a pity.

Unfortunately, I can't give you absolute guidelines on this. You just have to experiment. My apologies. The good news is that for most DVDs, the right answer is `23.976` FPS.

**Comment by markmarz** [comment]
Okay, I have to follow up, sorry. It's a darn shame that MediaInfo isn't accurate, because I incorporated it into my batch process to plug in the input (and therefore --force-rate value) frame rate. But if I look at the Handbrake log, it appears that he's determining the rate as well. For the video I'm looking at, it happens to be 29.970, which happens to match MediaInfo.

`[09:25:54] scan: decoding previews for title 1`
`[09:25:54] scan: audio 0x1: ac3, rate=48000Hz, bitrate=224000 English (AC3) (2.0 ch)`
`[09:25:54] scan: 10 previews, 720x480, 29.970 fps, autocrop = 0/0/2/0, aspect 16:9, PAR 32:27`

I accept I can't trust MediaInfo, but can I trust Handbrake? Perhaps I'll cludge up a way to use Handbrake to give me the correct frame rate.

Thanks,
Mark

**Comment by donmelton** [comment]
@markmarz Actually, MediaInfo is accurately reporting on the attributes and metadata in your source file. However, that information, especially for DVDs, can be misleading and MediaInfo is not "interpreting" that correctly. HandBrake doesn't do any better at this either. I'm not sure any piece of software alone can get this right. That's why you have to experiment.

**Comment by markmarz** [comment]
Ah, okay. So sad!!
Hah-hah! Should this be my biggest problem! Hah!

Thanks Don, you've been terrific.

**Comment by donmelton** [comment]
@markmarz You are very welcome, sir!

I'll close this now but feel free to continue commenting.
