### ISSUE TITLE
Unable to batch transcode videos on Windows 10

### ISSUE THREAD

**Issue by OspreyPrey** [donmelton/video_transcoding#128]
I have written my commands into notepad and saved it as batch.bat ([attached here as a text file](https://github.com/donmelton/video_transcoding/files/775549/batch_bat.txt)). When I start the batch, it will transcode the first video just fine then quit upon completion of the first file and will not continue down the line. 

Here are the versions of dependencies
- Ruby v.2.3.3
- video-transcoding v.0.16.0
- HandbrakeCLI v.1.0.2
- ffmpeg v.3.2.2, 
- mkvtoolnix v.9.8.0
- mplayer v.37905
- mp4v2 v.504

I am hoping that either you, @samhutchins or @JMoVS can weigh in on what may be happening or if I have something misconfigured.

Additionally, when transcoding, the status returns a new line every time it updates it progress (~.2 sec) resulting in a huge log file, and the command prompt window is utterly useless when full of 30 minutes of status updates. Is anyone else experiencing this too? ([sample log file](https://github.com/donmelton/video_transcoding/files/775596/Silent.Movie.1976.txt))

**Comment by donmelton** [comment]
@OspreyPrey I don't think you have anything misconfigured. And I simply don't know enough about Windows batch files to know what could be wrong there. Hopefully, @samhutchins will come to the rescue on that one.

As to the .log size, that's also odd although a megabyte-sized file wouldn't really surprise me.

You should expect your command prompt window to inaccessible during transcoding.

**Comment by samhutchins** [comment]
@OspreyPrey 

You need to put `call` in front of every command, I've updated your provided batch file:
[batch_bat.txt](https://github.com/donmelton/video_transcoding/files/776349/batch_bat.txt)

When ruby gems are installed on Windows they are invoked through a .bat file which essentially wraps a `ruby` command. Batch files can't call multiple other batch files without using the `call` command, because "legacy". More info here: http://stackoverflow.com/a/1104093

Looking at your script you could probably replace it with a for loop though:

CMD version:  
```
for %i in (C:\Users\Rusaw Family\Videos\MKV\*.mkv) do call transcode-video --no-log --output "C:\Users\Rusaw Family\Videos\Library" "%i"
```

batch file version:
```
@echo off
for %%i in (C:\Users\Rusaw Family\Videos\MKV\*.mkv) do call transcode-video --no-log --output "C:\Users\Rusaw Family\Videos\Library" "%%i"
```

The difference between the two is the double %, which is needed in batch files. Go Microsoft

**Comment by donmelton** [comment]
@samhutchins Thanks! I would have never figured this out for @OspreyPrey.

**Comment by OspreyPrey** [comment]
Thanks @samhutchins 
This seems like a simple enough issue, maybe it should be included in the readme? If not the main readme then definitely the one for installing video-transcoding on windows.

@donmelton I will test this later tonight when I have a few movies to transcode. Doesn't sound like I should have any problems.

**Comment by donmelton** [comment]
@OspreyPrey Cool. OK, I'll close this for now but comment here again if you're still having trouble.

**Comment by samhutchins** [comment]
@OspreyPrey I thought so too: https://github.com/JMoVS/installing_video_transcoding_on_windows/pull/6 :-D

**Comment by donmelton** [comment]
@samhutchins That's the perfect example script, too. Thanks!
