### ISSUE TITLE
Batch script needs modification for Ubuntu Linux

### ISSUE THREAD

**Issue by spiritphyz** [donmelton/video_transcoding#136]
Hi Don,

I used to do my batch transcoding on a Mac laptop and there were no problems. Your scripts are awesome, and I could queue up many files for transcoding at night before going to sleep.

Recently, I tried using the same `batch.sh` script on Ubuntu and ran into this error:
```
sed: can't read 1d: No such file or directory
```

Here's what I had to do to fix the script so it would work on Linux. I guess there are some weird differences with the "in-place" option for BSD sed vs. the GNU sed on Linux? 

old:
`sed -i '' 1d "$queue" || exit 1`
new:
`sed -i 1d "$queue" || exit 1`

Maybe you can come up with a "proper" solution so the `batch.sh` script works on Ubuntu, too? Here are the systems I'm running. (I guess the version numbers for sed aren't available because the utility is considered part of the operating system):

macOS 10.12.13
Ubuntu 16.04.2 LTS

Thank you, Don, for creating the scripts and being responsive to all the user issues raised!

**Comment by donmelton** [comment]
@spiritphyz Tony, thanks for opening this issue! I didn't realize that sample batch script would fail on Linux. No one has ever reported that.

It's likely I'll just have to document the difference since after some experiments and then research yielding this information:

http://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux

...it seems like this is an intractable problem. :)

**Comment by spiritphyz** [comment]
Oh my goodness, your Google-Fu to find an _exact_ StackExchange discusison is impressive! I had to dig through so many unrelated search results for a few days to figure out what was going on. 

That's very unfortunate that there's a tiny difference between the BSD and GNU platforms that you can't have a s sed incantation that works on both. :(

Feel free to close this issue (but hopefully future users can find this in the "Closed Issues" archives).

**Comment by donmelton** [comment]
@spiritphyz I actually used DuckDuckGo to find that. :) Thanks for closing. I'll keep this in mind when I update the documentation anyway.

**Comment by spiritphyz** [comment]
I think other people may have tried to use your batch script on Linux, encountered an error, and didn't know what to do about it.

I was really irritated that the script worked on another Unix-ish platform but wasn't working on Linux, and was really motivated to get the batch encoding work again!

According to a linked answer, there could be simple workaround:
http://unix.stackexchange.com/questions/92895/how-to-achieve-portability-with-sed-i-in-place-editing

> If you want to write a portable script, don't use -i — it isn't in POSIX. Do manually what sed does under the hood — it's only one more line of code.
```
sed -e '…' "$file" >"$file.new"
mv -- "$file.new" "$file"
```
Is adding a "mv" command an option for your script?

**Comment by donmelton** [comment]
@spiritphyz That would work. It just makes the script longer. :)

Here's how I might rewrite that line:

```
    sed 1d "$queue" >"$queue.$$" && mv "$queue.$$" "$queue" || exit 1
```

That uses the current process ID as a unique file extension.
