### ISSUE TITLE
Not working on latest iTunes DRM?

### ISSUE THREAD

**Issue by amlcreative** [donmelton/video_transcoding#140]
I just tried to transcode an iTunes new release rental.

Example
`transcode-video --quick --mp4 /path/to/iTunes/iTunes\ Media/Movies/rental.m4v`

I also tried without --quick and --mp4. After running with -vv, here is the full output.

[https://pastebin.com/ueB5CAwZ](https://pastebin.com/ueB5CAwZ)

I've been able to transcode other m4v files.

Is this just me or are others experiencing this issue?

**Comment by amlcreative** [comment]
I used the --scan -vv command and this is the output, not sure if it helps troubleshoot or not
`transcode-video 0.17.2
Copyright (c) 2013-2017 Don Melton
HandBrake 1.0.3 found...
Processing: /Users/saralazio/Music/iTunes/iTunes Media/Movies/Fantastic Beasts and Where to Find Them/01 Fantastic Beasts and Where to Find Them (1080p HD).m4v...
Scanning media title 1 with HandBrakeCLI...
[10:26:13] hb_init: starting libhb thread
[10:26:13] thread 700000081000 started ("libhb")
HandBrake 1.0.3 (2017022600) - Darwin x86_64 - https://handbrake.fr
4 CPUs detected
Opening /Users/saralazio/Music/iTunes/iTunes Media/Movies/Fantastic Beasts and Where to Find Them/01 Fantastic Beasts and Where to Find Them (1080p HD).m4v...
[10:26:13] CPU: Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
[10:26:13]  - Intel microarchitecture Sandy Bridge
[10:26:13]  - logical processor count: 4
[10:26:13] hb_scan: path=/Users/saralazio/Music/iTunes/iTunes Media/Movies/Fantastic Beasts and Where to Find Them/01 Fantastic Beasts and Where to Find Them (1080p HD).m4v, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
disc.c:274: failed opening UDF image /Users/saralazio/Music/iTunes/iTunes Media/Movies/Fantastic Beasts and Where to Find Them/01 Fantastic Beasts and Where to Find Them (1080p HD).m4v
disc.c:352: error opening file BDMV/index.bdmv
disc.c:352: error opening file BDMV/BACKUP/index.bdmv
[10:26:13] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread: Encrypted DVD support unavailable.
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[10:26:13] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/saralazio/Music/iTunes/iTunes Media/Movies/Fantastic Beasts and Where to Find Them/01 Fantastic Beasts and Where to Find Them (1080p HD).m4v':
  Metadata:
    major_brand     : M4V 
    minor_version   : 0
    compatible_brands: M4V mp42isom
    creation_time   : 2017-03-10 03:55:26
    title           : Fantastic Beasts and Where to Find Them
    artist          : David Yates
    album           : Coleo Animais Fantsticos e Onde Habitam + Harry Potter e a Pedra Filosofal
    genre           : Action & Adventure
    track           : 1/2
    disc            : 1/1
    compilation     : 0
    date            : 2017-03-14T07:00:00Z
    description     : Fantastic Beasts and Where to Find Them opens in 1926 as Newt Scamander has just completed a
    hd_video        : 2
    media_type      : 9
    purchase_date   : 2017-04-06 23:56:11
    sort_name       : Fantastic Beasts and Where to Find Them
    sort_album      : Coleo Animais Fantsticos e Onde Habitam + Harry Potter e a Pedra Filosofal
    sort_artist     : David Yates
    synopsis        : Fantastic Beasts and Where to Find Them opens in 1926 as Newt Scamander has just completed a global excursion to find and document an extraordinary array of magical creatures. Arriving in New York for a brief stopover, he might have come and gone without incidentwere it not for a No-Maj (American for Muggle) named Jacob, a misplaced magical case, and the escape of some of Newts fantastic beasts, which could spell trouble for both the wizarding and No-Maj worlds.
  Duration: 02:12:50.73, start: 0.000000, bitrate: 5587 kb/s
    Chapter #0:0: start 0.000000, end 520.000000
    Metadata:
      title           : 1
    Chapter #0:1: start 520.000000, end 1135.000000
    Metadata:
      title           : 2
    Chapter #0:2: start 1135.000000, end 1703.000000
    Metadata:
      title           : 3
    Chapter #0:3: start 1703.000000, end 2314.000000
    Metadata:
      title           : 4
    Chapter #0:4: start 2314.000000, end 2888.000000
    Metadata:
      title           : 5
    Chapter #0:5: start 2888.000000, end 3496.000000
    Metadata:
      title           : 6
    Chapter #0:6: start 3496.000000, end 4154.000000
    Metadata:
      title           : 7
    Chapter #0:7: start 4154.000000, end 4646.000000
    Metadata:
      title           : 8
    Chapter #0:8: start 4646.000000, end 5373.000000
    Metadata:
      title           : 9
    Chapter #0:9: start 5373.000000, end 5882.000000
    Metadata:
      title           : 10
    Chapter #0:10: start 5882.000000, end 6627.000000
    Metadata:
      title           : 11
    Chapter #0:11: start 6627.000000, end 7144.000000
    Metadata:
      title           : 12
    Chapter #0:12: start 7144.000000, end 7451.000000
    Metadata:
      title           : 13
    Chapter #0:13: start 7451.000000, end 7970.678000
    Metadata:
      title           : 14
    Stream #0:0(eng): Audio: aac (LC) [drms / 0x736D7264]
      48000 Hz, stereo, fltp, 156 kb/s (default)
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Audio
    Stream #0:1(eng): Video: drmi / 0x696D7264 [drmi / 0x696D7264]
      none, tv, bt709/bt709/bt709
      1912x792, 4559 kb/s, PAR 1:1 DAR 239:99
      23.98 fps, 23976 tbn (default)
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Video
    Stream #0:2(eng): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0 (default)
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:3(eng): Subtitle: p608 / 0x38303670, 0 kb/s (default)
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Closed Caption
    Stream #0:4(fra): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:5(spa): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:6(spa): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:7(ara): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:8(bul): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:9(zho): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:10(zho): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:11(ces): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:12(dan): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:13(deu): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:14(ell): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:15(spa): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:16(est): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:17(fin): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:18(fra): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:19(heb): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:20(hun): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:21(ita): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:22(lit): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:23(lav): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:24(nld): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:25(nor): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:26(pol): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:27(por): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:28(por): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:29(rus): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:30(slk): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:31(slv): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:32(swe): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:33(tha): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:34(tur): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:35(zho): Data: drmt / 0x746D7264, 0 kb/s, PAR 59:396 DAR 0:0
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Subtitle
    Stream #0:36(eng): Subtitle: mov_text
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Text
    Stream #0:37(und): Video: mjpeg [jpeg / 0x6765706A]
      yuvj444p, pc, bt470bg/unknown/unknown
      640x266 [PAR 72:72 DAR 320:133], 3 kb/s, PAR 65536:84999 DAR 859720:463439
      1k tbn
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Video
    Side data:
      displaymatrix: rotation of -0.00 degrees
    Stream #0:38(eng): Audio: drms / 0x736D7264 [drms / 0x736D7264]
      48000 Hz, 5.1, 384 kb/s
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Audio
    Side data:
      audio service type: main
    Stream #0:39(fra): Audio: aac (LC) [drms / 0x736D7264]
      48000 Hz, stereo, fltp, 156 kb/s
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Audio
    Stream #0:40(spa): Audio: aac (LC) [drms / 0x736D7264]
      48000 Hz, stereo, fltp, 156 kb/s
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Audio
    Stream #0:41(eng): Audio: aac (LC) [drms / 0x736D7264]
      48000 Hz, stereo, fltp, 155 kb/s
    Metadata:
      creation_time   : 2017-03-10 03:55:26
      handler_name    : Core Media Audio
    Stream #0:42: Video: mjpeg
      yuvj444p, pc, bt470bg/unknown/unknown
      667x1000 [PAR 1:1 DAR 667:1000]
      90k tbn
[10:26:13] add_ffmpeg_subtitle: unknown subtitle stream type: 0x0
[10:26:13] scan: decoding previews for title 1
Scanning title 1 of 1, preview 1, 50.00 %[10:26:13] scan: audio 0x0: aac, rate=48000Hz, bitrate=156763 English (AAC) (2.0 ch)
[10:26:13] scan: audio 0x27: aac, rate=48000Hz, bitrate=156741 Francais (AAC) (2.0 ch)
[10:26:13] scan: audio 0x28: aac, rate=48000Hz, bitrate=156632 espaol (AAC) (2.0 ch)
[10:26:13] scan: audio 0x29: aac, rate=48000Hz, bitrate=155566 English (AAC) (2.0 ch)
Scanning title 1 of 1, preview 1, 50.00 %[10:26:14] scan: could not get a decoded picture
Scanning title 1 of 1, preview 2, 100.00 %[10:26:15] scan: could not get a decoded picture
[10:26:15] scan: decoding previews for title 1
...
Scanning title 1 of 1, preview 1, 50.00 %[10:26:16] scan: could not get a decoded picture
Scanning title 1 of 1, preview 2, 100.00 %[10:26:16] scan: could not get a decoded picture
[10:26:16] libhb: scan thread found 0 valid title(s)
No title found.
HandBrake has exited.

/usr/local/bin/transcode-video: scanning media title 1 failed`

**Comment by donmelton** [comment]
@amlcreative My `transcode-video` tool knows nothing about DRM or encryption. Instead, it relies on you, the user, to feed it unencrypted data or, as a last resort, for `HandBrakeCLI` to do something about it.

Thanks for including your full output! And, as you can see in this line from that output, `HandBrakeCLI` was unable to do anything the encryption:

```
Scanning title 1 of 1, preview 1, 50.00 %[10:11:54] scan: could not get a decoded picture
```

I'm really surprised that you were ever able to transcode any movie rentals from the iTunes Store. I couldn't even guess as to how that ever worked. Do you have some other special software installed that decrypts automatically for you?

**Comment by amlcreative** [comment]
I never tried a rental before, but I thought it might work. My mistake. The other m4v's were not encrypted.

**Comment by donmelton** [comment]
@amlcreative Ah, OK. That makes sense.

BTW, there's usually no reason to transcode `.m4v` files. They're already in MP4 format so the video and audio is likely compact and in the correct formats. You can either rename them with a `.mp4` extension or use my `convert-video` tool to convert them to `.mkv` files in Matroska format.

I'll close this now but feel free to continue commenting.
