### ISSUE TITLE
Requesting More Control Over audio output via options

### ISSUE THREAD

**Issue by brutalgg** [donmelton/video_transcoding#142]
currently I'm using --add-audio all options which outputs mostly how I want. What it currently does is create a AC3 Audio track and then a copy of it as AAC. The AC3 is the first and default audio track and AAC is 2nd. I would like to reorder the tracks to have the AAC first and default followed by the AC3 since many of my devices do not support surround so plex starts transcoding audio. Today I go in and change this manually via mkvtoolnix but being able to change the settings would be ideal.

**Comment by donmelton** [comment]
@brutalgg If you want the duplicate main audio tracks re-ordered, then use the `--mp4` or `--m4v` options to output to MP4 format. That will put the AAC track first and the AC-3 track second.

**Comment by brutalgg** [comment]
I've been avoiding using the MP4 container because of its oddities when it comes to subtitles. I was hoping to specify the same audio priority for Mkv.

**Comment by donmelton** [comment]
@brutalgg I'm sorry, but there's not an option to do that. And I'm not inclined to add that as a feature since it's not a good idea for portability. Besides, Plex can be easily configured to ignore AC-3 track. But why not just use `--audio-width main=stereo` and forget about the AC-3 track?

**Comment by brutalgg** [comment]
I'll look into your suggestion. Thanks for the insight.
