### ISSUE TITLE
x264_10bit support.

### ISSUE THREAD

**Issue by beetwaaf** [donmelton/video_transcoding#143]
I'd love to get some official 10bit support. I've managed to patch it in myself but I've probably broken something in the process. 
I tried all commands I could think of, and while I did manage to get the commands to process, they were then overriden by the built-in defaults resulting in a 8bit file in the end.

**Comment by donmelton** [comment]
@beetwaaf 10-bit support is dependent on HandBrake. There's nothing that `transcode-video` does to affect that. Did you build a patched version of `HandBrakeCLI` for your experiments? From your description, it's unclear who was overriding what. Please elaborate.

**Comment by beetwaaf** [comment]
These are my settings:
transcode-video D:\Transcoding\Movie.mkv --quick --no-auto-burn --no-audio -E vbv-maxrate=0000 -E vbv-bufsize=0000 --output D:\Transcoding\Transcoded.mkv

When I then added in the -H encoder=x264_10bit option this would not take effect with transcode-video.
It does however when I try to set the encoder in handbrakeCLI bypassing your program. 

What I changed was the encoder options in your main transcode-video from x264 to x264_10bit which then allowed me to output 10bit video which I couldn't before.

I am not very knowledgeable and don't know a whole lot of programming so I probably broke something doing this but it worked.

My guess is that it needs another argument added in just like x265 with the high10 profile instead of high etc.

**Comment by donmelton** [comment]
@beetwaaf OK, now I see what you mean. Yes, this is a stupid "limitation" in `transcode-video`, meaning we should treat it as a bug. :) I can fix that.

If I allow `x264_10bit` as an encoder name, then I suppose I should also allow `x265_10bit`, `x265_12bit` and `x265_16bit`.

I can also automatically set the profile to `high10` when `x264_10bit` is selected.

I'm not sure what you mean by `x265` though. I think the correct profile for 10-bit there would `main10`.

**Comment by donmelton** [comment]
@beetwaaf BTW, this will likely take some time to test so I wouldn't expect the fix to be released until this weekend. Sorry about that.

And thanks again for filing this! Seriously.

**Comment by beetwaaf** [comment]
What I meant with the x265 line was that both x264 and x265 have their own dedicated arguments and that to have 10bit support it also need to have its own dedicated arguments. You addressed this in your reply to me. 
As for reporting it, no problem, I just want to help whenever I feel like I can. 
Dont feel rushed either, having it addressed at some point is enough for me.

**Comment by donmelton** [comment]
@beetwaaf Oh cool, I was hoping that's what you meant. :) But I'll address this soon because I hate having stupid bugs get in the way of users like you who want to push the tools.

BTW, if you want to send me your patch, I'll gladly take a look at it. It couldn't hurt and we might both learn something in the process. But no worries.

Cheers!

**Comment by klogg416** [comment]
@beetwaaf, @donmelton My information might be out of date, but a couple of
months ago if you wanted to encode in 10 and 12 bits then you needed to
download some additional DLL files and drop them in the directory with the
handbrake binary.

This is the link to the DLLs in the forum, last updated 3/18 (each post in
that thread provides updated versions, scroll to the bottom).
https://forum.handbrake.fr/viewtopic.php?f=11&t=34165

And here is the 1.0.0 release notes citing the need for external libraries,
https://handbrake.fr/news.php?article=37.
"- High bit depth encoding support via external shared libraries (video
pipeline is still 8-bit 4:2:0)
  - x264 10-bit
  - x265 10-bit and 12-bit"

All this to say that in addition to any update to video_transcode, don't
forget to collect all the pieces of handbrake. Good luck!!

**Comment by beetwaaf** [comment]
@klogg416 
I'm aware, the issue was with the scripts not interperating the -handbrake-option command properly with the 10bit encoder

@donmelton 
It's not really a patch, rather a hack. What I did was replace
'encoder' => 'x264' with 'encoder' => 'x264_10bit' under def process_input(arg)
why I don't know, but it seems like just changing 
case encoder
when 'x265'
        handbrake_options['encoder-profile'] = 'main'
      end
with
when 'x264_10bit'
        handbrake_options['encoder-profile'] = 'high10'
      end
still doesn't allow 10bit to properly start, my guess is that it's my fault, but I simply don't know ruby and rather looked at what should make sense in letting 10bit start. I tried replacing all options with x265 to x264_10bit but unless I changed the encoder under def process_input It wouldn't encode to 10bit.

**Comment by donmelton** [comment]
@beetwaaf I'm finally getting to this today. Sorry it's taking so long but the virus and seasonal allergies are really kicking my ass. Anyway...

My patch is very simple:

```
diff --git a/bin/transcode-video b/bin/transcode-video
index 63aacb0..ac1d884 100755
--- a/bin/transcode-video
+++ b/bin/transcode-video
@@ -912,7 +912,7 @@ HERE
       end
 
       encoder = @handbrake_options.fetch('encoder', 'x264')
-      return unless encoder == 'x264' or encoder == 'x265'
+      return unless encoder =~ /^x264(?:_10bit)$/ or encoder =~ /^x265(?:_1[026]bit)$/
       handbrake_options['encoder-preset'] = 'medium'
 
       if width > 1920 or height > 1080
@@ -933,8 +933,12 @@ HERE
       when 'x264'
         handbrake_options['encoder-profile'] = 'high'
         handbrake_options['encoder-level'] = encoder_level
+      when 'x264_10bit'
+        handbrake_options['encoder-profile'] = 'high10'
       when 'x265'
         handbrake_options['encoder-profile'] = 'main'
+      when 'x265_10bit', 'x265_12bit', 'x265_16bit'
+        handbrake_options['encoder-profile'] = 'main10'
       end
 
       if @vbr_quality.nil?
@@ -972,7 +976,7 @@ HERE
 
       if  (@quick or @veryquick) and
           @handbrake_options.fetch('encoder-preset', 'medium') == 'medium' and
-          encoder == 'x264'
+          encoder =~ /^x264(?:_10bit)$/
         encoder_options['partitions']   = 'none'
         encoder_options['ref']          = '1'
         encoder_options['bframes']      = '1'     if @veryquick
```

And it seems to pass the correct options through to `HandBrakeCLI`. However, as @klogg416 has pointed out, it's all for naught without the external libraries. And those libraries don't seem to be available for macOS. So the patch is basically impossible for me to test.

I'm not sure that this enhancement is ready for release if it's so difficult to configure HandBrake for 10-bit support.

**Comment by donmelton** [comment]
@beetwaaf and @klogg416 I'm changing this from a bug to an enhancement request. I think we have to wait on official binaries from the HandBrake team before we make this change. Let me know what you think.

**Comment by beetwaaf** [comment]
@donmelton 
Tested the patch and with just a couple of quick tests it all seems to work perfectly, maybe something'll crop up but I myself can't see any issues.

As for including it in release. It's entirely up to you, I'd however wager that anyone interested in 10bit would know enough to be able and patch it in themselves from your previous post. 
Thanks a lot for providing a solution.

**Comment by donmelton** [comment]
@beetwaaf Well, it's good to know that it works. :) Seriously, thanks for testing that. I'll consider landing it anyway but it always makes me nervous changing that particular section of code.

**Comment by donmelton** [comment]
@beetwaaf I'm working on landing that patch tonight and it turns out there are hideous bugs in it! Here's the correct patch:

```
diff --git a/bin/transcode-video b/bin/transcode-video
index bb465b5..62620a0 100755
--- a/bin/transcode-video
+++ b/bin/transcode-video
@@ -912,7 +912,7 @@ HERE
       end
 
       encoder = @handbrake_options.fetch('encoder', 'x264')
-      return unless encoder == 'x264' or encoder == 'x265'
+      return unless encoder =~ /^x264(?:_10bit)?$/ or encoder =~ /^x265(?:_1[026]bit)?$/
       handbrake_options['encoder-preset'] = 'medium'
 
       if width > 1920 or height > 1080
@@ -933,8 +933,12 @@ HERE
       when 'x264'
         handbrake_options['encoder-profile'] = 'high'
         handbrake_options['encoder-level'] = encoder_level
+      when 'x264_10bit'
+        handbrake_options['encoder-profile'] = 'high10'
       when 'x265'
         handbrake_options['encoder-profile'] = 'main'
+      when 'x265_10bit', 'x265_12bit', 'x265_16bit'
+        handbrake_options['encoder-profile'] = 'main10'
       end
 
       if @vbr_quality.nil?
@@ -972,7 +976,7 @@ HERE
 
       if  (@quick or @veryquick) and
           @handbrake_options.fetch('encoder-preset', 'medium') == 'medium' and
-          encoder == 'x264'
+          encoder =~ /^x264(?:_10bit)?$/
         encoder_options['partitions']   = 'none'
         encoder_options['ref']          = '1'
         encoder_options['bframes']      = '1'     if @veryquick
```

The new version correctly accepts plain `x264` and `x265` as ` -H encoder=` arguments.

Sorry about that.

**Comment by donmelton** [comment]
@beetwaaf OK, the new patch has been checked in. I'll probably make a release with this in the next few days. Stay tuned.

**Comment by donmelton** [comment]
@beetwaaf All the changes are in version 0.17.3 which I just released. Thanks, again!

**Comment by beetwaaf** [comment]
@donmelton Thats great to hear! I love your tool and appreciate your effort in constantly improving it.

**Comment by donmelton** [comment]
@beetwaaf You are very welcome, sir! Keep the good ideas coming. :)
