### ISSUE TITLE
Missing a way to only copy audio/subtitles

### ISSUE THREAD

**Issue by MelkorLord** [donmelton/video_transcoding#144]
Hi,

I have a load of H264 documentaries I want to keep for archiving. No matter what I try, there's no way to ask <code>transcode-video</code> to **ONLY COPY** audio/subtitle streams without it trying to encode them.

I use a shell alias to specify default command line options like this : 

<code>alias TV='transcode-video --no-auto-burn --handbrake-option encoder=x265 --add-subtitle all --copy-audio all --prefer-ac3 --target 1080p=2600 --target 720p=1500'</code>

Case 1 : MKV contains 6CH AC3 audio => I get the original audio, this is fine

Case 2 : MKV contains 2CH AAC => Audio gets reencoded! I don't want that.

I'd like a way to **blindly** copy audio without ever trying to do anything else.

I also miss a <code>--copy-subtitles all</code> in the same manner. Instead of their original SRT subtitles, my videos end up with ASS/SSA subtitles which I certainly don't want.

In fact, I use <code>transcode-video</code> to deal **only** with the video part to gain some storage space but I can't get it to do just that.

I'd appreciate any insight on how to achieve that :smirk:

**Comment by donmelton** [comment]
@MelkorLord Sorry I took so long to reply. I'm actually fighting out a pesky virus right now. Pro tip: take your vitamin C.

If you want to copy all your audio tracks in their original format, don't use the `--prefer-ac3` option because it will force tracks not already in AC-3 format to be re-transcoded.

Your subtitles are being converted to ASS/SSA format because that's just how HandBrake and the `libav` library it uses works. FFmpeg has the same "feature." I hate it too, but the only way around it is using `mkvmerge` directly. And building logic into `transcode-video` and `convert-video` to do something similar would add significant complexity and code bloat. Which is something I'm not willing to do at the moment.

I hope that helps.

**Comment by samhutchins** [comment]
I guess you could use the `--no-audio` thing in transcode-video to get the h.264 stream, then use mkvmerge gui from [here](https://mkvtoolnix.download/downloads.html) to mux in the audio and subtitles from the original file

Not ideal, but the remuxing step at the end really quick

**Comment by MelkorLord** [comment]
@donmelton Since you helped me a lot by creating `transcode-video`, especially the "rate control" part which makes sense and is brilliantly put to use, I'll try to help you a bit :smile:  As often as you can (could be everyday), use green tea, with ***under boiling*** water, infuse for 5mins (for the useful tannoids to kick in, 2-3 min is only for the taste) but no longer than 7-8 min to avoid oxidation. Add cinnamon. Let cool down a bit (below 50°C/122°F) and add honey (which good properties are destroyed above that temp) as well as lemon juice (preferably fresh). Drink rapidly because the vitamin C in lemon juice will disappear by oxidation within 10min time. Now you have one of the most effective natural firewall your body can ask :) You'll see yourself in better shape and no more colds! Viruses still pass through but you'll have better defenses :smiley: 

Back to topic : 

I managed to get exactly the behavior I wanted by creating a shell script wrapper with the following settings after fiddling quite some time with HandBrake options
```
transcode-video \
  --add-audio all --copy-audio all \
  --add-subtitle ${LIST_LANGS} --no-auto-burn \
  --target 720p=${BITRATE_720} --target 1080p=${BITRATE_1080} \
  --handbrake-option encoder=x265 \
  --handbrake-option aencoder=copy \
  --handbrake-option all-audio \
  --handbrake-option _audio \
  --handbrake-option _audio-fallback \
  --handbrake-option subtitle-lang-list=${LIST_LANGS} \
  --handbrake-option all-subtitles \
  --handbrake-option _subtitle \
  "$@"
```

Perhaps you should add an option to do that exactly, which is only apply settings to the video and keep the audio, untouched or only filtered by language. In fact, I don't really understand why `transcode-video` ***insists*** on creating an extra 2CH AAC track when "--copy-audio all" is specified. There's no way to prevent this from happening in all scenarios I've tried.

In another post, I'll talk about another feature which could be useful about the `--target` option.

The only remaining issue is of course with the ASS/SSA subtitles which is HandBrake's fault according to their documentation. This is is a real PITA but I can manage some workarounds.

**Comment by donmelton** [comment]
@MelkorLord Thanks for the medical advice.

Now that I see what you're doing with that script, your audio option hacks are completely unnecessary. Just add `--audio-width all=surround` before your call to `--add-audio=all --copy-audio all`. That will prevent the extra copy of the main audio track being created and it will allow wider, i.e. surround tracks, elsewhere.

Why do I persist in creating two copies of the main audio track by default? Because, believe it or not, that's what most users want. I did a survey earlier this year on that subject and it was clear that a stereo AAC audio track is still needed by users with older hardware, particularly older models of Apple TV devices.

**Comment by MelkorLord** [comment]
@donmelton 

***1/*** Ok then. After extensive tests with various files from different sources and really various audio tracks, all the resulting files ended up in "audio passthru" mode without additional/undesired AAC tracks.

This really should end up in some kind of FAQ because without your help, I wouldn't have been able to find such a trick to achieve what I wanted, hence the "overkill" Handbrake options fiddling shown above.

***2/*** I don't have any problem with your default settings and most users wanting a stereo AAC track, that's your choice and I don't have any say in that :smile:  What I found a bit annoying was the fact that I had to fiddle a lot to get transcode-video work the way I wanted. I really thought it would be easier like `--no-default-stereo-audio` or something like this. And, by the looks of it, all this fiddling was overkill compared to the more elegant solution you mentioned above.

On my part, I consider this "issue" to be closed unless there's something to add to the discussion

**Comment by donmelton** [comment]
@MelkorLord Well, I'm just glad it worked for you in the end. :) I'll see about adding to the documentation but I do explain audio pretty thoroughly here:

https://github.com/donmelton/video_transcoding#understanding-audio

I'll close this now but feel free to keep commenting.

**Comment by MelkorLord** [comment]
@donmelton I read that part of the documentation several times to make sure I wasn't missing anything, yet, without the solution you provided, I couldn't figure out by myself how to make sure that only original and untouched audio was copied. Well, now I know how thanks to you.

Side note: I've encoded quite a bunch of files now and I really have to say that I'm quite impressed by your settings, the way you manage the quality/options part of the encoder. The result, provided we use a good value for `target` is astonishing! I've done a lot of frame-by-frame visual comparison at home and a friend allowed me to use his (very) high end TV equipment for a whole afternoon. On a blind test, original and transcoded are indistinguishable! On the frame-by-frame test, only very few frames show "significant" changes but none of these make any difference during the live show. I have one word for you : Congratulations! And.. thank you :smiley:

**Comment by donmelton** [comment]
@MelkorLord You are very welcome, sir, and thank you for the appreciation. :)
