### ISSUE TITLE
Transcoding videos shot with iPhone

### ISSUE THREAD

**Issue by mauro3** [donmelton/video_transcoding#148]
I'm trying to transcode videos shot with a recent iPhone.  Presumably, this is not the "target" of this package, but it seems to work fine and cuts size by about 2/3.  However, I've run into two problems so far:
1) the orientation of the video in portrait format is not preserved.
2) slow-motion videos become normal motion

Are there any command-line options I can set to make this work?

Related links:
- for (1) [1](https://apple.stackexchange.com/questions/155052/why-does-handbrake-rotate-my-original-videos), [2](https://superuser.com/questions/418985/can-handbrake-flip-rotate-a-video)
- for (2) I only found slo-mo videos of cars doing handbrake turns...

A few more details (let me know if more details are needed):
1) the program `mediainfo` (on linux) returns for the original:
```
...
Width                                    : 1 280 pixels     
Height                                   : 720 pixels
Display aspect ratio                     : 16:9    
Rotation                                 : 90°
...
```
whereas the transcoded is missing the `Rotation` field.

2) `mediainfo` output of original show high frame rate:
```
...
Frame rate mode                          : Variable
Frame rate                               : 239.975 FPS
Minimum frame rate                       : 218.182 FPS
Maximum frame rate                       : 240.000 FPS
...
```
transcoded shows:
```
...
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
...
```

(Thanks @donmelton for the package! Makes me transcode with aplomb.)

**Comment by donmelton** [comment]
@mauro3 You are very welcome! "With aplomb" is a delightful description. Thank you. :)

Yes, `transcode-video` can rotate your video by using the `rotate` filter in `HandBakeCLI`. Try adding something like this to your command line:

```
--filter rotate=angle=90
```

As for the slow motion issue, have you tried adding something like this yet?

```
--force-rate 240
```

I'm not sure if that will work, but it's worth a shot. Let me know.

**Comment by mauro3** [comment]
Thanks for the speedy reply! Those tricks work both.

Now, getting greedy, is there a way to make this automatic?  I can do this in the python script I use to run `video-transcode` with a bit of effort.  But presumably some input-file info is parsed already in `video-transcode`.  Maybe you can point me to the source lines?

**Comment by donmelton** [comment]
@mauro3 Sorry I took so long to reply this time. I've been in the car driving all day. :)

I'm not sure what you want to automate with `transcode-video`. It can easily process multiple files as long as you pass those files the same options. But you might be better off modifying my example shell script here for batch processing:

https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video

This is essentially what I do. But I have a much more complex version of that script which parameterizes all sorts of options and stores the values in simple text files.

Is that what you meant by automation?

**Comment by mauro3** [comment]
No worries about the response time: unless I pay consulting fees I don't expect anything!

Anyway, I meant that it automatically detects rotation and/or slow motion and sets the flags accordingly.  I plan to transcode many videos, so, I'd rather not figure that out by hand for each video.  I just discovered `ffprobe`, so it should be easy for me to put things together.  I'll close this issue but might be back with more questions.  Thanks for your help!

**Comment by donmelton** [comment]
@mauro3 You are very welcome! And I'll be here if you have more questions. :)
