### ISSUE TITLE
How to use comb-detect?

### ISSUE THREAD

**Issue by gingerbeardman** [donmelton/video_transcoding#154]
Saw a reference in readme.

Will have a look at source now.

edit: am using `--filter decomb`

**Comment by donmelton** [comment]
@gingerbeardman I think the filter is called "comb-detect" so that would be:

```
transcode-video --filter comb-detect "/path/to/Movie.mkv"
```

But, honestly, I haven't trie it recently. :)

**Comment by gingerbeardman** [comment]
Thanks, decomb was more what I wanted - cheers!
