### ISSUE TITLE
Multi Language Transcoding

### ISSUE THREAD

**Issue by HenningJohannsen** [donmelton/video_transcoding#156]
Hi Don
First of all thanks thanks for sharing video_transcoding. 
I am trying to transcode a movie with multiple audio tracks in different languages, English and Norwegian, with the default settings in video_trancoding because it plays well with plex and my apple enviroment. Is there an easy way to use those defaults in a multi language scenario? 

I allready tried with transcode-video --add-audio nor,eng "/path/to/Movie.mkv" but the output was not what i expected.  

i was hoping for something like:
 + audio tracks:
    + 1, Norwegian (AC3) (5.1 ch) (iso639-2: nor), 48000Hz, 640000bps
    + 2, Norwegian (AAC) (2.0 ch) (iso639-2: nor)
    + 3, English (AC3) (5.1 ch) (iso639-2: eng), 48000Hz, 640000bps
    + 4, English (AAC) (2.0 ch) (iso639-2: eng)

Is it possible that you could help me with an easy fix or to reproduce the defaults for multiple audio tracks? 
Thanks
Henning

**Comment by donmelton** [comment]
@HenningJohannsen You are very welcome and thanks for opening this issue.

I suspect the problem was that only one copy of the English language track was added? If that's the case, then you need to add `--audio-width all=double` to your command line like this:

```
transcode-video --add-audio nor,eng --audio-width all=double "/path/to/Movie.mkv"
```

Let me know if that works for you.

**Comment by HenningJohannsen** [comment]
Hi again
Thanks for helping me out.
It turns out that i had 2 English tracks. Is i possible to choose a language track only once or not encode dts/ac3 tracks? 
 + audio tracks:
    + 1, English (AC3) (5.1 ch) (iso639-2: eng), 48000Hz, 640000bps
    + 2, English (AAC) (2.0 ch) (iso639-2: eng)
    + 3, English (AC3) (5.1 ch) (iso639-2: eng), 48000Hz, 640000bps
    + 4, English (AAC) (2.0 ch) (iso639-2: eng)
    + 5, Norwegian (AC3) (5.1 ch) (iso639-2: nor), 48000Hz, 640000bps
    + 6, Norwegian (AAC) (2.0 ch) (iso639-2: nor)

**Comment by donmelton** [comment]
@HenningJohannsen Unfortunately, neither of those two strategies are possible with the current set of options available in `transcode-video` or `HandBrakeCLI` itself. You will have to select the tracks you want to include by specific track numbers.

**Comment by donmelton** [comment]
@HenningJohannsen Since you've solved the original issue, I'm going to close this now. But feel free to continue commenting.
