### ISSUE TITLE
Subtitle Settings - Getting It Just Right

### ISSUE THREAD

**Issue by nickrupert7** [donmelton/video_transcoding#157]
I want to go ahead and say this isn't an issue or bug with the script, just an issue with my ability to use it correctly. I'm working on a script to completely automate my movie copying process, and after MakeMKV rips the DVD/BluRay to my computer, I want to use `transcode-video` to compress the files down, and the part I'm struggling with - copy full English and English foreign audio subtitle files (English subtitles for moments of foreign audio). Specifically, I do NOT want to burn those foreign audio subtitles into the video because if I choose to play the full English subtitles, they draw on top of the burned-in text which is nasty. What I want is to copy both the full English subtitles and the foreign audio subtitles, and correctly set the "forced" flag on the foreign audio subtitles. I've played around with the settings a lot, and the closest I've gotten is by using `--add-subtitle eng`, which correctly copies both full and foreign audio English subtitles, but (as expected) it does not set the "forced" flag on the foreign audio subtitles.

Can anybody clue me in to the correct settings to get the results I'm looking for? I should go ahead and say that I prefer the image-based subtitles that come with the MKV rips - no process of converting them to text based, and no downloading them online. I'm not interested in alternate solutions unless what I'm looking for simply isn't possible with `transcode-video` - all I want is the correct settings to copy the full English subtitles, and copy and set the "forced" flag on the foreign audio English subtitles.

Thanks in advance!

**Comment by donmelton** [comment]
@nickrupert7 You need to use the `--force-subtitle` option to do that. And you'll need to pass it a specific track number like this:

```
transcode-video --add-subtitle eng --force-subtitle 1 "/path/to/Movie.mkv"
```

Just change `1` to whatever the track number is that should be forced.

Let me know if that works for you.

**Comment by nickrupert7** [comment]
I think that did it! Im still working on a way to get the number right automatically though, so I don't have to manually check and enter it every time. I don't suppose there's a feature built in that does this? If not, I should be able to write a little script that does something to that effect.

Thanks!

**Comment by donmelton** [comment]
@nickrupert7 I'm glad that worked. :)

Unfortunately, there's no built-in feature to do this. However, you can write a script to parse the output of using the `--scan` option in `HandBrakeCLI` or `transcode-video` to enumerate the subtitles in your movie. You could also use the command line version of the MediaInfo tool to do something similar. See <https://mediaarea.net/en/MediaInfo> for more information.

I'll close this now but feel free to keep commenting here.
