### ISSUE TITLE
transcode-video scanning media title fails

### ISSUE THREAD

**Issue by chrisridd** [donmelton/video_transcoding#159]
I have "District 9.dvdmedia", a DVD rip.

I run `transcode-video --scan`. Output is in [scan.txt](https://github.com/donmelton/video_transcoding/files/1220654/scan.txt); it claims that title 1 is the main feature.

I run `detect-crop --title 1`. Output is in [crop.txt](https://github.com/donmelton/video_transcoding/files/1220655/crop.txt).

I then run `transcode-video --title 1` with the crop arguments, to generate the mp4/mkv. Output is in [transcode.txt](https://github.com/donmelton/video_transcoding/files/1220656/transcode.txt). Note that it fails to find title 1, and writes to stderr:

`/usr/local/bin/transcode-video: scanning media title 1 failed
`

[District 9.mkv.txt](https://github.com/donmelton/video_transcoding/files/1220659/District.9.mkv.txt)

**Comment by donmelton** [comment]
@chrisridd Thanks for the detailed information included with this issue! That makes it easy to diagnose.

It looks like `HandBrakeCLI` thinks your input is encrypted media. See these lines in `transcode.txt`:

```
libdvdnav: DVD disk reports itself with Region mask 0x00e50000. Regions: 2 4 5
libdvdread: Encrypted DVD support unavailable.
```

I'm sorry, but there's not much I can do about that. How did you create the input?

**Comment by chrisridd** [comment]
That's very strange! I rip using RipIt.app, so maybe something went wrong there.

I will re-rip it and see what happens.

**Comment by donmelton** [comment]
@chrisridd Yeah, I thought that was output from RipIt.app. Good software. I have it, too. :) However, I believe it's not always able to decrypt a DVD if that DVD region doesn't match your drive region. A better option for you might be MakeMKV. I don't think it has that problem.

**Comment by chrisridd** [comment]
I tried re-ripping with RipIt, which completed successfully but ended up with a still-encrypted file. Shame that RipIt has been abandoned... MakeMKV made quite a fuss, but did give me a valid mkv file!

I hadn't really thought about using MakeMKV for DVDs before. Good tip!

**Comment by donmelton** [comment]
@chrisridd Yes, it's a pity RipIt hasn't been updated in a long time. Anyway, I'm glad MakeMKV worked for you! I'll close this issue now but feel free to comment here or open other issues if you run into more problems.
