### ISSUE TITLE
--crop detect returns "/usr/local/bin/transcode-video: mplayer version unknown"

### ISSUE THREAD

**Issue by DaveHamilton** [donmelton/video_transcoding#16]
When using the --crop detect parameter, conversion refuses to start and returns the error "/usr/local/bin/transcode-video: mplayer version unknown"

I am fully up-to-date on OS X, 'brew update/upgrade', as well as having both the old transcode-video.sh script still installed (but am using the new ruby gem), in case that helps diagnose.

**Comment by donmelton** [comment]
@DaveHamilton Thanks. Please reply with the output of this command so I can begin diagnosis:

```
mplayer -version
```

It should look like this:

```
Unknown option on the command line: -version
Error parsing option on the command line: -version
MPlayer 1.1-4.2.1 (C) 2000-2012 MPlayer Team
```

If your output doesn't look like that, it's likely you have a corrupted Homebrew installation or the wrong version of MPlayer is accessible in your `$PATH`. Also, please reply with the output of this command:

```
which mplayer
```

That should be:

```
/usr/local/bin/mplayer
```

If it's not, that could be your problem.

**Comment by DaveHamilton** [comment]
@donmelton Thanks. mplayer -version returned:

> iMacOffice:~ dave$ mplayer -version
> dyld: Library not loaded: /usr/local/lib/libx264.142.dylib
>  Referenced from: /usr/local/bin/mplayer
>  Reason: image not found
> Trace/BPT trap: 5

The next line, of course, was typed by me:

> iMacOffice:~ dave$ brew reinstall mplayer

And now it works fine. ;) Sorry about the false alarm. Figured when I replicated this issue on two iMacs it was certainly not a configuration concern. ;)

**Comment by donmelton** [comment]
@DaveHamilton No problem! This same thing has happened to me before with MPlayer, FFmpeg, MPV and countless other Homebrew media packages due to the same libx264 dependency problem. :)

Closing for now. Please keep error reports like this coming because they make excellent documentation!

**Comment by Crash1** [comment]
I'm seeing this error with Ubuntu 16.04 Server.
`mplayer -version returns:  MPlayer**2** 2.0 2.0-728- ......`

Editing mplayer.rb fixes the issue.

**Comment by donmelton** [comment]
@Crash1 That's not the real MPlayer then. That's MPlayer2, a fork which has been discontinued and is no longer supported. You need to download or build your own version of MPlayer for Ubuntu Server.

Try the Linuxbrew fork of Homebrew to find a MPlayer package:

http://linuxbrew.sh
