### ISSUE TITLE
makemkv no longer works and website down

### ISSUE THREAD

**Issue by dorgan** [donmelton/video_transcoding#162]
Is there something other than makemkv that can be used since it seems that makemkv  application is died to the website working...

**Comment by donmelton** [comment]
@dorgan Sorry I took so long to respond...

Yikes! Unfortunately, MakeMKV is the only game in town for ripping Blu-ray Discs at the moment. Let me check with some other folks to find out what's really going on. This has happened before so hopefully it's only a temporary situation.

**Comment by samhutchins** [comment]
It seems to be back!

I'm gonna start keeping an archive of the installers somewhere...

**Comment by donmelton** [comment]
@samhutchins Yep, it's back and... good idea!

**Comment by donmelton** [comment]
@dorgan Since the site is back online, are you able to use the MakeMKV application again?

**Comment by dorgan** [comment]
@donmelton - yes, but only after following this:  http://www.makemkv.com/forum2/viewtopic.php?f=1&t=16556

**Comment by donmelton** [comment]
@dorgan Ah, the Beta key. Yes, that would be required. :)

**Comment by majormoses** [comment]
![image](https://user-images.githubusercontent.com/3145127/31305350-9b5b3896-aaec-11e7-84d0-21757f2fdba1.png)

**Comment by donmelton** [comment]
@majormoses Ugh. It looks like Mike at MakeMKV is having problems with his ISP again. :( Thanks for the heads up. Hopefully the site will be back online soon.

**Comment by majormoses** [comment]
If you know him please let him know I would be willing to discuss sponsoring some new hosting. He can reach out to `me@benabrams.it`.

**Comment by donmelton** [comment]
@majormoses That's very generous of you! Unfortunately, I don't know Mike personally. In fact, I suspect "Mike" is not his real name. But if I do find out how to contact him, I'll pass your information along.

**Comment by dorgan** [comment]
A simple Digital Ocean node should work for him and be cheap.

**Comment by majormoses** [comment]
Yup, depending on what he needs (is doing) even that might even be overkill.

**Comment by samhutchins** [comment]
I would guess the issue is legal more than anything, I suspect the site would have problems with any hosting provider. I'm sure his hosts get a lot of pressure from Hollywood

**Comment by donmelton** [comment]
@samhutchins Agreed.

**Comment by klogg416** [comment]
@majormoses I am super late to this party, but I did grab the beta key for the month of November before the site went down. It's only a month, but may hold you over until they are back up.

MakeMKV key good to the end of November:
T-rTYSOM9ktvR0Fihn9_2zbORtGKYXUsMtMoraj2fy_wXlDPrx6EX6Xk56opCsOK9bJl

**Comment by samhutchins** [comment]
Site’s back up now too

**Comment by donmelton** [comment]
@samhutchins Good advice!
