### ISSUE TITLE
Commas in chapter names truncate the name

### ISSUE THREAD

**Issue by chrisridd** [donmelton/video_transcoding#165]
I used `transcode-video --mp4 --chapter-names filename.csv` where my filename.csv contained these lines (amongst the others)

```
10,Nice work (Mustang Sally, She’s a Lady)
33,End Credits (She’s a Lady, Bullets)
```

[Miss Congeniality - don't judge.]

Anyway it looks like the commas caused problems, because the .mp4.log shows:

```
            {
                "Name": "Nice work (Mustang Sally"
            },
            {
                "Name": "End Credits (She’s a Lady"
            }
```

Subler.app confirms these truncated names were indeed written into the mp4 file.

**Comment by martinpickett** [comment]
This behaviour comes from Handbrake rather than Don's script. You need to escape the commas in the chapter title. It's poorly documented in Handbrake but `\,` works for me. So

`10,Nice Work (Mustang Sally, She's a Lady)`

Becomes

`10,Nice Work (Mustang Sally\, She's a Lady)`

**Comment by donmelton** [comment]
@chrisridd Sorry I didn't respond sooner. I was out walking the dog.

Doh! I was just typing to ask you that very question. :)

OK, this is really good to remember! I forgot all about the escaping issue.

**Comment by donmelton** [comment]
Dammit, I put emojis on my own comment by accident. :)

**Comment by donmelton** [comment]
@chrisridd Are you OK with closing this now?

**Comment by donmelton** [comment]
@martinpickett And, BTW, thanks for figuring that out!

**Comment by chrisridd** [comment]
One day I'll find a real bug :-)

Thanks @martinpickett for the backslash trick, yep we're good to close this one.
