### ISSUE TITLE
Batch processing Video Transcoding Gem not working on two Macs with new project.

### ISSUE THREAD

**Issue by quasimog** [donmelton/video_transcoding#169]
[queue.txt](https://github.com/donmelton/video_transcoding/files/1339413/queue.txt)
I have been batch processing video files with the VTG for a couple years. For some reason today I can not get it to work on either computer, one on 10.12.6 and the other on the 10.13 Beta. Both have worked as early as last week.

Workflow

1. cd into destination folder
2. use find /path/to/my/movies -name \*.MOV >queue.txt to make a file with list of files to be processed.
3. run batch-encode.sh from destination folder

_#!/bin/bash

readonly queue="$(cd "$(dirname "$0")" && pwd)/queue.txt"

input="$(sed -n 1p "$queue")"

while [ "$input" ]; do
    sed -i '' 1d "$queue" || exit 1
    transcode-video.sh "$input"
    input="$(sed -n 1p "$queue")"
done_

But today it just seems to be doing nothing, not wiping the queue or anything.

Here is a quick video: https://vimeo.com/235854074

**Comment by quasimog** [comment]
Update: Seems to be working now, must be the way I deleted the previous entries after only half a batch was completed.  The empty line at the top of the queue.txt must have been stopping the process for some reason.

**Comment by donmelton** [comment]
@quasimog Well, it's a good thing I got distracted by unexpected visitors an hour ago so you could solve this yourself. :) Seriously, my apologies for being unable to respond right away.

Yes, any blank line in the `queue.txt` file will stop batch processing. That's actually a feature, allowing you to control the looping behavior without changing the executing script.

I'm going to assume we can close this now?

**Comment by quasimog** [comment]
Yes thank you very much!

**Comment by donmelton** [comment]
@quasimog You are very welcome, sir.
