### ISSUE TITLE
Transcoding Plex DVR raw files barely reduces the file size.

### ISSUE THREAD

**Issue by Unkas** [donmelton/video_transcoding#170]
Hi Don,

I've been using your tool to try and reduce the file sizes of the result of DVRing show using Plex, but the size only gets reduced by a couple hundred MB.  They are originally ~3.1 GB and only go down to ~2.8 GB.  Is there any way to decrease the size further with your tool?  Let me know if I can provide you with any more information.  

Thanks.

**Comment by donmelton** [comment]
@Unkas Yes, you can apply more compression and even lower resolution to reduce output size. But the risk in doing so is, as always, quality loss. Of course, your mileage may vary.

You should first try adding the `--target small` option and argument. This lowers the target bitrate significantly.

It that's not sufficient and your original is 1080p, then you can also add the `--720p` option to fit the output video within 1280x720 pixel bounds.

I hope that helps.

**Comment by Unkas** [comment]
I've been running it for a couple weeks now and it works quite well thanks!

**Comment by donmelton** [comment]
@Unkas Good to know! And thanks for the update. :)
