### ISSUE TITLE
convert to --480p

### ISSUE THREAD

**Issue by senkron24** [donmelton/video_transcoding#175]
hi 
i try to convert my videos to 480p bud i get error
my string like this 
transcode-video --480p "/home/vip2/transc/"*.avi  -o "/home/vip2/Finish/"
and get this 
/usr/local/bin/transcode-video: invalid bitrate argument: --480p

bud if i make it with --720p its works also how to work with 480p 

thx for you help in advence 

kind regrats

ps : normaly i do this on my old script
-e x264 -q 22 -r 24 -B 64 -X 720 -O -s "1,2,3,4,5,6"--verbose=1
bud on my old convert i get lower size as now with this script i think i do samthing wrong :)

**Comment by senkron24** [comment]
yes big thanks thad i have soruch perfeckt help +

**Comment by donmelton** [comment]
@samhutchins Thanks, Sam! You are correct, as usual. :)

senkron24 I'll close this now since it seems you have your answer.
