### ISSUE TITLE
Deinterlacing not working with Anime

### ISSUE THREAD

**Issue by asheimo** [donmelton/video_transcoding#176]
Anime that I have converted (Avatar: The Last Airbender, Inyuahsa, etc.) show interlacing issues, when transferred with WinX dvd ripper using the deinterlacing option the lines di appear and the image is smoother.

**Comment by samhutchins** [comment]
I don't think `transcode-video` or Handbrake try to do any de-interlacing by default (I could be wrong though)

You may need to pass some extra args to `transcode-video` for content you know is interlaced, I think adding something like `-H decomb` might do what you want.

See https://handbrake.fr/docs/en/latest/cli/cli-guide.html for more options relating to de-interlacing

**Comment by donmelton** [comment]
@asheimo As it says int the `transcode-video --help` output, the `deinterlace` filter is applied automatically for some inputs, specifically for those at precisely `29.97` FPS and when the user has not already specified an output frame rate or the `deinterlace`, `decomb`, `detelecine` filter.

It's likely that you need to apply one of those three filters yourself to fix the problem. As @samhutchins suggests, the `decomb` filter is a good place to start.

Let us know if that works.

**Comment by asheimo** [comment]
That does appear to make a difference. I am now experimenting with using just `--filter decomb` or as your faq suggests in settings you use `--force-rate 23.976 --filter detelecine` to get the best quality. My apologies if this is a noob question/request.

**Comment by donmelton** [comment]
@asheimo I'm glad that's working for you! And don't worry about the question. We welcome them here.

I'll close this now but feel free to continue commenting here or even open another issue.
