### ISSUE TITLE
transcode to 480p or 576p ?

### ISSUE THREAD

**Issue by senkron24** [donmelton/video_transcoding#181]
hi i use this comand and working fine

transcode-video --720p "/home/vip2/transc/"*.mkv  -o "/home/vip2/Finish/"

its posible to make like this

transcode-video --480p "/home/vip2/transc/"*.mkv  -o "/home/vip2/Finish/"

or 576p 
becouse i get this 
/usr/local/bin/transcode-video: invalid option: --576p

how i can do this 

kind regarts

**Comment by donmelton** [comment]
@senkron24 While it's _possible_ to add a `--480p` option, I don't want to do this and complicate an already too large API. Worse, adding an option with that name (or a name like `--576p`) would not give a true DVD-like presentation of the video. For that you would need to also change the aspect ratio which is not a good idea. My old Bash-based `transcode-video.sh` script did have a `--480p` option and this wrong impression was a constant support problem.

But it's easy to get similar behavior by using `--max-height 480` or `--max-height 480 --max-width 854` if you want to be really thorough.

I hope that helps.

**Comment by senkron24** [comment]
big thx for the support i will try 

Kind regarts

**Comment by donmelton** [comment]
@senkron24 You are very welcome! Thanks for using my software.
