### ISSUE TITLE
Subtitles are squished vertically after cropping a video during transcoding

### ISSUE THREAD

**Issue by hisaac** [donmelton/video_transcoding#186]
When I transcode a video with subtitles, and there is vertical cropping done, the subtitles get squished vertically. Here's some screenshots to show what I mean:

### Before cropping

<img width="2032" alt="screen shot 2018-01-10 at 8 14 31 pm" src="https://user-images.githubusercontent.com/923876/34805325-179618d0-f643-11e7-9ed1-ca58901df756.png">

### After cropping

<img width="2032" alt="screen shot 2018-01-10 at 8 15 08 pm" src="https://user-images.githubusercontent.com/923876/34805326-1b7f1f82-f643-11e7-96b6-3eee4ea3ec76.png">

See how the letters are squished? Is there any way around this?

**Comment by donmelton** [comment]
@hisaac Sorry I took so long to respond. I was out at dinner.

Is this particular subtitle one that you burned into the video or a Blu-ray/DVD image-based subtitle that you added as a separate track?

**Comment by hisaac** [comment]
No problem on the delay Don, You responded quicker than I expected. 👍

This is a Blu-Ray subtitle that I added as a separate track.

**Comment by donmelton** [comment]
@hisaac OK, then the answer is simple and it's also why I tell users it's better not to add Blur-ray or DVD image-base subtitles to their videos.

So here's what's happening. You definitely cropped the video. But unfortunately, there's no way to crop the subtitle that you added. Which means it still has its original `1920 x 1080` pixel bounding box. So your media player (which I assume here is VLC) is just scaling it (albeit unnecessarily) to fit the new bounding box of your video.

The only way around this is to 1) Try another media player or 2) Convert the image-based subtitle to text.

Sorry about that.

**Comment by hisaac** [comment]
Ah, ok, that makes sense. I assumed the subtitles were text and not images. And I'm just now seeing the section in your readme where you talk about this. Sorry I didn't see it before reaching out.

Thanks for the help, and thanks for the great tools!

**Comment by donmelton** [comment]
@hisaac You are very welcome, sir! I'm just sorry to be the bearer of bad news.

I'll close this now but feel free to open an issue when you have a question and it's too long for Twitter.
