### ISSUE TITLE
track specification for burned-in subtitles

### ISSUE THREAD

**Issue by djsecrist** [donmelton/video_transcoding#190]
How should I be specifying the command to burn in the English subtitles for transcoding the following?  I have tried several different things and none of them have resulted in an mp4 with the English subtitles burned-in.

General
Unique ID                                : 231262747574409604396682094247823836076 (0xADFB95C653C05A07A21EC4461A1083AC)
Complete name                            : /home/dsecrist/plex/media/Movies/Hunt for Red October, The (1990)/The Hunt for Red October.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 12.7 GiB
Duration                                 : 2h 15mn
Overall bit rate                         : 13.5 Mbps
Encoded date                             : UTC 2015-10-08 15:44:01
Writing application                      : mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
Writing library                          : libebml v1.3.1 + libmatroska v1.4.2

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 2h 15mn
Bit rate                                 : 11.5 Mbps
Width                                    : 1 920 pixels
Height                                   : 818 pixels
Display aspect ratio                     : 2.35:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.307
Stream size                              : 10.9 GiB (85%)
Writing library                          : x264 core 142 r2389 956c8d8
Encoding settings                        : cabac=1 / ref=5 / deblock=1:-2:-1 / analyse=0x3:0x113 / me=umh / subme=11 / psy=1 / psy_rd=1.00:0.05 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-3 / threads=12 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=12 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=0 / bitrate=11544 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=40000 / vbv_bufsize=40000 / nal_hrd=none / filler=0 / ip_ratio=1.40 / pb_ratio=1.30 / aq=1:0.70 / zones=189880,193052,q=31,deblock=1:2
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Mode                                     : 16
Format settings, Endianness              : Big
Codec ID                                 : A_DTS
Duration                                 : 2h 15mn
Bit rate mode                            : Constant
Bit rate                                 : 1 510 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Frame rate                               : 93.750 fps (512 spf)
Bit depth                                : 24 bits
Compression mode                         : Lossy
Stream size                              : 1.43 GiB (11%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 2h 15mn
Bit rate mode                            : Constant
Bit rate                                 : 448 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Stream size                              : 433 MiB (3%)
Language                                 : English
Default                                  : No
Forced                                   : No

Text #1
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2h 10mn
Bit rate                                 : 39 bps
Count of elements                        : 1071
Stream size                              : 38.3 KiB (0%)
Language                                 : Dutch
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 5
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 2h 4mn
Bit rate                                 : 0 bps
Count of elements                        : 26
Stream size                              : 715 Bytes (0%)
Title                                    : non-English
Language                                 : English
Default                                  : No
Forced                                   : No

**Comment by donmelton** [comment]
@djsecrist Sorry I took so long to respond.

Your English subtitles are the second track so adding `--burn-subtitle 2` to your command line take care of that. Have you tried that already?

Keep in mind that this track only contains the forced subtitles. You can tell because MediaInfo is reporting `Count of elements : 26`. That means there are only 26 subtitles in that track. And most of those are when Sean Connery and Sam Neill are speaking actual Russian at the beginning of the movie instead of just using cheesy accents like they do the rest of the time.

Because this English subtitle is already in text format, meaning it's not a Blu-ray image format, you don't really have to burn it in. Instead you could just include it directly and set the forced flag by adding `--force-subtitle 2` to your command line.

**Comment by djsecrist** [comment]
Thanks for the reply, Don.  I'm pretty sure that "--burn-subtitle 2" was the first thing I tried, but I will try it again right now.  I'm trying to eliminate all chance of Plex needing to transcode on the server side.  So, I think burn is the option I want instead of force.  Not all of the Plex clients can utilize the embedded subs, and it's just easier on both the server and my family to not have to ensure the subtitles are enabled.  Plex doesn't respect the "forced" flag very well (if at all) either.

Also, did Sean Connery even attempt a cheesy Russian accent?  :)  I think he was just being him...

**Comment by donmelton** [comment]
@djsecrist Well, maybe it was a Scottish/Russian accent then. :)

If the `--burn-subtitle 2` option and argument fails, send me your `.log` file and I'll examine it for clues. But good luck and let me know!

**Comment by djsecrist** [comment]
I get an error in the log about adding an unknown subtitle type.
add_ffmpeg_subtitle: unknown subtitle stream type: 0x53526970

Here is the full output before the encode:
```
Input #0, matroska,webm, from '/home/dsecrist/plex/media/Movies/Hunt for Red October, The (1990)/The Hunt for Red October.mkv':
  Metadata:
    encoder         : libebml v1.3.1 + libmatroska v1.4.2
    creation_time   : 2015-10-08 15:44:01
  Duration: 02:15:08.13, start: 0.000000, bitrate: 13496 kb/s
    Chapter #0:0: start 0.000000, end 792.959000
    Metadata:
      title           : 00:00:00.000
    Chapter #0:1: start 792.959000, end 1175.758000
    Metadata:
      title           : 00:13:12.959
    Chapter #0:2: start 1175.758000, end 2006.504000
    Metadata:
      title           : 00:19:35.758
    Chapter #0:3: start 2006.504000, end 2586.417000
    Metadata:
      title           : 00:33:26.504
    Chapter #0:4: start 2586.417000, end 3107.062000
    Metadata:
      title           : 00:43:06.417
    Chapter #0:5: start 3107.062000, end 3925.547000
    Metadata:
      title           : 00:51:47.062
    Chapter #0:6: start 3925.547000, end 4274.979000
    Metadata:
      title           : 01:05:25.547
    Chapter #0:7: start 4274.979000, end 5103.807000
    Metadata:
      title           : 01:11:14.979
    Chapter #0:8: start 5103.807000, end 5811.931000
    Metadata:
      title           : 01:25:03.807
    Chapter #0:9: start 5811.931000, end 6471.757000
    Metadata:
      title           : 01:36:51.931
    Chapter #0:10: start 6471.757000, end 6918.745000
    Metadata:
      title           : 01:47:51.757
    Chapter #0:11: start 6918.745000, end 7679.714000
    Metadata:
      title           : 01:55:18.745
    Chapter #0:12: start 7679.714000, end 8108.128000
    Metadata:
      title           : 02:07:59.714
    Stream #0:0: Video: h264 (High), yuv420p, 1920x818, SAR 1:1 DAR 960:409, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 11535490
      BPS-eng         : 11535490
      DURATION        : 02:15:08.100000000
      DURATION-eng    : 02:15:08.100000000
      NUMBER_OF_FRAMES: 194400
      NUMBER_OF_FRAMES-eng: 194400
      NUMBER_OF_BYTES : 11691364085
      NUMBER_OF_BYTES-eng: 11691364085
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-10-08 15:44:01
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-10-08 15:44:01
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)
    Metadata:
      BPS             : 1509750
      BPS-eng         : 1509750
      DURATION        : 02:15:08.096000000
      DURATION-eng    : 02:15:08.096000000
      NUMBER_OF_FRAMES: 760134
      NUMBER_OF_FRAMES-eng: 760134
      NUMBER_OF_BYTES : 1530149742
      NUMBER_OF_BYTES-eng: 1530149742
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-10-08 15:44:01
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-10-08 15:44:01
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Metadata:
      BPS             : 448000
      BPS-eng         : 448000
      DURATION        : 02:15:08.128000000
      DURATION-eng    : 02:15:08.128000000
      NUMBER_OF_FRAMES: 253379
      NUMBER_OF_FRAMES-eng: 253379
      NUMBER_OF_BYTES : 454055168
      NUMBER_OF_BYTES-eng: 454055168
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-10-08 15:44:01
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-10-08 15:44:01
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(dut): Subtitle: subrip (default)
    Metadata:
      BPS             : 39
      BPS-eng         : 39
      DURATION        : 02:10:57.932000000
      DURATION-eng    : 02:10:57.932000000
      NUMBER_OF_FRAMES: 1071
      NUMBER_OF_FRAMES-eng: 1071
      NUMBER_OF_BYTES : 39187
      NUMBER_OF_BYTES-eng: 39187
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-10-08 15:44:01
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-10-08 15:44:01
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(eng): Subtitle: subrip
    Metadata:
      title           : non-English
      BPS             : 0
      BPS-eng         : 0
      DURATION        : 02:04:00.724000000
      DURATION-eng    : 02:04:00.724000000
      NUMBER_OF_FRAMES: 26
      NUMBER_OF_FRAMES-eng: 26
      NUMBER_OF_BYTES : 715
      NUMBER_OF_BYTES-eng: 715
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-10-08 15:44:01
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-10-08 15:44:01
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[09:19:12] add_ffmpeg_subtitle: unknown subtitle stream type: 0x53526970
[09:19:12] add_ffmpeg_subtitle: unknown subtitle stream type: 0x53526970
[09:19:12] scan: decoding previews for title 1
Scanning title 1 of 1, preview 1, 0.00 %[09:19:14] scan: audio 0x2: ac3, rate=48000Hz, bitrate=448000 English (AC3) (5.1 ch)
[09:19:14] scan: audio 0x1: dca, rate=48000Hz, bitrate=1536000 English (DTS) (5.1 ch)
```

**Comment by donmelton** [comment]
@djsecrist Ugh. HandBrake used to handle SubRip-format subtitles itself before handing them off to LibAV (FFmpeg). Are you using a nightly build? This shouldn't be a problem with the release version of HandBrake.

Anyway, you'll have to extract the subtitle, convert it to ASS (Advanced SubStation Alpha) format, remux the file, and then attempt transcoding it again.

Here's a Web page which explains how to do the conversion with FFmpeg:

https://trac.ffmpeg.org/wiki/HowToConvertSubtitleToASS

It's very simple. The hard part will be extraction and remuxing. For that you'll need to use `mkvextract` and `mkvmerge`.

**Comment by djsecrist** [comment]
I'll check which version I'm using.  Regardless, I think your guidance has put me on the right track.  Thank you, and thanks for such a great tool!

In a related question, do you know of an easy way to identify all of the media files where I might have this same issue?  Also, I know that I have some files where the subtitles are not properly tagged as forced (like this example) or the wrong subtitle track is forced.  Sometimes the subtitles are labeled "non-english parts" or something like that but not actually tagged as forced.  Basically, I want to end up with a list of files and subtitle tracks that will need some "special handling".  Then, I can let your tool loose on the rest of my media while I prepare the special cases.

**Comment by donmelton** [comment]
@djsecrist You are very welcome! Thanks for using it, sir!

As for identifying all your problematic media files, you'll have to write a script to do that. Sorry, there's not easy way around that. I have to do this same kind of thing myself all the time.

You'll probably have to use `mediainfo` or `ffprobe` (which is part of the FFmpeg suite of tools). The `ffprobe` tool is faster and its output easier to parse than using `mediainfo`. Here's a Web page giving some tips on how to use `ffprobe`:

https://trac.ffmpeg.org/wiki/FFprobeTips

But really, use whatever tool you're comfortable with.

Anyway, should I close this issue now?

**Comment by djsecrist** [comment]
Yes.  It can be closed.  Unless...  You want to change it into a feature request to automate the handling of these problematic subtitles...  :)

By the way, I am using "HandBrake 0.10.2 (2016021200) - Linux x86_64".  Thanks again!

**Comment by donmelton** [comment]
@djsecrist Hmmmm, that version string seems peculiar. That date should read `(2015060900)` for HandBrake 0.10.2. Maybe it's just a Linux-specific build/distribution issue?

Anyway, closing this now but feel free to keep commenting here or opening other issues.

**Comment by djsecrist** [comment]
I updated my HandBrake version and it worked without having to extract to ASS or do anything special.  I'm now on HandBrake 1.0.4.  Thanks again!

**Comment by donmelton** [comment]
@djsecrist Excellent!
