### ISSUE TITLE
UTF parsing of subtitle (SRT) files

### ISSUE THREAD

**Issue by osuritz** [donmelton/video_transcoding#192]
Here's the command line I used to encode a movie:
`transcode-video --mp4 --crop 0:0:52:52  --add-audio fra --audio-width other=double --add-srt Movie.eng.srt --add-srt Movie.fre.srt ~/Movies/Movie.mkv`

However when watching the file in QuickTime (and MPlayer), the French subtitles (in particular the accents) are showing garbled characters. However, if I open the MP4 in Subler, remove the French subtitle track, then re-add it manually and save, then the subtitles are render properly in QuickTime and MPlayer.

There must be a way to detect UTF8 format from files and set whatever sort of flag needs to be set in the container? I'm happy to link to subtitle file if necessary.

**Comment by donmelton** [comment]
@osuritz Sorry I took so long to respond. I was out walking the dog. :)

I think if you add `--bind-srt-encoding utf8` after `--add-srt Movie.fre.srt` then it should recognize all the characters because the default encoding in `HandBrakeCLI` is `latin1`.

**Comment by donmelton** [comment]
@osuritz Did my suggestion work for you?

**Comment by osuritz** [comment]
Yup that worked. Thanks! :)

**Comment by donmelton** [comment]
@osuritz No problem. I'm glad it worked. I'll close this then.
