### ISSUE TITLE
Invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by dorgan** [donmelton/video_transcoding#193]
`--crop detect` and detect-crop tool failing with error `Invalid byte sequence in US-ASCII`

**Comment by donmelton** [comment]
@dorgan OK, I'm back from dinner. :)

Thanks for filing this! Can you add more information about the problem media file? Like results from `--scan` or output from MediaInfo? Also, does this happen with every media file or only one?

Also, which version of `ffmpeg` are you using?

**Comment by dorgan** [comment]
output from `detect-crop --scan` is:

`+ title 1:
  + stream: shrek.mkv
  + duration: 01:30:08
  + size: 1920x1080, pixel aspect: 1/1, display aspect: 1.78, 23.976 fps
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 00:04:59
    + 2: cells 0->0, 0 blocks, duration 00:06:46
    + 3: cells 0->0, 0 blocks, duration 00:04:16
    + 4: cells 0->0, 0 blocks, duration 00:04:13
    + 5: cells 0->0, 0 blocks, duration 00:06:08
    + 6: cells 0->0, 0 blocks, duration 00:05:21
    + 7: cells 0->0, 0 blocks, duration 00:03:32
    + 8: cells 0->0, 0 blocks, duration 00:05:11
    + 9: cells 0->0, 0 blocks, duration 00:04:37
    + 10: cells 0->0, 0 blocks, duration 00:04:15
    + 11: cells 0->0, 0 blocks, duration 00:06:11
    + 12: cells 0->0, 0 blocks, duration 00:05:27
    + 13: cells 0->0, 0 blocks, duration 00:04:39
    + 14: cells 0->0, 0 blocks, duration 00:03:42
    + 15: cells 0->0, 0 blocks, duration 00:02:18
    + 16: cells 0->0, 0 blocks, duration 00:03:19
    + 17: cells 0->0, 0 blocks, duration 00:02:42
    + 18: cells 0->0, 0 blocks, duration 00:03:19
    + 19: cells 0->0, 0 blocks, duration 00:02:09
    + 20: cells 0->0, 0 blocks, duration 00:07:04
  + audio tracks:
    + 1,  (AC3) (5.1 ch) (iso639-2: rus), 48000Hz, 640000bps
    + 2,  (DTS) (5.1 ch) (iso639-2: rus), 48000Hz, 768000bps
    + 3,  (DTS-HD MA) (5.1 ch) (iso639-2: rus)
    + 4,  (DTS-HD MA) (5.1 ch) (iso639-2: rus)
    + 5,  (DTS-HD MA) (5.1 ch) (iso639-2: rus)
    + 6,  (DTS-HD MA) (5.1 ch) (iso639-2: rus)
    + 7,  (DTS-HD MA) (5.1 ch) (iso639-2: rus)
    + 8,  (DTS-HD MA) (5.1 ch) (iso639-2: rus)
    + 9, English (DTS-HD MA) (5.1 ch) (iso639-2: eng)
  + subtitle tracks:
    + 1, Russian (iso639-2: rus) (Text)(SSA)
    + 2, Russian (iso639-2: rus) (Text)(SSA)
    + 3, Russian (iso639-2: rus) (Text)(SSA)
    + 4, Russian (iso639-2: rus) (Text)(SSA)
    + 5, Russian (iso639-2: rus) (Text)(SSA)
    + 6, Russian (iso639-2: rus) (Text)(SSA)
    + 7, English (iso639-2: eng) (Text)(SSA)
    + 8, Russian (iso639-2: rus) (Text)(SSA)`

**Comment by dorgan** [comment]
well know i know the issue.  Apparently it doesnt like the russian subtitles...

**Comment by donmelton** [comment]
@dorgan Maybe it's not the language but the SSA/ASS format?

**Comment by donmelton** [comment]
@dorgan So, did you resolve this yourself?

**Comment by dorgan** [comment]
I resolved it by deleting it...

**Comment by donmelton** [comment]
@dorgan That works! :) OK, I'll close this issue then.
