### ISSUE TITLE
Scripts fail to start on Cygwin

### ISSUE THREAD

**Issue by CallumKerrEdwards** [donmelton/video_transcoding#2]
# Scripts fail to start on Cygwin

## Description

Upon downloading the scripts, I was able to view the help and the version, to verify that I had the latest version. 
Trying to use any of the scripts further, however, resulted in the stack trace given below.

## Further details

The identical stack trace appears when using any of the scripts, with or without any parameters.
Uninstalling and reinstalling the Ruby gem results in the same error immediately.
I first noticed this after adding the 

	/home/Callum/bin
directory to the Windows system environment variable path as

	C:/cygwin/Callum/bin
but after removing them from the path the error persists.

## System information

* OS: Win7 x64 Service Pack 1
* Cygwin version: 2.0.1(0.287/5/3)
* Ruby version: ruby 2.0.0p598 (2014-11-13) [x86_64-cygwin]

## Stack trace

	$ transcode-video --help
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': /home/Callum/.gem/ruby/gems/video_transcoding-0.1.0/lib/video_transcoding/media.rb:11: syntax error, unexpected ',' (SyntaxError)
		def initialize(path:, title: nil, autocrop: false,...
							 ^
	/home/Callum/.gem/ruby/gems/video_transcoding-0.1.0/lib/video_transcoding/media.rb:11: Can't assign to nil
	...f initialize(path:, title: nil, autocrop: false, extended: t...
	...                               ^
	/home/Callum/.gem/ruby/gems/video_transcoding-0.1.0/lib/video_transcoding/media.rb:11: Can't assign to false
	...:, title: nil, autocrop: false, extended: true, allow_direct...
	...                               ^
	/home/Callum/.gem/ruby/gems/video_transcoding-0.1.0/lib/video_transcoding/media.rb:11: Can't assign to true
	...utocrop: false, extended: true, allow_directory: true)
	...                               ^
	/home/Callum/.gem/ruby/gems/video_transcoding-0.1.0/lib/video_transcoding/media.rb:323: syntax error, unexpected keyword_end, expecting end-of-input
			from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
			from /home/Callum/.gem/ruby/gems/video_transcoding-0.1.0/lib/video_transcoding.rb:15:in `<top (required)>'
			from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
			from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
			from /home/Callum/.gem/ruby/gems/video_transcoding-0.1.0/lib/video_transcoding/cli.rb:8:in `<top (required)>'
			from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
			from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
			from /home/Callum/.gem/ruby/gems/video_transcoding-0.1.0/bin/transcode-video:12:in `<top (required)>'
			from /home/Callum/bin/transcode-video:23:in `load'
			from /home/Callum/bin/transcode-video:23:in `<main>'

**Comment by donmelton** [comment]
I think Markus is correct. I'm requiring the wrong Ruby version.

**Comment by donmelton** [comment]
Callum,

Thanks for the super-detailed bug report!

I think this is the same issue that @cadonau identified in https://github.com/donmelton/video_transcoding/pull/1 with his patch.

I just checked in a fix based on his patch and re-released the Gem as version 0.1.1.

Let me know if that fixes the problem.

**Comment by CallumKerrEdwards** [comment]
No problem, creating bug reports is part my day job, so I am used to providing too much detail! It has fixed the error for me. On to a new world of transcoding!

**Comment by donmelton** [comment]
Wow! OK, you're a good man to know then.

On to the new world, indeed. Let me know if you run into any other problems.
