### ISSUE TITLE
convert-video cannot find a compatible video track

### ISSUE THREAD

**Issue by huwtheb** [donmelton/video_transcoding#203]
I've ripped a couple of DVDs using MakeMKV, now want to convert that MKV using convert-video. When I do, I get a "no compatible video track" message.

Using mkvmerge -i, it appears the video track is MPEG-1/2. Not sure if convert-video does not like that.

Is there a way to convert this type of video track?

**Comment by donmelton** [comment]
@huwtheb Sorry I took so long to respond. I was at lunch.

My `convert-video` tool is designed to convert a video file from Matroska (MKV) to MP4 format or from MP4 to Matroksa format without transcoding the video. It's mostly useful as a helper utility for my `transcode-video` tool if want to switch formats after transcoding, e.g. you forgot to use the `--mp4` option when you invoked `transcode-video`. 

A DVD rip, as you've discovered, always contains video in MPEG-2 format. This video format is not allowed in MP4 files. This is a restriction by the format and not by my or anyone else's tools.

The only video format allowed in MP4 files is MPEG-4. The H.264/AVC codec is the most widely used "flavor" of MPEG-4, and the default output format of HandBrake. So, you'll need to use my `transcode-video` tool or some other transcoding utility to convert your DVD rip into MP4 format.

Does that answer your question?

**Comment by huwtheb** [comment]
Right, got it. Thanks, Don.

**Comment by donmelton** [comment]
@huwtheb No problem! Glad that helped.

I'll close this now but feel free to comment here again or open another issue. I get the notifications either way. :)
