### ISSUE TITLE
Question - can I use this to reduce/compress video file size?

### ISSUE THREAD

**Issue by zulhfreelancer** [donmelton/video_transcoding#204]
Hi,

I have some videos in various formats i.e. MP4, MOV, AVI, WMV & etc.

I found this awesome project and it looks promising. But I'm not sure whether this tool is suitable for what I'm currently building or not.

Does it posibble to use this tool to...

- compress all the video sizes to lowest possible size
- maintain the video and audio quality
- make all of them (the output) in MP4 format (I think this one is possible)

...?

Thank you.

**Comment by donmelton** [comment]
@zulhfreelancer Yes, that's exactly what this project is designed for. :)

If the "README" or the built-in documentation via `transcode-video --help` don't answer your questions on how to do that, please feel free to ask again here.

**Comment by zulhfreelancer** [comment]
Noted. Thanks @donmelton!
