### ISSUE TITLE
audio question: why mkv audio output ordered differently than mp4? 

### ISSUE THREAD

**Issue by markmarz** [donmelton/video_transcoding#208]
Until recently I converted all MakeMkv output to .mp4 with transcode-video. Often the main audio is 5.1, which transcode-video handles by creating a stereo AAC track from it and placing that track as the first track and copying the original 5.1 audio as the second track.

But recently I've been trying .mkv output and I noticed the same conversion takes place, but the generated stereo AAC track is not made the first track, instead the original ordering is preserved. Is there anything I can do to get the same audio output ordering from .mkv transcoding as I get with .mp4?

Here's a typical example which will yield different audio ordering if I had chosen --mp4:
transcode-video --main-audio 1=Main "E:\dvd_input\Batman Forever (1995)/Batman Forever (1995).mkv" -o "E:\dvd_output\Batman Forever (1995)\Batman Forever (1995).mkv"

Thank you!
Mark M.

**Comment by donmelton** [comment]
@markmarz Yes, you can add the `--reverse-double-order` option to your `transcode-video` command line when your output format is MKV to mimic the track order of MP4 output. Here's the description of that option from the `--help` output:

```
    --reverse-double-order
                    reverse order of `double` width audio output tracks
```

Let me know if you have any other questions. Otherwise we can probably close this issue.

**Comment by markmarz** [comment]
@donmelton I'm sorry. I should have dug further, I never saw that option. Thanks Don!

**Comment by donmelton** [comment]
@markmarz No worries, sir! That `--help` output is huge. :) And you're very welcome.
