### ISSUE TITLE
Does not work on current Debian

### ISSUE THREAD

**Issue by hagabla** [donmelton/video_transcoding#215]
transcode-video "VIDEO_TS"
HandBrakeCLI: unrecognized option '--auto-anamorphic'

**Comment by donmelton** [comment]
@hagabla As near as I can tell from the information you provided, the version of `HandBrakeCLI` you have installed is older than 1.0.0, which is currently the minimum requirement for using `transcode-video`. You need to upgrade to `HandBrakeCLI`  version 1.0.0 or later. I assume that's possible on a Debian Linux distribution?

**Comment by hagabla** [comment]
https://packages.debian.org/stretch/handbrake-cli

that's what up to date stable Debian (9) ships with (0.10.5+ds1-2 ). No newer versions around on the official (or unofficial Debian) repository. There is an unofficial ubuntu repository that has uptodate packages, xenial packages seem to work, for now, but that's not really a solution.

**Comment by donmelton** [comment]
@hagabla Ugh. Being _unable_ to use up-to-date software packages is a known "feature" of Debian. Seriously, `HandBrakeCLI` version 1.0.0 is not some bleeding-edge experiment. It was released on December 24, 2016, over 18 months ago.

If you can't install a newer `HandBrakeCLI`, then my advice is to downgrade your `video_transcoding` Gem to version 0.19.0.

**Comment by hagabla** [comment]
I have used the ubuntu package and transcoded the movie successfully already,  just though that is something you should be aware of. After all Debian is one of the bigger linux Distros out there.

Did not think of downgrading video_transcoding, thanks for that.

**Comment by donmelton** [comment]
@hagabla Thanks for letting me know! My Linux testers didn't mention that when we were evaluating the change for 0.20.0. It happens. :)

I'm glad that downgrading is an option for you, too.

I'll close this now but feel free to comment further.
