### ISSUE TITLE
--audio-width problem with transcode-video on CentOS

### ISSUE THREAD

**Issue by nobitataj** [donmelton/video_transcoding#218]
Hi, recently I encountered a problem with transcoding video on CentOS 7. The input file contains audio track in Dolby format. I wanted the output to have only stereo audio AAC format, so I added --audio-width main=stereo into the command. The output is as expected when I tested in my local MacOS computer. However the output file when I run the command on CentOS still have audio track with 6 channels, when I inspect the output file with ffprobe, it comes like this:
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 6,
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": -440,
            "start_time": "-0.009167",
            "duration_ts": 20020800,
            "duration": "417.100000",
            "bit_rate": "384516",
            "max_bit_rate": "384516",
            "nb_frames": "19552",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2018-08-28T04:42:02.000000Z",
                "language": "eng",
                "handler_name": "Surround"
            }
        }
    ]
Any ideas where I could have been using it incorrectly? Thanks in advance
P.S: I use latest HandBrake version, following this guide: https://handbrake.fr/docs/en/latest/developer/install-dependencies-centos.html

**Comment by nobitataj** [comment]
Tested on Ubuntu, seems that this problem only happens on Cent

**Comment by donmelton** [comment]
@nobitataj Interesting. It seems the audio mixdown defaults are different on CentOS than any other platform.

You could try forcing the audio mixdown on CentOS by adding `--handbrake-option mixdown=dpl2` to your command line. The `dpl2` indicates that you want a stereo mix in Dolby Prologic II format.

Let me know if that works. And thanks for opening this issue!

**Comment by nobitataj** [comment]
@donmelton perfect
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 135420912,
            "duration": "2821.269000",
            "bit_rate": "158904",
            "max_bit_rate": "158904",
            "nb_frames": "132248",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2018-08-29T01:50:23.000000Z",
                "language": "eng",
                "handler_name": "Stereo"
            }
        },
        {
            "index": 2,
            "codec_name": "ac3",
            "codec_long_name": "ATSC A/52A (AC-3)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "ac-3",
            "codec_tag": "0x332d6361",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "dmix_mode": "-1",
            "ltrt_cmixlev": "-1.000000",
            "ltrt_surmixlev": "-1.000000",
            "loro_cmixlev": "-1.000000",
            "loro_surmixlev": "-1.000000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 135421152,
            "duration": "2821.274000",
            "bit_rate": "224000",
            "nb_frames": "88165",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "creation_time": "2018-08-29T01:50:23.000000Z",
                "language": "eng",
                "handler_name": "Stereo"
            },
            "side_data_list": [
                {
                    "side_data_type": "Audio Service Type"
                }
            ]
        }

Tested on Mac and Cent, let me try on Ubuntu

**Comment by nobitataj** [comment]
Ubuntu verified working, thanks a lot @donmelton

**Comment by donmelton** [comment]
@nobitataj Excellent! I'll close this now but feel free to comment here or open other useful issues like this one.
