### ISSUE TITLE
QUESTION: How to parse logs to see result of --burn-subtitle scan

### ISSUE THREAD

**Issue by kford** [donmelton/video_transcoding#220]
If I use the option `--burn-subtitle scan` I know the system tries to determine if the subtitles appear in 10% or more of the video and if so, burns it into the video.  How can I parse the logs to determine if this resulted in a burn-in or skip?

Thanks!

**Comment by donmelton** [comment]
@kford Great question! Look for a line in the `.log` file which ends with `-> Render/Burn-in`. That will also be the same for explicitly burned subtitles.

Does that work for you?

**Comment by kford** [comment]
Fantastic.. That was too easy.  I tend to process in batch so I can revisit all the processed videos and then verify individually whether the burn-in was appropriate.

`find . -iname "*.log" -print0 | xargs -0 grep -i burn-in`

Here's one example .log file that leads me to another question.  The line I used to invoke transcode-video for this particular file had the following options. `--add-subtitle 1  --burn-subtitle scan`.  Since I explicitly added subtitle track 1, what does the below indicate?
```[08:25:15]  * Foreign Audio Search: Render/Burn-in, Forced Only
[08:25:15]    + subtitle, English [PGS] (track 0, id 0x2, Picture)
[08:25:15]    + subtitle, English [PGS] (track 1, id 0x3, Picture)
[08:25:15]    + subtitle, English [PGS] (track 3, id 0x5, Picture)
[08:25:15] sync: expecting 222187 video frames```

**Comment by donmelton** [comment]
@kford Sorry about taking so long to reply. I was AFK for the evening.

Another great question! Well, from that `.log` file fragment, it doesn't look like any subtitles were burned. If I could see the whole file, I might be able to tell for sure.

**Comment by nobitataj** [comment]
Hi @donmelton , I have a question. Here is the log I extracted:

`[09:26:00] [ass] fontselect: (UTM Ong Do Gia, 700, 0) -> /usr/share/fonts/transcoder/svn-fonts/SVN-Student.ttf, 0, SVN-Student
[09:26:00] [ass] fontselect: (UTM Swiss Condensed, 700, 0) -> /usr/share/fonts/transcoder/unicode-fonts/UTM Swiss CondensedBold.ttf, 0, UTMSwissCondensed-Bold`

As you can see, my subtitle has multiple styles, which the first font style was incorrectly picked (I checked the system and the font was there), and the second font style was correctly picked. Any idea what happened? I include result of the fc-list command:
`/usr/share/fonts/transcoder/utm-fonts/UTM Ong Do Gia.ttf: UTM Ong Do Gia:style=Regular
/usr/share/fonts/transcoder/unicode-fonts/UTM Ong Do Gia.ttf: UTM Ong Do Gia:style=Regular`

One more thing, if my subtitle has a line that covers the whole video (eg: a logo), shouldn't it appear even if I transcode just a part of the video? For instance from frame 20000 to 30000?

**Comment by nobitataj** [comment]
Ah, found the answer for the latter, turns out it was because of HandBrake, I used the HandBrake GUI to encode the middle part, no subtitle found

**Comment by donmelton** [comment]
@nobitataj That would explain it, all right. :)

OK, I'll close this now but feel free to continue commenting or open another issue.

**Comment by kford** [comment]
Hey Don,

I totally forgot about this but I had meant to come back and provide the log file.  I see log entries that look like this `* Foreign Audio Search: Render/Burn-in, Forced Only` in all my files, but in select ones, like the log I attached, I also see `* subtitle track 1, English [PGS] (track 5, id 0x9, Picture) -> Render/Burn-in, Forced Only`

Can you help me understand how to interpret the logs?  If there's a guide that's cool, I can follow it.

[Some Movie.mkv.log](https://github.com/donmelton/video_transcoding/files/2555626/Some.Movie.mkv.log)

**Comment by donmelton** [comment]
@kford Were you using the same options for that movie? That is, `--burn-subtitle scan`?

**Comment by donmelton** [comment]
@kford OK, the reason you're seeing that line because that's the forced subtitle the `--burn-subtitle scan` option found. You won't see that in files where HandBrake couldn't find a forced subtitle.

**Comment by kford** [comment]
@donmelton yes, I was using the same option.. So that is when it found that the title already had a burned in subtitle?  Not when it decided that one should be burned in.  Can you tell me what I'd expect to see in the log if it finds a candidate subtitle to burn into the video while transcoding?  I thought this was part of the video_transcoding library, but if it's part of HandBrake, I might be able to find the answer myself from their docs.

**Comment by donmelton** [comment]
@kford The scanning and decision behavior is within HandBrake and, frankly, it's a bit unpredictable. That's why I don't recommend using it. Instead, the better option is to make sure the forced flag is set on any forced subtitles in your rips before you transcode them. This can be done within MakeMKV when you rip or afterwards with a tool like `mkvpropedit`.
