### ISSUE TITLE
Need assistance on audio tracking

### ISSUE THREAD

**Issue by khaosx** [donmelton/video_transcoding#228]
@donmelton OK, hopefully this is the last issue for me :)

I know I'm already violating most of the suggestions for usage, but I would like to setup the audio on my output files as follows:

Input = 1 single track from the original MKV (will be TrueHD or DTS-HD)

Output:
track 1 = Passthrough of HD Audio
track 2 = AC/3 surround decode of input
track 2 = stereo AAC

Using:

--copy-audio 1 --audio-width all=double

yields passthrough and stereo

How do I tell it to passthrough, and then do ac3 & stereo as additional tracks?

**Comment by donmelton** [comment]
@khaosx The `--copy-audio 1 --audio-width all=double` options and arguments will only copy the first main audio track and create a stereo copy of it. You need to explicitly add the other tracks, e.g. `--copy-audio 1 --add-audio all  --audio-width all=double`.

Does that fix it for you?

**Comment by khaosx** [comment]
Nope - unfortunately it looks like when you only have one audio track in the source, it copies that in once, recognizes that it's a surround track, and does the conversion to stereo (which fulfills the double width request). It won't add the track a third time.

Unless this is an easy "Oh, you need to add this to your command line" type of thing, I'll just re-rip my MKV's to have a second track that can be added and fed to the script.

**Comment by khaosx** [comment]
If I re-rip with a second input track, the following works:

    --copy-audio 1 --audio-width all=surround --add-audio 1 --prefer-ac3 --audio-width 1=double

I end up with 3 audio tracks: TrueHD, AC-3, AAC Stereo.

Starting from 1 single TrueHD track for my input, I can't get it to add a third track, even explicitly adding the input track three times. As soon as the input track is recognized as being a surround track, it won't create another surround track. So, looks like re-ripping is the way to go.

**Comment by donmelton** [comment]
@khaosx OK, now I understand what you want, essentially a triple-wide main audio track, with the original lossless audio, a transcoded surround version and finally a transcoded stereo version of that original. Right?

There's no easy way to do that without dropping into `--handbrake-option` territory. I can actually give you the commands to do it, but you probably won't like the process. :)

And I'm sorry, but I intend to keep things complicated like that. Why?

Here's the key reason from the very top of the README document:

> ...I created these tools to transcode my collection of Blu-ray Discs and DVDs into a smaller, more portable format while remaining high enough quality to be mistaken for the originals.

Smaller and more portable. Definitely not the originals.

Keeping the lossless audio with _two_ lossy copies is probably half the size of your transcoded video. Seriously, I don't think you should be transcoding your rips. You should just figure out a way to play them directly.

So, do you want to know the `--handbrake-option` trick?

**Comment by khaosx** [comment]
@donmelton I've been direct playing them for a while, but I'm finally out of drive space and She Who Must Be Obeyed will murder me in my sleep if I shell out another $1500 for a stack of 10TB Iron Wolf drives. :)

Your point is well-taken though. I'm going to do some soul searching and figure out my actual use cases. As it is, I'm targeting a 7.1 theater room, a 4k panel in the living room, AND trying to deal with Plex transcoding for remote viewing. I'm just trying to do too much.

I won't likely use the handbrake trick, as this moves well outside of the reason why I use (and you wrote) this script - keeping it simple.

Thanks for the look-see anyway. Go ahead and close this one!

**Comment by donmelton** [comment]
@khaosx Yes, I have one of those same dangerous types here. :)

OK, I'll close this and give you something else to think about with how I actually handle my audio. I don't even transcode to AC-3 any longer. After a lot of testing with my two expensive 5.1 surround systems, I've decided that a single 160 Kbps stereo audio track in Dolby Pro Logic ll format with matrix-encoded surround sounds is just fine for my needs.

Seriously, DPL II is more than good enough. Hell, it's how I get surround sound from Netflix anyway. Give it a listen and judge for yourself.
