### ISSUE TITLE
Add subtitle language with --add-srt?

### ISSUE THREAD

**Issue by vasuvasu** [donmelton/video_transcoding#231]
Is there a way to specify the language of a subtitle being added via --add-srt? I'd like to be able specify that the subtitle I'm adding is english so that it doesn't show up at unknown/undetermined/null/etc  in a media player.

**Comment by donmelton** [comment]
@vasuvasu Yes, the default is `und`, i.e. undefined, so after your `--add-srt` option and argument, add `--bind-srt-language eng` to your command line.

Does that answer your question? If so, I'll close this.

**Comment by vasuvasu** [comment]
@donmelton yes, thank you!

**Comment by donmelton** [comment]
@vasuvasu Good! I'm glad that worked. And you're very welcome.
