### ISSUE TITLE
detect-crop ruby error

### ISSUE THREAD

**Issue by platonium** [donmelton/video_transcoding#232]
Dear Don,

All of a sudden, detect-crop isn't working because of the following.  The thing is, there's no Version 2.0.  Finder shows version 2.3.  Is this an easy fix, or a good time to upgrade from Sierra to High Sierra or Mojave?  

Although off topic, if it's upgrade time, do you have a suggestion as to whether I should switch up to Mojave?  32bit isn't an issue, and I'm on a late 2013 iMac.  Thank you so much as always for sharing your fantastic work.

-bash: /usr/local/bin/detect-crop: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by donmelton** [comment]
@platonium I'm sorry you're having the problem but I don't understand the configuration of your system well enough to know what's going on. Can you please execute the following five commands and past the output here?

```
which ruby
ruby --version
which gem
gem environment
which detect-crop
```

Thanks.

Also, I haven't switched to Mojave yet so I don't know if there are issues.

**Comment by platonium** [comment]
Thank you so much.

imacs-iMac:~ plato$ which ruby
/usr/bin/ruby
imacs-iMac:~ plato$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin16]
imacs-iMac:~ plato$ which gem
/usr/bin/gem
imacs-iMac:~ plato$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2.3
  - RUBY VERSION: 2.3.7 (2018-03-28 patchlevel 456) [universal.x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/plato/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/plato/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-16
  - GEM PATHS:
     - /Library/Ruby/Gems/2.3.0
     - /Users/plato/.gem/ruby/2.3.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
imacs-iMac:~ plato$ which detect-crop
/usr/local/bin/detect-crop

**Comment by donmelton** [comment]
@platonium OK, you're using the pre-installed macOS version of `ruby` and `gem` instead of the version from Homebrew. This can be problematic sometimes which is why I never use them.

I would try to uninstall the `video_transcoding` Gem, cleanup your environment, and then reinstall it like this:

```
gem uninstall video_transcoding
gem cleanup
gem install video_transcoding
```

If that doesn't work, I would try installing the Ruby environment via Homebrew.

Let me know if that helps.

**Comment by platonium** [comment]
Dear Don,

That worked brilliantly and quickly.  Thank you again!

Best,
Plato

**Comment by donmelton** [comment]
@platonium You are very welcome, sir! I'm glad that worked.
