### ISSUE TITLE
transcode-video uses libmp3lame when outputting an mkv

### ISSUE THREAD

**Issue by samhutchins** [donmelton/video_transcoding#235]
I don't have a mac handy to test with I'm afraid, but on Windows (native windows, using CMD) the following command outputs with an mp3 stereo track:

`transcode-video title_t03.mkv -o "output.mkv"`

This command, however, outputs with an aac stereo track instead:

`transcode-video title_t03.mkv -o "output.mp4"`

I'm not sure if this is intended behaviour or not, but I doubt it is. Apologies for not noticing this before now. I used to always output to an mp4, so I always got aac, and by the time I'd switched to outputting mkv files I'd also specify to use `fdk_aac`.

I'm using HandBrakeCLI 1.1.2

MKV log:  
[output.mkv.log](https://github.com/donmelton/video_transcoding/files/2636961/output.mkv.log)

MP4 log:  
[output.mp4.log](https://github.com/donmelton/video_transcoding/files/2636962/output.mp4.log)

**Comment by donmelton** [comment]
@samhutchins Holy crap! Did they change the default audio format for Matroska output in version 1.1.2? Can you try this with version 1.1.0 or 1.1.1 as well? And can anyone else using Windows confirm this?

**Comment by donmelton** [comment]
@samhutchins BTW, this is probably due to a change I made back in June to "Modify `transcode-video` to no longer pass a named audio encoder to `HandBrakeCLI` in order to select AAC since that's the default audio format anyway." Obviously I was wrong about the default on Windows!

https://github.com/donmelton/video_transcoding/commit/477d342302764097cbd925b5081d8774864d872a

**Comment by donmelton** [comment]
@samhutchins I'll back out that change which will, no doubt, fix this bug. I'll also look at any other optimizations I may have done elsewhere which might be causing further problems. And I'll add the workaround for the new mixdown default in nightly builds which you and I have been discussing out of band.

My apologies that you ran into the situation. Thanks for catching this!

**Comment by donmelton** [comment]
@samhutchins Stupid question: Do you still have to specify `av_aac` on Windows to get the FFmpeg/Libav AAC encoder or can you use the generic `aac` name and still avoid getting the old LibFacc encoder (which I think was removed in `HandBrakeCLI` version 0.10.0)?

**Comment by donmelton** [comment]
@samhutchins Thanks! Yeah, I really screwed things up with that optimization back in June. But at least the fix can be just a single line by using the `aac` alias.

And I'm so glad Linux users aren't affected by this! Thanks for testing that, too!

I'll probably have a release with the fix later today.

**Comment by samhutchins** [comment]
I wonder why HandBrake defaults to mp3 on Windows, but not anywhere else...

**Comment by donmelton** [comment]
@samhutchins Good question! Apparently their defaults are a lot less stable and/or predictable than I thought. Ugh.

BTW, I decided to restore all the complicated code which reads the output of `HandBrakeCLI --help` to determine the actual encoder name (i.e. `ca_aac` or `av_aac`) than use the generic `aac` name because... 1) I know that worked and 2) I worry that they'll remove that in the future.

**Comment by donmelton** [comment]
@samhutchins Whew. :) And thanks for the quick testing!

I'll get this released as soon as I get that workaround for HandBrake nightly builds done that we discussed out of band.

**Comment by samhutchins** [comment]
@donmelton No problem!

Good luck with the other audio issues too. Apologies for emailing about those, I should have opened an issue here instead (which I can do if you like). For some reason it didn't trigger the "file a bug" code path in my head

**Comment by donmelton** [comment]
@samhutchins No worries. I didn't think to open an issue either. :)

The good news is that the patch for that is done. The bad news is that although I think it works, testing it thoroughly will take awhile.

**Comment by donmelton** [comment]
@samhutchins Aaaaand... In the process of testing _that_ bug fix, I found other unrelated breakage when using the HandBrake nightly builds. Dammit.

This will definitely take awhile.

**Comment by donmelton** [comment]
@samhutchins OK, I committed the mixdown workaround:

https://github.com/donmelton/video_transcoding/commit/5f2aa55226320d2f1fabd9822441fff16e4dcbe1

Working on the _next_ workaround now...

**Comment by donmelton** [comment]
@samhutchins OK, I released the Gem. Thanks, again!
