### ISSUE TITLE
Seeing Error/Warning - Cannot load libnvidia-encode.so.1

### ISSUE THREAD

**Issue by kford** [donmelton/video_transcoding#249]
Hi Don,

I've started noticing this error below.  I see some posts indicating it might be a misinstalled ffmpeg or ffmpeg trying to locate that library and not find it at the expected location/filename.  It does not seem to have affected the output files that come out of your script.  I couldn't find that file on my system, which I think makes sense as I'm using an Intel integrated graphics chip.  Should I be concerned about it?  Can I force it to look for the right encoding library?

`Cannot load libnvidia-encode.so.1`
`Cannot load libnvidia-encode.so.1`
`Cannot load libnvidia-encode.so.1`
`Cannot load libnvidia-encode.so.1`
`[19:58:34] hb_init: starting libhb thread`
`[19:58:34] thread 7f898276b700 started ("libhb")`
`HandBrake 20190105185838-3c95342-master (2019010601) - Linux x86_64 - https://handbrake.fr
12 CPUs detected`

Thanks

**Comment by donmelton** [comment]
@kford Are you using the `nvenc_h264` hardware encoder? Because that's the only thing I can think of that would  cause that error within HandBrake or the libav library from FFmpeg.

Also, I suggest you open an issue on the HandBrake project itself to see if anyone else is having this problem.

**Comment by kford** [comment]
I'll open the issue with HB.  How can I tell if I'm using nvenc_264?  I'm not passing any arguments to transcode-video itself.

**Comment by donmelton** [comment]
@kford That means you're not using the`nvenc_h264` encoder explicitly. I guess `HandBrakeCLI` is linking with that library whether it's using it or not. Is `nvenc_h264` listed as one of the available encoders when you execute `HandBrakeCLI --help` on the command line?

**Comment by kford** [comment]
It seems that this is just Handbrake interrogating the system to see what's available.

[This](https://github.com/HandBrake/HandBrake/issues/1874) is the [rapid] response I got from Handbrake issues.

**Comment by kford** [comment]
Thanks again @donmelton

**Comment by donmelton** [comment]
@kford You are very welcome! Glad you got a response from the HandBrake team so quickly. I guess it's just chatty. :)

**Comment by prithivirajasingh** [comment]
sudo apt-get install libnvidia-encode1
-solved my issue.
