### ISSUE TITLE
How to produce 2000ish kb/s videos?

### ISSUE THREAD

**Issue by TehMaster** [donmelton/video_transcoding#250]
Hey! First want to say i really appreciate your work, and love the results. For TV series i like to store each episode in a 1080P 2000-2500ish kb/s video file (starting with a 4500ish kb/s file), but i cannot figure out the right combination of flags to accomplish this; Even when using the target bitrate (have tried 3000, 25000, 2000, 1500) and/or small options the produced file has a close to original bitrate. 

Is there a right set of flags i could set, or should i simply stick with the gui for these? Appreciate the help!

**Comment by samhutchins** [comment]
The default ratecontrol system used by `transcode-video` has a minimum quality bar, and it will ignore the target bitrate if it needs to to achieve that quality. If you add `--abr` or `--simple` to your command it will use a ratecontrol system that honours the target bitrate. 

The readme has some good information of the different ratecontrol system here: 
https://github.com/donmelton/video_transcoding#explanation

**Comment by donmelton** [comment]
@TehMaster As usual, @samhutchins has answered another support question perfectly while I've been AFK all day. (My car broke down while on a road trip.)

Does that solve the problem for you?

**Comment by TehMaster** [comment]
@samhutchins @donmelton Thanks guys, i really appreciate the replies! I will give this a go. Sorry to hear about your car Don!

**Comment by donmelton** [comment]
@TehMaster Thanks! Fortunately the dealership handled it and I'm back home again. :)

**Comment by donmelton** [comment]
@TehMaster Did the suggestion by @samhutchins work for you? If so, can we close this now as resolved?

**Comment by TehMaster** [comment]
Yes they did! Thank you again!

**Comment by donmelton** [comment]
@TehMaster No problem and glad to hear it!
