### ISSUE TITLE
4k to 1080p

### ISSUE THREAD

**Issue by tehbdg** [donmelton/video_transcoding#267]
Hi.

As my sad little i3 Plex server doesn't have the horsepower to transcode from 4k to 1080 in real time when I am watching on non-4k devices, I was thinking of making a few 1080 rips of 4k content on my i7 box. The problem is I can't work out how to do it. I have used the --720p switch in the past but the PQ looks a little dodgy. Is there an easy way of doing a 1080p rip?

Cheers

**Comment by donmelton** [comment]
@tehbdg I think you mean a 1080p _transcoding_, right? Because you've already ripped the 4K?

If so, just use the `--max-width` and `--max-height` options like this to scale your 4K video into a 1920x1080 boundary:

```
transcode-video --max-width 1920 --max-height 1080 "/path/to/Movie.mkv"
```

Does that work for you?

**Comment by tehbdg** [comment]
Thanks @donmelton , I will give it a whirl after my current encoding is complete.....

**Comment by tehbdg** [comment]
@donmelton That worked perfectly. I have also been trying out the --avbr setting, and it seems to be working out great, I had to reinstall the transcode-video packages using gem as I don't think the docker version has been updated yet. Using x264-10bit and --avbr on a UHD movie I am currently getting an average of 14.8 frames per second encode. Usually on x265-10 bit --simple I get around 3-4 fps. 
Obviously the files work out to be bigger. I just did a comparison using Once Upon A Deadpool 1080p. The original Remux was around 35gb.
--AVBR x264 1080p is 9.289 gb
Your old system worked out to be 15.4 gb
--simple x265 is 9.226 gb
That's pretty amazing.

**Comment by tehbdg** [comment]
> @tehbdg I think you mean a 1080p transcoding, right? Because you've already ripped the 4K?

> 
Sorry, I missed that. Yes I have already ripped the movies, now I want to transcode.

**Comment by donmelton** [comment]
@tehbdg I'm glad that worked for you! And that you're using and enjoying the new `--avbr` ratecontrol option. Thanks.

I'll close this now since your original issue is now resolved but feel free to comment again here or open new issues if you have additional questions.
