### ISSUE TITLE
transcode-video: mp4track version unknown

### ISSUE THREAD

**Issue by dgibbs64** [donmelton/video_transcoding#27]
Running ubuntu 15.10. Can confirm mp4track is installed and the correct version but transcode video is not picking this up.
    
    /usr/local/bin/transcode-video: mp4track version unknown

    user@video-transcode:~/output$ mp4track --version
    mp4track - MP4v2 -r

**Comment by donmelton** [comment]
@dgibbs64 Damn. There's yet another broken version string. I don't know how I can check for that, either, since it doesn't actually contain a version. :(

Did you build this `mp4track` yourself or is it from an Ubuntu package?

**Comment by dgibbs64** [comment]
It's the Ubuntu package

**Comment by dgibbs64** [comment]
Do you just want to checknits present orndonou need a specific version? Since your using ruby 2.0 I used a newer distro anyway

**Comment by donmelton** [comment]
@dgibbs64 I'll likely just pull the version check for `mp4track` and the other tools from the code sometime this week. It's been more trouble than it's worth than it's worth, causing problems for you and many others. That's what I get for over-engineering this.

**Comment by donmelton** [comment]
@dgibbs64 Just checked in a fix to no longer fail if `mp4track --version` doesn't actually return a version number. It seems I can't count on the version string being consistent.

I'll leave this open until I make an official release, probably early next week.

**Comment by dgibbs64** [comment]
@donmelton cheers! :D

**Comment by donmelton** [comment]
@dgibbs64 Just do a `gem update` to get version 0.2.8 with the fix. :)
