### ISSUE TITLE
Transcode all titles - Batch Encoding?

### ISSUE THREAD

**Issue by ProxyCell** [donmelton/video_transcoding#280]
Is there any chance of this suite receiving a feature to encode multiple DVDs or at least multiple titles on the same DVD?
I have a few music video DVDs that each have between 2 and 9 titles that represent different songs.

Any chance of accepting --titles=2-4 or something like that? It would have to be usable only with dry-run which I'm sure diminishes it's value a bit but I'm just thinking of batch jobs/loops for such use-cases.

**Comment by donmelton** [comment]
@ProxyCell I'm sorry but HandBrake doesn't support transcoding multiple titles at the same time from disc image directories so this would be a significant investment in a feature that I may remove in the future anyway. Transcoding from disc image directories has many limitations and bugs already so I try to discourage use of that feature as it is.

Thanks for opening this issue. My apologies for being the bearer of bad news. I'll close this now but feel free to comment here again or elsewhere.
