### ISSUE TITLE
Adding a subtitle (of any format) forces it into ASS format

### ISSUE THREAD

**Issue by Goorzhel** [donmelton/video_transcoding#281]
[Jokes about the title aside](https://en.wikipedia.org/wiki/SubStation_Alpha#Advanced_SubStation_Alpha)...

```
$ mediainfo foo.mkv --Output=JSON | jq '.media.track[4]'
{
  "@type": "Text",
  "@typeorder": "1",
  "ID": "4",
  "UniqueID": "9228952445193322396",
  "Format": "UTF-8",
  "CodecID": "S_TEXT/UTF8",
  "Language": "en",
  "Default": "Yes",
  "Forced": "No"
}
$ transcode-video foo.mkv -o Transcoded/foo.mkv --add-subtitle eng --no-auto-burn
<...>
$ mediainfo Transcoded/foo.mkv --Output=JSON | jq '.media.track[4]'
{
  "@type": "Text",
  "ID": "4",
  "UniqueID": "4",
  "Format": "ASS",
  "CodecID": "S_TEXT/ASS",
  "Compression_Mode": "Lossless",
  "Language": "en",
  "Default": "No",
  "Forced": "No"
}
```

This wouldn't be such a big deal to me if the Emby web-app, my player of choice, supported ASS (without transcoding, anyway). Plus, perhaps it's a streak of Luddism on my part, but I'm far more partial to plain-text formats.

**Comment by donmelton** [comment]
@Goorzhel Yes, we've all made those jokes over the years. :)

I too am far more partial to plain-text formats. However, if you add an SRT subtitle to your output via `HandBrakeCLI` (which is what `transcode-video` is using behind the scenes), then the FFmpeg-based library within HandBrake will always convert that subtitle to SSA/ASS format. And there's nothing I can do to prevent the conversion. It's just the way it works.

My advice is to use a tool like `mkvmerge` after transcoding to mux the subtitle you want into your transcoded output. Or just extract that subtitle as a standalone file and "sideload" it during playback. Which is what I do with Plex.

Do you have any other questions?

**Comment by Goorzhel** [comment]
Aha, I should've figured it was a Handbrake-ism. After beating my head on `mkvmerge` for about ten minutes, I hit upon a solution:
```
#!/bin/bash
transcode-video $1 -o Transcoded/$1 > /dev/null
mkvmerge -o Merged/$1 -S Transcoded/$1 -A -D $1
```
Thanks for the pointers, @donmelton!

**Comment by donmelton** [comment]
@Goorzhel You're very welcome and I'm that worked out for you!
