### ISSUE TITLE
Upscaling?

### ISSUE THREAD

**Issue by gingerbeardman** [donmelton/video_transcoding#283]
An odd request, but YouTube only allows 60fps videos at 720p or higher. 

So, I wondered if I could use `transcode-video` as part of my workflow to upscale my 4:3 ratio 720x480(640x480)@60Hz grabs of PlayStation 2 footage to 1080x720(960x720)@60Hz?

I appreciate that this is a bastard use of your tool. Forgive me :)

I see:
```
    --720p          fit video within 1280x720 pixel bounds
    --max-width WIDTH, --max-height HEIGHT
```
but they do not upscale

And:
```
    --pixel-aspect X:Y
```
but it does not accept 1.5 as a scale value nor allow upscaling.

How do you recommend I do this? Is it possible?

**Comment by donmelton** [comment]
@gingerbeardman Sorry I took so long to respond. I was traveling yesterday.

Since it's such an edge case and I don't want users to somehow do it accidentally, the only way to upscale with `transcode-video` is to pass options directly to `HandBrakeCLI`.

Try adding `--handbrake-option width=960 --handbrake-option height=720` to your command line and see if that works.

**Comment by gingerbeardman** [comment]
Thanks Don!

`--handbrake-option width=1080 --handbrake-option height=720`
and sometimes
`--handbrake-option width=1440 --handbrake-option height=1080`
are just the ticket!

I think I will buy a video scaler to do this upscaling step in hardware — seems like a better use of my time/money.

**Comment by donmelton** [comment]
@gingerbeardman You are very welcome, sir! Glad that worked. :)

**Comment by gingerbeardman** [comment]
Circling back to this, recording Wii I am now doing:
`hw-transcode-video *.m2ts --handbrake-option width=1280 --handbrake-option height=720 --pixel-aspect 4:4 transcode-video --crop 10:2:2:8 --mp4`

to upscale SD 720x480@60 anamorphic widescreen to 16:9 720p@60

Just posting here for my own records! LOL
