### ISSUE TITLE
How to pass HandbrakeCLI --optimize parameter?

### ISSUE THREAD

**Issue by gingerbeardman** [donmelton/video_transcoding#284]
It's a single so does not require = value

Maybe I should use HandbrakeCLI specifically for the task at hand?

**Comment by donmelton** [comment]
@gingerbeardman Sorry I took so long to respond. I've been playing the World of Warcraft Classic stress test today. :)

Just add `--handbrake-option optimize` to your command line if you really want to use it. But be advised that optimizing MP4 files for streaming is not only slow, but it's completely pointless. There's no advantage to it anymore these days.

**Comment by gingerbeardman** [comment]
I could have sworn I tried that — just checked my command history and I made a typo `-handbrake-option optimize` rather than `--handbrake-option optimize` 

FYI optimizing speeds up processing on YouTube. Every little helps :)

https://support.google.com/youtube/answer/1722171?hl=en-GB

**Comment by donmelton** [comment]
@gingerbeardman Thanks for the heads up on YouTube requirements. Figures. :) Anyway, you can always "optimize" after transcoding with FFmpeg.

**Comment by gingerbeardman** [comment]
Another thing I did not know! Cheers
