### ISSUE TITLE
Burn in sub while cutting video

### ISSUE THREAD

**Issue by nobitataj** [donmelton/video_transcoding#285]
Hi, recently I experience a problem when burning in subtitle (soft-sub) and cutting video at the same time. For instance, if I am to cut video from 0:00:30 to 0:01:00 with Handbrake params -H start-at=duration:30 -H stop-at=duration:30, and my input video has a soft-sub contains a line from 0:00:25 to 0:00:35, then my output video will not be showing that line at the beginning, and the whole line will be missing from output video. I tried this with HandBrake GUI, and the same thing happened, so I guess this is HandBrake's issue.
The thing is, when I tried using FFMPEG to do the exact same cutting/burning-in thing (ffmpeg -i input.mp4 -ss 00:00:30 -t 00:00:30...), the line was shown for the first 5s of the ouput video (which is what should've been done with HandBrake).
My question is, is there any option I can do to force transcode-video to use ffmpeg for cutting video instead of using HandBrake? or any other way for me to achieve my goal?
P.S: I've tried -E ss=30 -E to=30, didn't work.
Thank you all for your time!

**Comment by donmelton** [comment]
@nobitataj I'm sorry but there's no way to force `transcode-video` to use `ffmpeg` instead of `HandBrakeCLI` as its transcoding engine.

And if this problem is also happening with the HandBrake GUI app, then there's no way to work around it. My apologies for the inconvenience.

**Comment by donmelton** [comment]
@nobitataj OK, I'll close this for now. Just comment here or open another issue if you have more questions.
