### ISSUE TITLE
Ability to specify "--force-subtitle" by language code

### ISSUE THREAD

**Issue by notDavid** [donmelton/video_transcoding#290]
Hi there!

I was wondering if you would consider adding the ability to set the forced subtitle by language code instead of the index.
So for example: `--force-subtitle NLD`.

Perhaps aborting with an error in the rare case where multiple indexes with the same language code are found, since you can't force multiple subtitles. Or maybe just forcing the first match.

When transcoding many files, finding the specific index of a language for each file in a batch separately, can be quite a pain :)

Thank you! 🙏🏼

**Comment by donmelton** [comment]
@notDavid I understand the difficulty you're having but I don't want to introduce a behavior that would either often fail or seem to behave capriciously. By definition both `--burn-subtitle` and `--force-subtitle` have a one-to-one mapping. Adding a language as an argument makes this semantically confusing.

So, I'm have to say "no" this time. Sorry about that.

**Comment by notDavid** [comment]
Yea i understand, it wouldn't be a perfectly clean/solid solution...

Although the alternative, using `--scan` and grep voodoo to find the index, is not very solid either 😅
