### ISSUE TITLE
"--add-subtitle" has no effect on transcode_video

### ISSUE THREAD

**Issue by ctismer** [donmelton/video_transcoding#291]
Hi @donmelton,
I tried a lot of permutations, but it seems that `transcode_video` ignores everything concerning subtitles. Maybe something has changed in `HandBrakeCLI` that the script no longer understands, or I am doing something completely wrong?

The following is an example, but this problem is with all my `MakeMkv` rips.
The command line is
```
transcode-video --main-audio 3 --add-audio 1 --add-subtitle ger \
    --copy-audio all --copy-audio-name all --audio-width all=surround \
    "${SOURCE}.mkv" -o "${SOURCE}-dm.mkv"
```
because I am trying to keep everything identical to the origin and only transcode the video.
This works great for audio, but no luck with subtitles.

I used the main track of _Aviator - The Aviator (2004) DiCaprio Blanchett K.Beckinsale Reilly Baldwin Spiner Dafoe_ which has the following layout:
[aviator_mkvinfo.txt](https://github.com/donmelton/video_transcoding/files/3430923/aviator_mkvinfo.txt)

This seems to be not an issue with the language "ger". The same (nothing) happens with explicit track numbers. I use a MacBook Pro (15-inch, 2016) with English language settings but a German keyboard.
```
$ transcode-video --version
transcode-video 0.25.2
Copyright (c) 2013-2019 Don Melton
$ HandBrakeCLI --version
[11:57:23] hb_init: starting libhb thread
[11:57:23] thread 700008a9c000 started ("libhb")
HandBrake 1.2.2

HandBrake has exited.
```
I use `"${SOURCE}-dm.mkv"` to mark my files as "processed with Don Melton script", but unfortunately I have to do another post-process with `mkvmerge`, which I do by hand, currently :wink:.
Otherwise, I am very happy with your script, although it is not written in `Python` :stuck_out_tongue_closed_eyes:.

**Comment by donmelton** [comment]
@ctismer Thanks for using my tools!

OK, I don't seen anything wrong in your sample command line that would prevent subtitles from being added to your transcoded output. And I can assure that both `transcode-video` version 0.25.2 and `HandBrakeCLI` version 1.2.2 still work for myself and my collaborators as far adding subtitles goes, either by language or by explicit track numbers.

So something else must be going on.

In order to help, I'll need some more information.

Can you include the output here of that same command with the `-vv --dry-run` options added? That way I can get extensive diagnostic information and, more importantly, see what `transcode-video` is passing to `HandBrakeCLI`.

Thanks!

**Comment by ctismer** [comment]
@donmelton Thank you for taking care!
Meanwhile it is a different file: `The American (2010) Clooney Reuten Placido`.
```
$ transcode-video --main-audio 1 --add-audio 3 --add-audio 5="Commentary" \
    --add-subtitle ger --copy-audio all --copy-audio-name all --audio-width all=surround \
    -vv --dry-run "${SOURCE}.mkv" -o "${SOURCE}-dm.mkv" \
    > the_american_dm.txt 2> the_american_dm2.txt
```
The stdout file contains `HandBrakeCLI --input=/Users/tismer/Movies/conv/The\ American\ \(2010\)\ Clooney\ Reuten\ Placido/The\ American.mkv --output=/Users/tismer/Movies/conv/The\ American\ \(2010\)\ Clooney\ Reuten\ Placido/The\ American-dm.mkv --markers --encoder=x264 --crop=0:0:0:0 --auto-anamorphic --encoder-profile=high --encoder-level=4.0 --quality=1 --audio=1,3,5 --aencoder=copy,copy,copy --audio-fallback=ac3 --aname=Surround\ 5.1,Surround\ 5.1,Commentary --encopts=vbv-maxrate=6000:vbv-bufsize=12000:crf-max=25:qpmax=34`

**Comment by donmelton** [comment]
@ctismer Thanks for all the diagnostic information! That's exactly what I needed to figure out your problem.

OK, here's what you need to do: change `--add-subtitle ger` to `--add-subtitle deu`.

I realize that `ger` _should_ be an alias for the ISO 639-2 language code `deu` (for German), but that's not what `HandBrakeCLI` is embedding in the metadata. And my `transcode-video` tool has to use the metadata as provided.

Let me know if that fixes the problem.

**Comment by ctismer** [comment]
Whow, great!
For some reason. I thought that "eng" and "ger" had already worked on audio channels, but I may have been mislead. The second problem was that I made the false assumption that all channels were numbered in one sequence, starting with "0" for the video. This came from the channel ordering in {VLC} and {MkvMerge}, which actually had nothing in common with the reality but the correct audio channel numbers ;-)
So after "ger" did not work, and after "6,8" did not work either, I concluded that subtitles would not work, altogether :-)

I checked again, and there the "shit" happens:
```
transcode-video --main-audio ger --add-audio 3 --add-audio 5="Commentary" \
    --add-subtitle ger --copy-audio all --copy-audio-name all --audio-width all=surround \
    "${SOURCE}.mkv" -o "${SOURCE}-dm.mkv"
```
actually _works_ for the `--main-audio` case, just not for the subtitles!
Funny, there must have been different teams been hacking on this code :-)

Ok, now that this is solved, I would like to add that this "silent ignore if nonexistent" is a bit error prone, and it would be nice if all channel arguments would have an option that prevents this silent ignore mode:
Both the effect that "ger" does sometimes something and sometimes nothing, and also that "6,8" does nothing, because 6 or 8 simply don't exist in the (not so obvious) numbering of this movie are quite misleading. A warning that those don't exist would be great. (Although this "ignorance" mode is quite handy to read many sources with a single batch file.)
Maybe it would help both uses and developers to add standard test cases to everything, that ensure that _something_ defined works. I would love to provide that, but that is not my language ;)

Your's sincerely -- Chris

**Comment by ctismer** [comment]
He-Ho @donmelton I fear there is more to fix.
When I use the command line
```
transcode-video --main-audio 1 --add-audio 3 --add-audio 5="Commentary" \
    --add-subtitle deu --add-subtitle eng --copy-audio all --copy-audio-name all \
    --audio-width all=surround "${SOURCE}.mkv" -o "${SOURCE}-dm.mkv"
```
then I get English subtitles, only! The script does not complain that I re-used the same option.
If I use
```
transcode-video --main-audio 1 --add-audio 3 --add-audio 5="Commentary" \
    --add-subtitle deu,eng --copy-audio all --copy-audio-name all \
    --audio-width all=surround "${SOURCE}.mkv" -o "${SOURCE}-dm.mkv"
```
then the original numbering is retained, what I don't want, either, so I have to use the (correct) channel numbers. (Yes, I am a PITA)

Cheers -- Chris

**Comment by donmelton** [comment]
@ctismer The behavior you describe is intentional and designed that way to behave like other UNIX/Windows command line tools. This is because it allows you to nested wrapper scripts which override initial arguments.

So that won't be changed.

Anything else I can help you with?

**Comment by ctismer** [comment]
@donmelton Initial arguments: Ok, understood (although not liked).
Thanks, the only really annoying thing that remains is that "ger" and "eng" are treated differently between audio and subtitles, and they are not checked at all:
There is a difference if you don't have "deu" because it is not in the data, or if you don't have "ger" because that name is not implemented at all. I would add a check for that, meaning
"if you don't see anything, then because you don't have such data".
But silently ignoring a thing that exists in "audio" but not in "subtitles" is worth improving.

Cheers -- Chris

**Comment by donmelton** [comment]
@ctismer Thanks for the feedback! I will consider that, sir!

Do you want to close this now? (And, BTW, feel free to open other issues as you find them!)

**Comment by ctismer** [comment]
Yes, closing. 
I'm not really happy with the rule that `--add-subtitle <name>` can only appear once, while '--add-subtitle <number>' can occur multiple times, for some vague `Unix` convention.
I'm not used to that, because the `Python` language is very explicit there, to avoid unforeseen effects like those that have bitten me. :wink:

Cheerioh - Chris
