### ISSUE TITLE
Duplicate Audio Tracks

### ISSUE THREAD

**Issue by Jasmer** [donmelton/video_transcoding#294]
Hello Don!

Thank you for this project! Small issue. I attempted a simple mkv to m4a conversion using convert-video "sample.mkv"

All went well except it duplicated the first track. This happened on three different videos. So as you can see in the attached screenshot, there is an extra duplicated track.
![conversion error](https://user-images.githubusercontent.com/2568784/63425329-e6414b80-c3d5-11e9-93a1-32829771a659.png)

Thanks so much,

Jas

**Comment by donmelton** [comment]
@Jasmer You are very welcome and thank you for using my tools!

The behavior you're seeing is intentional. This is because your input main audio surround track is being copied as stereo track as well. You can disable that behavior via the `--no-double` option. Here's how it's described in the built-in `--help` output:

```
    --no-double     don't swap order of first two audio tracks
                      or add stereo copy of main surround track
```
Did that fix the problem?

**Comment by Jasmer** [comment]
@donmelton Hello and thank you for your quick response! I am looking to do a straight 1 to 1 convert with no doubling. I'm working to expand my encoding knowledge so I have a few questions if you don't mind.

- So would the command then be >  convert video --no-double "example.mkv" ?

- Re: Swapping the order of the tracks. I am preparing videos for iTunes and AppleTV. I notice when I use Handbrake, some of the presets default to stereo as the first track and then, 5.1 for the second track. Why? I would think I would want 5.1 as the first track and if AppleTV is set to auto audio it should resolve that on its own. I notice in the help output you listed above it says "don't swap order of first two audio tracks". There must be a reason for ordering the tracks.

- I notice above in my screenshots the titles of the tracks are the same. How would I know which one is stereo if the track names stay the same after the doubling?

- There may be a situation in which I would want the audio track it doubled, in that case, is there a way to append the title with "(2 channel)" or anything similar so I can tell which is which?

My questions are admittedly a bit rudimentary. If you could straighten me out on these, I would greatly appreciate it.

Thank you,

Jas

**Comment by samhutchins** [comment]
> So would the command then be > convert video --no-double "example.mkv" ?

Yup

> Re: Swapping the order of the tracks. I am preparing videos for iTunes and AppleTV. I notice when I use Handbrake, some of the presets default to stereo as the first track and then, 5.1 for the second track. Why? I would think I would want 5.1 as the first track and if AppleTV is set to auto audio it should resolve that on its own. I notice in the help output you listed above it says "don't swap order of first two audio tracks". There must be a reason for ordering the tracks.

Stereo followed by surround is the convention from iTunes. I believe the reason for this is backwards compatibility when Apple upgraded iTunes films from stereo to surround. 

Don's tools do different things with the audio depending on the output format. By default, mp4 files will have stereo first and surround second, to match iTunes, but MKV output does what you've suggested: surround followed by stereo. Both `transcode-video` and `convert-video` have mechanisms to choose the order (for example, I use `--reverse-double-order` with `transcode-video` to produce MKV files with the stereo track first)

> I notice above in my screenshots the titles of the tracks are the same. How would I know which one is stereo if the track names stay the same after the doubling?
> 
> There may be a situation in which I would want the audio track it doubled, in that case, is there a way to append the title with "(2 channel)" or anything similar so I can tell which is which?

I don't think there's a way to name audio tracks with `video_transcoding`. You might be able to use the `--handbrake-option` with `transcode-video` to do it, but I don't think there's any mechanism to do it with `convert-video`

**Comment by samhutchins** [comment]
@Jasmer I don't think there's a way to do that with Don's tools, but the GUI for `mkvtoolnix` is pretty good for this kind of thing

<img width="1457" alt="Screenshot 2019-08-28 at 13 13 20" src="https://user-images.githubusercontent.com/13986933/63854716-b249c580-c995-11e9-8019-a08268f6dd1b.png">

Although that will produce mkv files.

You could also use `ffmpeg` directly, using the `-map` and `-c:v copy -c:a copy` options

@donmelton might have some better ideas though

**Comment by martinpickett** [comment]
If you are a Mac user then you might want to investigate Subler - https://subler.org/

The UI is not particularly intuitive but it can do what you want.

**Comment by Jasmer** [comment]
> If you are a Mac user then you might want to investigate Subler - https://subler.org/
> 
> The UI is not particularly intuitive but it can do what you want.

Excellent. Works perfectly. Thank you @martinpickett

**Comment by donmelton** [comment]
Thanks @samhutchins and @martinpickett!

@Jasmer Is this issue resolved sufficiently to close it now?

**Comment by Jasmer** [comment]
Yes @donmelton THANK YOU for developing these tools. They have proven to be integral in my workflow. I sent you a LinkedIn request.

I'm having an interesting, enlightening and incredibly detailed discussion regarding converting/transcoding (Handbrake, Subler, Plex, iTunes etc.) here.
https://forums.plex.tv/t/encoding-video-audio-on-macos/449187/18

Much Appreciation,

Jas

**Comment by donmelton** [comment]
@Jasmer I'm very glad you like these tools and that they're working for you! And thanks for the pointer to the discussion. BTW, I don't really use LinkedIn anymore. Sorry about that.
