### ISSUE TITLE
Specifying Language --add-srt

### ISSUE THREAD

**Issue by phillipsmn** [donmelton/video_transcoding#296]
I'm sorry if this is addressed somewhere, but I can not find out how to set the language for the subtitles when I'm adding via an SRT. 

I've tried naming the SRT file with the language included in the filename, but the output shows: 

`* subtitle track 1, Unknown [SRT] (track 0, id 0xff, Text) -> Passthrough, offset: 0, charset: ISO-8859-1` 

I've tried using `-N` and  `--native-language` as well as `--srt-lang eng` and none of these work (I tried them because they are a part of the [HandBrake CLI documentation](https://handbrake.fr/docs/en/1.2.0/cli/command-line-reference.html)).

My SRT file is being added, but it is showing as Unknown which isn't game breaking, but annoying.

Can anyone tell me what I'm doing wrong, or if it is possible to designate language for SRT files being included?

Below is an example of the command I'm using:

`transcode-video -e vt_h264 --avbr --add-srt 20191008-Vid-Master.eng.srt 20191008-Vid.mov -o 20191008-Vid.mp4`

**Comment by donmelton** [comment]
@phillipsmn My apologies for taking so long to respond.

You need to use the `--bind-srt-language` option. It's described in the builtin `--help` this way:

```
    --bind-srt-language CODE
                    bind ISO 639-2 language code (default: und)
                      to previously forced or added subtitle
                      (can be used multiple times)
```

So, you can change your command line to this:

```
transcode-video -e vt_h264 --add-srt 20191008-Vid-Master.eng.srt --bind-srt-language eng 20191008-Vid.mov -o 20191008-Vid.mp4
```
...and that should work.

**Comment by phillipsmn** [comment]
@donmelton your response was definitely fast enough for me...and thank you for the answer. 

You have really built an awesome tool and I truly appreciate your work! Thank you again.
