### ISSUE TITLE
Compatibility w/ macOS 10.15 Catalina

### ISSUE THREAD

**Issue by seventhaxis** [donmelton/video_transcoding#297]
So I didn't notice anything listed as 32-bit in my Mojave system report, so I pulled the trigger and did a clean install of macOS 10.15 Catalina. I'm certainI have all the listed dependencies installed via HomeBrew and went to process a film. Unfortunately I'm receiving an error immediately -- see below:

```
$ transcode-video --target big --no-auto-burn /path/to/movie/file.mkv --verbose
transcode-video 0.25.2
Copyright (c) 2013-2019 Don Melton
Processing: /path/to/movie/file.mkv...
Scanning media title 1 with HandBrakeCLI...
HandBrake 1.2.2 found...
/usr/local/bin/transcode-video: scanning media title 1 failed
```

No log file is generated in the working directory. Any ideas? Is this a Catalina issue?

**Comment by donmelton** [comment]
@seventhaxis Unknown whether it's a Catalina-specific problem yet.

But why are you placing the `--verbose` option after the input file name? That's not going to work. The input file name(s) always come at the end of the command line.

**Comment by donmelton** [comment]
@seventhaxis Also, can you try this command:

```
transcode-video --dry-run /path/to/movie/file.mkv
```

Then copy the the `HandBrakeCLI` command that's printed out and execute that?

That way we can determine whether the problem is with `transcode-video` or `HandBrakeCLI`.

Thanks.

**Comment by seventhaxis** [comment]
> But why are you placing the `--verbose` option after the input file name?

![](https://media.giphy.com/media/AKaEfzaLlr0yI/giphy.gif)

@donmelton So I get the same with `--dry-run` it seems.

```
$ transcode-video --dry-run /path/to/movie.mkv
/usr/local/bin/transcode-video: scanning media title 1 failed

$ transcode-video --dry-run --verbose /path/to/movie.mkv
Copyright (c) 2013-2019 Don Melton
Processing: /path/to/movie.mkv...
Scanning media title 1 with HandBrakeCLI...
HandBrake 1.2.2 found...
/usr/local/bin/transcode-video: scanning media title 1 failed
```

**Comment by donmelton** [comment]
@seventhaxis LOL! OK, now that I've spilled some of my coffee laughing at that... :)

Let's see if `HandBrakeCLI` is also failing if you call it directly. Try this command:

```
HandBrakeCLI --title 0 --scan --previews 2:0 --input  /path/to/movie.mkv
```
...and let me know what happens. Thanks!

**Comment by seventhaxis** [comment]
```
$ HandBrakeCLI --title 0 --scan --previews 2:0 --input  /path/to/movie.mkv
[12:17:11] hb_init: starting libhb thread
[12:17:11] thread 70000d99a000 started ("libhb")
HandBrake 1.2.2 (2019101100) - Darwin x86_64 - https://handbrake.fr
12 CPUs detected
Opening /path/to/movie.mkv...
[12:17:11] CPU: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
[12:17:11]  - Intel microarchitecture Kaby Lake
[12:17:11]  - logical processor count: 12
[12:17:11] hb_scan: path=/path/to/movie.mkv, title_index=0
[1]    18128 segmentation fault  HandBrakeCLI --title 0 --scan --previews 2:0 --input
```

Really appreciate you troubleshooting this Don.

**Comment by donmelton** [comment]
@seventhaxis No problem! OK, so `HandBrakeCLI` is crashing. Maybe you can try re-downloading and re-installing it?

**Comment by seventhaxis** [comment]
![](https://asciinema.org/a/vrAyOcqv2jt9lUxw9bQVPRgZr?autoplay=1&loop=1)

**Comment by seventhaxis** [comment]
Ah, no dice after uninstalling/reinstalling Handbrake (v1.2.2) via HomeBrew.

![](https://media.giphy.com/media/JYrBeHNSSZZvi/giphy.gif)

**Comment by donmelton** [comment]
@seventhaxis Ouch! OK, I recommend you open an issue on HandBrake itself here:

https://github.com/HandBrake/HandBrake/issues

Because honestly I don't know how to proceed. Sorry about that. :(

**Comment by seventhaxis** [comment]
Thanks @donmelton. Closing for now.
Will reopen and follow up as new information is released or an update is provided for HandBrakeCLI.

https://github.com/HandBrake/HandBrake/issues/2364

**Comment by donmelton** [comment]
@seventhaxis Re-opening this to ask you how you installed `HandBrakeCLI`. Did you download the binary from the website or did you use Homebrew to install it? Because, based on other information I received today, it looks like the Homebrew version has problems on Catalina.

**Comment by seventhaxis** [comment]
@donmelton Hah yeah my issue over there got the exact same response. I removed the HomeBrew version and manually installed it. When executing a dry run I get the following:

```
$ transcode-video --dry-run /path/to/movie.mkv
HandBrakeCLI --input=/path/to/movie.mkv --output=movie.mkv --markers --encoder=x264 --crop=0:0:0:0 --auto-anamorphic --encoder-profile=high --encoder-level=4.0 --quality=1 --audio=1,1 --aencoder=ac3,ca_aac --mixdown=,stereo --encopts=vbv-maxrate=6000:vbv-bufsize=12000:crf-max=25:qpmax=34
```

Seems good, so I tried the transcoding process again and it's working as expected!

![](https://media.giphy.com/media/135aoPCsZli7QI/giphy.gif)

As always, you da man!

**Comment by donmelton** [comment]
@seventhaxis Thanks and no problem, sir! :)
