### ISSUE TITLE
Is it possible to define start/stop timestamps?

### ISSUE THREAD

**Issue by seventhaxis** [donmelton/video_transcoding#298]
Is it possible (or potentially an enhancement) to add start and stop timestamps for the purposes of only transcoding that duration of the video file?

**Comment by donmelton** [comment]
@seventhaxis Sure, it's possible by using `--handbrake-option` or `-H` to pass options directly through to `HandBrakeCL` like this:

```
transcode-video -H start-at=duration:30 -H stop-at=duration:45 "/path/to/Movie.mkv"
```
See this section from the output of `HandBrakeCLI --help` for more details:

```
   --start-at <string:number>
                           Start encoding at a given duration (in seconds),
                           frame, or pts (on a 90kHz clock)
                           (e.g. duration:10, frame:300, pts:900000)
   --stop-at  <string:number>
                           Stop encoding at a given duration (in seconds),
                           frame, or pts (on a 90kHz clock)
                           (e.g. duration:10, frame:300, pts:900000)
```

Does that answer your question?

**Comment by seventhaxis** [comment]
Awesome, that's very helpful. I'll need to read up more on how to narrow down the timings to be very specific. Thanks!

**Comment by seventhaxis** [comment]
Do you happen to know of a quality application to reliably extract frame number at a specific position?

**Comment by donmelton** [comment]
@seventhaxis Yes, you can use `ffmpeg` or `mkvextract` for that, although the syntax is a bit complicated.

**Comment by seventhaxis** [comment]
Okay, thanks @donmelton -- will do some research!

**Comment by seventhaxis** [comment]
@donmelton I haven't found an answer to this question -- am I restricted to integers when targeting duration/seconds? Or can I do SS.MS?

**Comment by seventhaxis** [comment]
Well that seemed to work fantastically.

Best. Tool. Ever.
