### ISSUE TITLE
Scanning Media Failed

### ISSUE THREAD

**Issue by jxp05j** [donmelton/video_transcoding#301]
I am getting the following error every time I try to use convert_video or transcode_video:

`Scanning media title 1 with HandBrakeCLI...
HandBrake 1.3.0 found...
/usr/local/bin/transcode-video: scanning media title 1 failed`

I have tried several different media files and I get the same error every time.  I am running fresh install of  Mac OS 10.15.1.  Is there any guidance as to what I should do to diagnose and fix the problem? Thank you in advance!

**Comment by salicio** [comment]
I had the same problem but only using the version installed with brew, that version of HandBrakeCLI gives me a segmentation fault. 

Try uninstalling that version and trying to install directly the downloaded one from the website.

https://handbrake.fr/downloads2.php

**Comment by donmelton** [comment]
@jxp05j I would agree with @salicio 's suggestion for you to try install a downloaded version of `HandBrakeCLI` from the website to see if that fixes your problem. Be sure to remove any version of `HandBrakeCLI` installed with Homebrew first.

Let me know if that doesn't work and we'll figure out how to proceed.

**Comment by jxp05j** [comment]
That did it.  Thank you for your help and the work you do on these tools!

**Comment by donmelton** [comment]
@jxp05j No problem and you are very welcome!

I'll close this now but feel free to comment again or open another issue.
