### ISSUE TITLE
Pass-through video?

### ISSUE THREAD

**Issue by vasuvasu** [donmelton/video_transcoding#303]
Just spent twelve years encoding 40 files with x265 and realized I copied the original DTS track over instead of encoding down to 384kbit eac3 like I meant. Is there a way to run through a new batch again, but pass-through video and just re-do audio?

**Comment by donmelton** [comment]
@vasuvasu Ouch. Well, I think we've all done something like that at one time or another.

So, there's no way to do this with `transcode-video` or even `HandBrakeCLI` but there's a fairly easy way to do this with `ffmpeg`. A command something like this could work:

```
ffmpeg -i input.mkv -c:v copy -c:a eac3 -b:a 384k output.mkv
```

Does that help?

**Comment by vasuvasu** [comment]
Yes, thank you so much!

**Comment by donmelton** [comment]
@vasuvasu Great! Once you have that working, we can close this issue.
