### ISSUE TITLE
mp4v2 on Ubuntu 19.10?

### ISSUE THREAD

**Issue by tjesp** [donmelton/video_transcoding#306]
I am not sure if the author is using Ubuntu but then I will just ask the general users if there is a way to install mp4v2 on Ubuntu 19.10? (latest version).

I used to have Ubuntu 18.04 where I could just install it, but now it seems to be gone from the standard repositories.

I went to their Google Code page and downloaded the source but I have much trouble compiling it (I am not a developer).

So, does anybody know a third party repository who offers it, a PPA or anything similar?

**Comment by donmelton** [comment]
@tjesp I'm sorry you're having this problem. I don't use Ubuntu, but I'll ask the hivemind if they can help. Stay tuned...

**Comment by tinusn** [comment]
I never succeeded in finding one, I used the source to compile it. But that has been a while I have since switched to Manjaro where the package is there.

Sorry I cannot help you more.

**Comment by samhutchins** [comment]
Can you download the deb manually from here: https://packages.ubuntu.com/bionic/mp4v2-utils ? (it's the version from 18.04, but it might still install on newer versions of Ubuntu)

**Comment by tjesp** [comment]
Ok, I solved it this way. Install libmp4v2:

https://packages.ubuntu.com/bionic/amd64/libmp4v2-2/download

Install mp4v2-utils:

https://launchpad.net/ubuntu/bionic/amd64/mp4v2-utils/2.0.0~dfsg0-6

However I do hope that Canonical/Ubuntu intends to add this again. Perhaps I could petition them somehow? 

There seems to be an empty entry here for it on 19.10:

https://launchpad.net/ubuntu/eoan/amd64/mp4v2-utils

Anyway, closing this now since the author of this tool can't do anything about it.

**Comment by zchrykng** [comment]
Just FYI. It appears that mp4v2-utils was removed from Debian since "... it's dead upstream and better alternatives exist."

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921127

**Comment by donmelton** [comment]
@zchrykng Thanks for the heads up. I wish I knew what Moritz means by "better alternatives."

**Comment by zchrykng** [comment]
No worries!

You've got me. I only found that because a friend is a maintainer for some Ubuntu stuff.

**Comment by jhbeskow** [comment]
Has anyone been able to actually get this installed on 20.04?  I had it working on Bionic.  It looks like mp4v2 has not been maintained in years, and I get the following error on make:

src/rtphint.cpp: In member function ‘void mp4v2::impl::MP4RtpHintTrack::GetPayload(char**, uint8_t*, uint16_t*, char**)’:
src/rtphint.cpp:342:35: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
  342 |                     if (pSlash != '\0') {
      |                                   ^~~~
make: *** [GNUmakefile:1391: src/rtphint.lo] Error 1

**Comment by donmelton** [comment]
@jhbeskow Ouch! What if you try to pass that `-fpermissive` flag to the compiler?

**Comment by jhbeskow** [comment]
Like so?  make CFLAGS='-fpermissive'

I get the same exception.

**Comment by jhbeskow** [comment]
Actually, it would be CXXFLAGS.  Trying that now.

**Comment by jhbeskow** [comment]
That got it.  Thanks!

To make this work:

git clone https://github.com/mp4v2/mp4v2.git ~/mp4v2
cd ~/mp4v2
autoreconf -i 
./configure 
make CXXFLAGS='-fpermissive'
make install

**Comment by donmelton** [comment]
@jhbeskow Sweet! I don't suppose there's any point in submitting a pull request to the project with that in `GNUmakefile.am`?

**Comment by jhbeskow** [comment]
Possibly.  I noticed there haven't been any changes in years, based on the dates on the repo, so who knows if someone will review it.  At least it is documented here so folks searching the web can find out how to make it work.

**Comment by jhbeskow** [comment]
This may or may not be related.  I tested out an mkv I found here: http://www.jell.yfish.us/

Command: transcode-video --m4v --quick Downloads/jellyfish-110-mbps-hd-hevc.mkv

End of output:
_Encode done!
HandBrake has exited.

**/usr/local/bin/transcode-video: mp4track failed during execution**_

The output video plays just fine, log file does not even have that exception in it.  Is this normal?  Is there a good way to figure out what happened?

**Comment by donmelton** [comment]
@jhbeskow No, that's not normal. And I have no idea why that would have happened.

**Comment by jhbeskow** [comment]
The files seem to play OK. What is mp4track used for?

**Comment by jhbeskow** [comment]
I'll just drop this here as part of this discussion.  I created a Docker image to package all of this up.  It does not have the mp4track exception I spoke of above:  https://hub.docker.com/r/jhbeskow/transcode-video

**Comment by jhbeskow** [comment]
No problem!

**Comment by yermak** [comment]
Just tested on Ubuntu 20.04 LTS
wget http://archive.ubuntu.com/ubuntu/pool/universe/m/mp4v2/libmp4v2-2_2.0.0~dfsg0-6_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/universe/m/mp4v2/mp4v2-utils_2.0.0~dfsg0-6_amd64.deb
dpkg -i libmp4v2-2_2.0.0~dfsg0-6_amd64.deb
dpkg -i mp4v2-utils_2.0.0~dfsg0-6_amd64.deb

I addition with regard to building from source.
I used quite succeffully fork of original mp4v2 : https://github.com/TechSmith/mp4v2
Was able to compile it for windows, not yet tried Mac and Linux
