### ISSUE TITLE
Curious about encoding FPS drop recently

### ISSUE THREAD

**Issue by octopush-it** [donmelton/video_transcoding#308]
Using a Macbook Pro to encode for the longest time using this package - always had relatively good framerates encoding until about a week ago.  I went from 30-60fps down to 4-10fps using the exact same command line:  --mp4 --quick --target small 

This happened before my upgrade to Catalina, and continues after my upgrade - so pretty sure it isn't related to that.  Curious if this is a known issue or something specific I should check?  Ruby gem install is updated too. Thanks!

**Comment by donmelton** [comment]
@octopush-it Well, my code hasn't changed in over 8 months so I doubt it's `transcode-video`. It could be related to an updated version `HandBrakeCLI`, but that's unlikely.

What's more likely is that you have something else on your system using CPU cycles or slowing down your disk I/O. Have you used the Activity Monitor app yet to see if there's anything suspicious going on?

**Comment by ttyS0** [comment]
@octopush-it A dramatic drop like that can happen when the source material resolution jumps. For instance, did you start using 2160 source rips instead of 1080?

**Comment by octopush-it** [comment]
Oh snap - I didn't realize that - I *did* just start encoding 2160 source material for the first time recently, didn't equate that as part of the issue.  I will look to some 1080 content to confirm.  Thanks @ttyS0 !

**Comment by donmelton** [comment]
@octopush-it OK, I'm gonna guess that @ttyS0 nailed it (many thanks, Sean!) and close this issue for now. Just re-open if that's not the case.
