### ISSUE TITLE
Converting H.265 to H.264

### ISSUE THREAD

**Issue by asheimo** [donmelton/video_transcoding#309]
So I started using H.265 seeing newer must be better. Well now that I see issues with CPU usage with Plex, and overall browser support for H.265 I see that I should have stuck with H.264. Since I had all the setting the way I wanted for H.265 as far as languages, subtitles, forced subtitles etc. Can I just put all the files through Transcode-Video again using h.264 as the encoder or do I need to run all the same settings to not lose anything I had already gotten in the files?

**Comment by donmelton** [comment]
@asheimo Unfortunately you'll need to re-transcode your original files with those same settings. :(
