### ISSUE TITLE
mplayer not available

### ISSUE THREAD

**Issue by luminose** [donmelton/video_transcoding#31]
Running in OSX. I closed terminal in the middle of an encode and now get the following error:

/usr/local/bin/transcode-video: mplayer not available

mplayer was not an active process and rebooting didn't resolve the issue.

**Comment by donmelton** [comment]
@luminose Weird. Well, `mplayer` is used behind the scenes depending on which options you use.

No idea why rebooting wouldn't fix this

Can you paste in your command line here?

**Comment by luminose** [comment]
Here's what I'm running:

transcode-video --m4v --big --crop detect movie.mkv

**Comment by donmelton** [comment]
@luminose Sorry, I missed the email notification from GitHub yesterday. My bad.

Yeah, the `--crop detect` option and argument requires `mplayer` to do the detection.

But I still have no idea why closing the Terminal.app would have screwed everything up unless `HandBrakeCLI`, `mplayer` or one of the other tools that `transcode-video` calls wrote some weird kind of persistent state out to disk. And I've never seen that happen. At least, not yet.

Can you try reinstalling `mplayer` via Homebrew to see if that clears things up? With this command:

    brew reinstall mplayer

Also, you might want to see if there's anything weird in your `~/.mplayer` folder.

Other than that, I'm still scratching my head over this one.

**Comment by luminose** [comment]
Reinstalling did the trick. Thanks!

**Comment by donmelton** [comment]
@luminose Wow! That was just a "Hail Mary" idea. :) Glad it worked, though.

OK, I'm closing this one. But it's definitely a contender for the weirdest bug I've seen. :)
