### ISSUE TITLE
x264 unparsed parameters

### ISSUE THREAD

**Issue by derek-blanchette** [donmelton/video_transcoding#310]
I want to thank Don for this project. I have been trying to understand his general approach to producing the most efficient video in terms of size and appearance. In doing so, it seemed that his approach rests on specifying boundaries and allowing the encoder to do the heavy lifting. Boundaries change based on the type of input; smart and simple! 

However, I have just completed my first run of transcode and I am confused by the log. There is a line which lists unparsed options and among these options are the bitrate max, the CRF max and the qpmax (all of which are essential, no?). Is anyone able to explain to me what is really going on here?

Thank you

[12:05:05] encx264: min-keyint: 24, keyint: 240
[12:05:05] encx264: encoding at constant RF 1.000000
**[12:05:05] encx264: unparsed options: vbv-maxrate=6000:vbv-bufsize=12000:crf-max=25:qpmax=34:level=4.0**
x264 [info]: using SAR=1/1
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX XOP FMA3 BMI1
x264 [info]: profile High, level 4.0, 4:2:0, 8-bit

**Comment by spooknik** [comment]
Hello! I also wondered about this when I started using Transcode Video, I dug this up: #26

Perfectly normal, nothing to worry about.

**Comment by derek-blanchette** [comment]
Thanks. Can I ask, did you link to the correct item? I am not sure how Dolby audio is related to unparsed advanced encoder options.

**Comment by spooknik** [comment]
Sorry, I forgot which project i was in. I linked the older git - video-transcoding-scripts. 

[You can read it here.](https://github.com/donmelton/video-transcoding-scripts/issues/26)

**Comment by derek-blanchette** [comment]
Thank you for the help!

**Comment by donmelton** [comment]
@derek-blanchette Thank you and thanks for using my tools! And thanks to @spooknik for the explanation and the links.

Yes, the `unparsed options` message to the console and the `.log` is nothing to worry about.
