### ISSUE TITLE
Location of video_transcoding and dependencies

### ISSUE THREAD

**Issue by ghender3** [donmelton/video_transcoding#313]
I've used and like your project. I know how to install it and all the dependencies. 

My question - my boot disc is a pretty small SSD. Post-install, I'd like to move video-transcode to my Mac OS home folder, which is on a 4 TB rotating HD. If I recreate the directory names and structure, move it all over and then put symlinks in my /usr/local folder, will it work? Or, could it work by moving it all into my home folder and just navigating to it in Terminal?

Got pretty excited to see your new other_video_transcoding. Alas, quickly became apparent that with Mac OS and my hardware (CPU and GPU) it's not really an option.

Thanks

**Comment by donmelton** [comment]
@ghender3 Thank you for using my tools and I'm glad they're working out for you!

I don't think it's worth moving the `video_transcoding` Gem to another disk because it's only 244K in size. That's almost a rounding error these days. Also, even if you got the symbolic link trick to work, I'm not sure how RubyGems would handle updates.

I'm sorry that `other_video_transcoding` is not an option for you. Might I ask which model of Mac you're using?

**Comment by ghender3** [comment]
It's **not** the Ruby gem I am concerned about. It's all of the other items (ffmpeg, handbrake cli, mkvtoolnix and all of their dependencies that when I type in brew install I get a long, long download - all sorts of things like tesseract, ad infinitum.  I understand about breaking updating of the ruby gem if moved.

It's a Hackintosh with an Ivy Bridge CPU and an AMD HD 7770 GPU. No nVidia.  Based on what I read, this is a less than ideal configuration for hardware encoding. Mac OS High Sierra.

**Comment by donmelton** [comment]
@ghender3 OK, don't know what to tell you about all the other dependencies then. My advice would be to check the Homebrew website to see if it can be configured to install somewhere other than `/usr/local`.

And, yeah, you are probably out of luck for hardware-based transcoding with a Hackintosh.

**Comment by ghender3** [comment]
I found that it is possible to put homebrew and all its packages in one's home folder, for example. But it's a bit tedious, and not everything is guaranteed to work all that well. So I probably won't go there. The whole works for video_transcoding is maybe 1.2 GB.

I have a new problem that perhaps you have bumped into. brew install always brings in the latest, greatest release of a package. Unfortunately, on the system where I want to use video-transcoding, that's a big problem. I'm on High Sierra, 10.13.6. brew install Handbrake CLI gives a very nasty message about requiring a version of Xcode to build it that is ONLY available in Mojave or higher. I have been going through Handbrake CLI's changelog, and I can see when that change was made.

Similar type of problem with mpv. brew install mpv **installs** mpv and all the dependencies, but any attempt to do anything with mpv gives an abort code 6 and a complaint about it not being able to find a SwiftAV dylib.  Not even mpv --help works.  I've gone through mpv's GitHub changelog, and I've also found **when** they "deprecated older versions of Swift".

I HAD video_transcoding working fine about a year ago, but did a clean install without specifically backing up that directory. I've always had homebrew work great before, didn't realize this potential outcome.

Do you have any information about how to point homebrew at a release on GitHub that WILL work?  I would certainly appreciate it.

By the way, other-video-transcoding screams on my 2012 MacBook Pro running Mojave. Somewhere around 200 fps on BluRay source material. Would you happen to know whether it is using my nVidia GPU, or my Intel HD4000?

Thanks

**Comment by ghender3** [comment]
I finally got it all working in High Sierra. The biggest problem by far was finding a way to brew install mpv. Sought help from GitHub mpv people, and was told to try brew install --HEAD mpv. Builds the binary in a different way, and it solved all of my High Sierra issues. HandbrakeCLI can no longer be done with homebrew under High Sierra, but it can be downloaded and put into an appropriate place and symlinked. 

Finally, it actually can be done with everything related to homebrew in one's user folder on a much larger volume. Homebrew has to be installed where you want it first, then you must get a path to homebrew into one's bash_profile. At least for everything related to video-transcoding, it all installs and works. Video-transcoding's gem can go where it normally installs. In the future, I will NOT assume I can get away with not backing up my homebrew directories, because brew install is so easy.
