### ISSUE TITLE
How to offset audio track?

### ISSUE THREAD

**Issue by seventhaxis** [donmelton/video_transcoding#314]
Have a file where it seems the audio track is off ever so slightly, but to me it's noticeable enough to keep from enjoying...

![](https://media.giphy.com/media/SHhUunfD9eSYURRoI4/giphy.gif)

So how do I go about offsetting the audio track? Is this something I need to pass through to Handbrake? If so, what's the syntax for that?

**Comment by donmelton** [comment]
@seventhaxis Unfortunately, HandBrake doesn't have a mechanism to offset or sync audio tracks. I don't even know of a tool for making such an adjustment. Is this file a Blu-ray or DVD rip? Or was it a gift from Uncle Torrance?

**Comment by seventhaxis** [comment]
> @seventhaxis Unfortunately, HandBrake doesn't have a mechanism to offset or sync audio tracks. I don't even know of a tool for making such an adjustment. Is this file a Blu-ray or DVD rip? Or was it a gift from Uncle Torrance?

![](http://docs.eggplantsoftware.com/ePF/using/epf-usability-mode.htm)

Uh yeah so it sounds like I might just need to find a different solution, hah!
Thanks @donmelton -- youdaman!
