### ISSUE TITLE
Alternative to (or alternative source for) mp4track (via mp4v2-utils)

### ISSUE THREAD

**Issue by carsonl** [donmelton/video_transcoding#317]
I get this isn't really your problem, Don... but I'm hoping you have some ideas.

I am running ubuntu 20.04, and they have not included mp4v2-utils (and by proxy, the tool: mp4track).

Rather than grabbing this and compiling it from source, is there an alternative tool that can be used, or a reliable way to get a compiled version for inclusion?

The software itself does seem abandoned.

**Comment by samhutchins** [comment]
You can download the 18.04 version of the `.deb` [here](https://packages.ubuntu.com/bionic/mp4v2-utils), and it might install on newer versions. I've not tested personally.

It may also be worth checking out Don's newer project [other_video_transcoding](https://github.com/donmelton/other_video_transcoding), which doesn't have this dependency (and can leverage hardware encoders for more speed!)

**Comment by donmelton** [comment]
@samhutchins Thanks! For both parts of that answer!

@carsonl Does that help?

**Comment by carsonl** [comment]
Thank you both, I'll investigate the options and go from there... I guess those older debs will be available until Bionic goes EOL...

**Comment by jhbeskow** [comment]
@donmelton @carsonl  I created a Docker image for transcode-video that packages everything up for you. https://hub.docker.com/r/jhbeskow/transcode-video
