### ISSUE TITLE
mpv syntax error in detect-crop output?

### ISSUE THREAD

**Issue by Lanthanus** [donmelton/video_transcoding#319]
I tried this tools for the first time and I must say they are great!
But when I was exploring all the options I encountered an error when I tried to inspect the output of `detect-crop`:
`Error parsing commandline option vf: option requires parameter`
popped up when using either of both commands.
For me the space in `--vf [option]` needed to be exchanged by an `=` to work properly. Was there a change in mpv syntax? I am not familiar with mpv.

Btw: Just found your other repo with the new tools. Could you could update the readme with the information in the (very good) one in this repo or at mention it for new users?

**Comment by Lanthanus** [comment]
Just saw that this is already mentioned in your other project and is fixed anyway. Sorry to bring this up again. I was not aware that there is a newer project going on when I encountered this error.

The idea to have a mostly automatic tool with gpu support is great but my computer seems to old (7 years) to support this. It seems to only run on the cpu with a speed of ~0.9. Time to buy a new machine ;-)

**Comment by donmelton** [comment]
@Lanthanus I already fixed the problem in this project, too, but I haven't made a release with that change yet. That will likely happen sometime today. Thanks.

**Comment by donmelton** [comment]
@Lanthanus OK, I have just released version 0.25.3 with the fix for this. Just `gem update` to get it. Thanks.
