### ISSUE TITLE
Of --target problems and VHS archives

### ISSUE THREAD

**Issue by sonic6567** [donmelton/video_transcoding#320]
Hello,

Is the --target capped at 12500 ?

I pass in: --target 20000
And I see: + bitrate: 20000 kbps, pass: 0
But I also see: vbv-bufsize=12500:vbv-maxrate=12500
And looking at the resulting file, the bitrate is around 12500

I am trying to do [essentially] loss-less (as much as possible) transcoding for a project I am working on.

Perhaps, a better question might be, what is recommended for saving precious memories from old VHS tapes?

With the understanding that 'perfect' is the enemy of 'good', I need to do something before the tapes are forever lost. I cannot afford a professional service (and would I trust them anyway? ). I have [oh so] many years of video work and technology in my background. I am limited in funds and have a workflow leveraging what I have now.
I capture the VHS video [essentially] uncompressed using huffyuv.
I use transcode-video (and my own personal wrapper perl scripts etc) to move that huffyuv avi to h264 m4v so that it can be edited by final cut pro x.
The source avi have a bitrate of 60,000 - 90,000. I would like to do the aforementioned transcode with a ridiculously high bitrate (ie. --target 100000) because at this phase, the point is not saving file size, but just producing compatibility.
Then after editing and exporting to prores, I would use transcode-video to bring the file size down to something reasonable (but quality is priority because might not be able to ever recapture from the source if the tapes deteriorate) - not too concerned about size so maybe - - target 20000. 
Which is where I run into the 12500 issue. 

I understand that transcode-video is focused on reducing size of quality source material, but I really like the way it works and it does an amazing job. I have used it a lot for that purpose. I can think of nothing I trust more for this project, but I want to make sure I use it as best I can. 

Any input would be greatly appreciated. 

Thank you

Ben

**Comment by samhutchins** [comment]
Why don't you edit the huffyuv file directly, and remove a lossy transcode from the process?

Failing that, I'd have thought that going from huffyuv -> h264 -> edit -> prores -> h264 is worse than say, huffyuv -> prores -> (edit) -> prores -> h264

IMO, `transcode-video` isn't really a tool best suited for intermediate files, I'd only use it for the final compression personally, and work with the highest bitrate editing codec I can get away with before that

**Comment by donmelton** [comment]
@sonic6567 Thank you for using my tools and I'm glad they work so well for you.

Archiving is not a goal of video transcoding because it is, by it's very nature, a lossy process. That said, I understand your constraints.

So let's get to the 12500 Kbps maximum bitrate issue that you're hitting...

I assume the resolution of your video input is at or below 720 pixels wide and 576 pixels high, because a bitrate of 12500 Kbps is exactly the upper limit allowed for the H.264 encoder level that I'm setting for that resolution.

Why do I set an encoder level? Mostly to maintain playback compatibility for older devices. But there are other nerdy reasons for it that I won't detail here.

The good news is that there's an easy way to disable setting the encoder level and getting the target bitrate you want. Just modify your command line to add pass an option directly to `HandBrakeCLI` like this:

```
transcode-video --target 20000 --handbrake-option _encoder-level /path/to/input.mkv
```

The underscore (`_`) before "`_encoder-level`" is very important! That's not a typo. That tells the command line parser to un-define that option.

Does that work for you?

**Comment by sonic6567** [comment]
Hello,

Wow. thank you very much for the quick reply!

@samhutchins

I agree, I do not like the lossy transcode process in the middle.
But, huffyuv is not really friendly for editing is the problem. Direct edit was my original plan, however, final cut does not support importing huffyuv. So I need to convert it first. I don't know of any other tools that can convert huffyuv to an intermediate file. (handbrake, ffmpeg, yes, but those are all the same as this) Any recommendations? huffyuv to prores would be great. or any kind of [essentially] lossless conversion to something final cut can deal with.

I could try other editors, I suppose.  I do not like virtualdub or avisynth or whatever - I use audio filters in final cut to repair and there could be future edit projects requiring more advanced tools. I could try black magic davinci resolve but i already have and use final cut and would just prefer to stick with that.

@donmelton

You are correct, the size is essentially 480i/p.
The --handbrake-option _encoder-level is great. Thank you.  That is the magic I was looking for to do something ridiculous ha ha

I understand archiving is a bit outside the scope, but I really appreciate your input and understanding of the situation. Someday [in a long distant future] budget may allow for buying pro equipment and TBC and etc but in the mean time I don't want the original tapes to disintegrate (it has been 30 years already which is well beyond the life expectancy of some of these low quality tapes)

Unless someone has other suggestions on a different flow, I really do like the results I am getting from your tool.  I appreciate the work you do. It is allowing for me to share clips with family members and spark their memory of times long past.

Besides the obvious inherent nature of a lossy flow, any other suggestions you might have for my misusing of your tool ha ha and shoe horning it into service for me?  (I looked at other-transcode but this one seems to fit for me - but no religious allegiance to one over the other)

I have spent many an hour studying the forums and man pages here and I think I have it as best as possible. But maybe if there are any other hidden options... ?  Perhaps an adjustment to the deinterlacing process used? Speed is not a concern, so in handbrake i would use eeid2; looks like this doesn't? (still great results btw)

I am as simple as this:
--avbr --m4v --audio-width all=stereo --target 20000 --handbrake-option _encoder-level

Does using hardware (--encoder vt_h264) lessen quality at all? I like the speed boost but worry.

Thank you very much

Ben

**Comment by sonic6567** [comment]
Just thought - I bet I could use the --handbrake-option and pass deinterlace options directly to handbrakecli, right?

**Comment by donmelton** [comment]
@sonic6567 That's a good set of options you've chosen.

But selecting a hardware encoder at those bitrate targets won't lessen quality so I would go ahead and use `--encoder vt_h264`.

As for using `--handbrake-option` to pass deinterlace options, I would not recommend it. Deinterlacing should be handled automatically but if it's not then I recommend using the `--filter` option to access HandBrake's various deinterlace and detelecine filters.

**Comment by sonic6567** [comment]
@donmelton 

Thank you.  It is working great. I am letting it handle deinterlacing automatically.

The input file is huffyuv at about 89000. I set the --target to 99000.
I no longer see the 12500 cap.

When I view the resulting file I see that the bitrate is right around 32000 (and layman-visually identical)
I am assuming that h264 has accomplished its mission and only needed 32000 to do it.  ie. for the given video, h264 could not be less efficient if it wanted to.
Does that sound correct?

The results are great.  Just what I was looking for so I can import and edit in final cut, dump out to prores, and have no real loss from the original capture.

Of course, after that I will use your tool with more reasonable settings to tame down the final version.

You noted that you had set the limit to 12500 for older device compatibility and other nerdy reasons. You don't have to divulge your nerdy reasons if you don't want to ha ha, (although I am curious) but is that a good bitrate to target for maximum compatibility if I want to share the final version with family members?

Thank you again for the work you have done creating the tool and your time in working with me.
Much appreciated.

Ben

**Comment by donmelton** [comment]
@sonic6567 Setting the target that high is likely to cause problems during playback on devices other than desktop-class computers. This is because even though the average bitrate was only 32000 Kbps, the _peak_ bitrate will be much higher.

I strongly recommend never setting the target above 20000 Kbps for video at that resolution. You will not see a quality difference.

If you want to share the video, I would try to keep the bitrate target as low as possible.

You are very welcome for the support. I'll close this now since the original issue is resolved, but feel fee to continue commenting here.

**Comment by sonic6567** [comment]
@donmelton Yes, for sharing, I will re-run your tool on the selected file at target 1500 (fifteen hundred) or something because it will be for a semi-ephemeral text and I will still always maintain the 20000 (twenty thousand) original.

So, academically speaking, on principal, does software or hardware encoding give better quality? For the interim flow I use hardware because you said at my goofy high bitrates (99000) there is no difference (and it has looked great so far) and it saves time going from huffyuv. For the final version at around 20000 (i am toying with 17000 maybe - i can occasionally visually detect minutely lower quality from 20000 to 15000 and lower) I have no problem with the time it takes to encode so I will let the software encoder run if, on principal, it would produce better quality. Even if it is only for my peace of mind placebo.

Is there an option for your tool to carry over meta data? ie. I add meta description and tags in final cut pro x export to prores.mov. It would be nice if those were carried over to the m4v.

thank you, yet again.
Ben

**Comment by donmelton** [comment]
@sonic6567 There are too many variables to decided on which is better, software- or hardware-based encoding. The question, as always, is what looks good to you?

There is no option in `transcode-video` to copy metadata. And that's intentional because most playback systems, such as Plex, don't need it or, worse, can be confused by it.
