### ISSUE TITLE
Dolby Pro Logic II versus AC3 -- what do you hear?

### ISSUE THREAD

**Issue by ajmicek** [donmelton/video_transcoding#328]
Hello,

I am wondering who among you is able to hear a difference between, say:

- 160kbps AAC matrix-encoded Dolby Pro Logic II mixdown of 5.1 channels
- 640kbps 5.1 AC3

If so, what do you hear? Is it in certain frequency ranges or instead changes in multi-channel separation? Both?

Obviously, the savings per film are not great here (2 hour film is about 570MB for AC3 and about 140MB for AAC), but I just wanted some opinions from those who have compared output quality more than myself. Thanks!

**Comment by donmelton** [comment]
@ajmicek I was once a big proponent of using Dolby Pro Logic II (DPL II) to save some space. But I learned that the DPL II implementation used by HandBrake and FFmpeg is flawed. And my own as well as other contributor listening tests confirmed that. One problem is correct channel separation during surround decoding. But, more importantly, tracks encoded with this software are no longer correctly balanced for simple stereo decoding. The effect is quite noticeable for some inputs.

This is why the mixdown for stereo tracks in `transcode-video` no longer defaults to DPL II.

Does that answer your questions?

**Comment by ajmicek** [comment]
Thank you! That's precisely the kind of insight I was hoping for. I had long thought DPL II was technically impressive but 'too good to be true' -- I'm surprised the issue is more problematic implementation and not an inherent limitation of the spec, but it really helps me understand the `convert-video` defaults even better...

FWIW, (for modern films), when I see a 2 channel AC3 on the source disc, I tend to put that into the *.mkv as well, so if the studio took the time to produce their own two-channel mixdown, I can capture that in the AAC stream of the final .mp4...
I may be wasting my time with that, lol.

Thanks again for your fast reply!

**Comment by donmelton** [comment]
@ajmicek You are very welcome! I'll close this now assuming the questions have been answered.
