### ISSUE TITLE
Get handbrakecli command?

### ISSUE THREAD

**Issue by vasuvasu** [donmelton/video_transcoding#331]
Is there a way to get the handbrakecli command that gets run by transcode-video? 

I used transcode-video to help a client solve an encoding problem, and now I'd like to copy/paste the handbrakecli command that gets run, but didn't see it in the logs.

Thanks for any help!

**Comment by samhutchins** [comment]
The `--dry-run` on `transcode-video` will do exactly that

**Comment by donmelton** [comment]
@samhutchins Thanks!
