### ISSUE TITLE
Create AAC tracks for multiple languages

### ISSUE THREAD

**Issue by dashrealfar** [donmelton/video_transcoding#335]
I know the default settings will create an AAC track from the default language track, but is there a way to create a second AAC track for a secondary language track? 
In other words 
Source File
Track 1: AC-3 5.1 eng
Track 2: AC-3 5.1 spa
Transcode
Track 1: AC-3 5.1 eng
Track 2: AAC stereo eng
Track 3: AC-3 5.1 spa
Track 4: AAC stereo spa

**Comment by donmelton** [comment]
@dashrealfar Yes, it's easy. To add the Spanish language audio tracks that way, use these options:

```
--add-audio spa --audio-width all=double
```

This is, BTW, all explained in the `--help` output.

Does that answer your question?

**Comment by dashrealfar** [comment]
Yes, thank you, perfectly explained. 

And apologies, I must've mis-read that part of the -help

**Comment by donmelton** [comment]
@dashrealfar No problem! I'll close this now.
