### ISSUE TITLE
Confused by multiple audio tracks

### ISSUE THREAD

**Issue by bblackmoor** [donmelton/video_transcoding#340]
(Handbrake; Windows 10)

Thank you for this software. (If I am in the wrong place, please let me know.)

I have transcoded hundreds of video files over the past few years, typically from mkv to mp4. I am confused by the multiple audio tracks. In Handbrake and VLC, I see multiple audio tracks that all have the exact same name and description. I have always seen them, and just not worried about it. Also, sometimes I think the 5.1 mix has been lost somehow -- the other channels are just missing. Again, I've just not worried about it.

But it seems to be getting more common, particularly with videos that are _supposed_ to have multiple audio tracks (commentaries, typically).

I have read that, maybe, I am seeing 2 channel audio ("stereo") and 5.1 channel audio. But nowhere do I see any indication of that being the case -- the duplicate audio tracks all have the same name. For example, "eng (English)". Or "English (Commentary)". Like that.

I am certain I am doing something wrong, but I don't see what or how. I typically use Handbrake on Windows and convert videos in queued batches.

I would be grateful for some guidance on this issue.

**Comment by donmelton** [comment]
@bblackmoor The behavior of `transcode-video` regarding audio tracks is described in the "Rationale" and "Understanding audio" sections of the README document. In short:

> When audio transcoding is required, it's done in [AAC format](https://en.wikipedia.org/wiki/Advanced_Audio_Coding) and, if the original is [multi-channel surround sound](https://en.wikipedia.org/wiki/Surround_sound), in [Dolby Digital AC-3 format](https://en.wikipedia.org/wiki/Dolby_Digital). Meaning the output can contain two tracks from the same source in different formats. And mono, stereo and surround inputs are all handled differently.

That's why you sometimes get multiple output tracks for a single input track.

Can you give me an example of the command line options you're using for a particular input track?

**Comment by bblackmoor** [comment]
Ah, I see. I will have to read up more about this if I want to change what is happening now. Thank you.

**Comment by donmelton** [comment]
@bblackmoor BTW, you might want to try my other video transcoding project, cleverly called "Other Video Transcoding," here:

https://github.com/donmelton/other_video_transcoding

The `other-transcode` tool does not duplicate main audio tracks by default. That project is also in active development.

**Comment by bblackmoor** [comment]
Thank you, I will.

**Comment by donmelton** [comment]
@bblackmoor OK, I will close this now then.
