### ISSUE TITLE
mpv not recognized

### ISSUE THREAD

**Issue by bolognasammich** [donmelton/video_transcoding#342]
Hello,

I can not get command prompt or powershell to recognize mpv. When typing in
"C:\Users\me>mpv --version"
This is what happens.
"
C:\Users\me>"

I just get a blank and new command line. The exe file is in the bin folder with the other exe files that work.

Any help is appreciated.

**Comment by donmelton** [comment]
Sorry that this happened to you. The `mpv.exe` executable also requires that the `mpv.com` file be in the same directory to work. Just make sure both are in your `bin` directory.

**Comment by bolognasammich** [comment]
That worked!! Thank you so much!
