### ISSUE TITLE
MacPorts has all the required support packages too

### ISSUE THREAD

**Issue by chrisridd** [donmelton/video_transcoding#38]
With almost the same package names as homebrew, so this works:

```
port install ffmpeg
port install mkvtoolnix
port install mp4v2
port install mpv
```

Apparently `mplayer2` is obsolete and replaced with `mpv`. To be honest I don't have either installed and just use VLC / QuickTime Player.

**Comment by donmelton** [comment]
@chrisridd Unfortunately, `mplayer` is required by my `detect-crop` tool. And the `mpv` package can't replace it because the developers removed the crop detection functionality.

Unless MacPorts decides to add `mplayer` back, I can't really do anything about this.

But thanks for the information.

**Comment by chrisridd** [comment]
Thanks for explaining why mplayer was needed!

MacPorts also has the "mplayer-devel" package which accepts the cropdetect argument and seems to work OK with detect-crop.

```
port install ffmpeg
port install mkvtoolnix
port install mp4v2
port install mplayer-devel
```

**Comment by donmelton** [comment]
@chrisridd You are very welcome. Sorry that I missed your comment the other day.

That's good to know about MacPorts. I may add that to the README then. Thanks!
