### ISSUE TITLE
No-hands-batch

### ISSUE THREAD

**Issue by frankeman90** [donmelton/video_transcoding#40]
I am trying to set up a batch to convert files without any involvment from my side (om my server).

Would like to use your workflow, but my knowledge in scripting does not reach this far (have spent many hours googling to try and solve this, but with no luck).

I am using Hazel, and I guess it is kind of easy to adapt the workflow *(if I only knew how).* 

What I would like to accomplish is to put videofiles (avi, mkv, video_ts) in one folder and trigger your scripts. 

**Here is the Hazel documentation:**
Using Hazel's "Passes shell script" condition or "Run shell script" action, you can have Hazel run shell scripts or trigger any external command-line program. Some important points about running scripts/programs with Hazel:

Hazel will pass one argument which is the path of the file being processed.
The program/script can be written in any language (including Perl and Python) as long as you tell Hazel which shell/interpreter to use.

Embeded vs. External
Hazel can run scripts in one of two ways: embedded or external.

When running an embedded script, you can enter the script using Hazel's built-in editor. Here you can also specify the shell/interpreter to use (sh, perl, python, etc). Embedded scripts are stored with your rules and therefore do not need to be exported/imported separately when transferring your rules.

When using an external script, you can have Hazel trigger a script/program already on your disk. The program must be executable. If it is a script, it should start with a sha-bang (#!) line to indicate which interpreter to use. When transferring rules between machines, the scripts must be transferred separately.

Using shellscripts for use in a rule condition
When using scripts in a rule condition, the script should exit with a 0 status to indicate that the file passes the condition. Any other exit status will tell Hazel that the file does not match the condition.
Since rule conditions tend to be evaluated many times, you should make sure the scripts runs quickly. Time consuming scripts will greatly affect performance.
The script must not modify any files or folders underneath the folder Hazel is monitoring as it can result in a loop where Hazel never stops processing the folder.

Using shellscripts for use in a rule action
When using scripts via the "Run shell script" action, the script should return 0 to indicate that the action was performed successfully. Any other value indicates an error and the rule will be re-executed until the action proceeds successfully.*

**Comment by donmelton** [comment]
@frankeman90 I'm sorry but I've never used Hazel so I have no idea how it works (despite that handy documentation you pasted in) or what its limitations are. Without a sample shell script from Hazel, I wouldn't know how to advise you.

On the other hand, I know for certain that the batch control script for `transcode-video` here:

https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video

...works fine since I use a variation of that myself.

Do you have a Twitter account? I can ask on Twitter for you and perhaps one of my followers or someone else is already using Hazel with `transcode-video` out there.

**Comment by frankeman90** [comment]
Sure im on twitter as @fransholm
- thanks for your efforts!

I will look into the link you posted aswell!

/Andreas




On Mon, Jan 18, 2016 at 9:02 AM -0800, "Don Melton" <notifications@github.com<mailto:notifications@github.com>> wrote:


@frankeman90<https://github.com/frankeman90> I'm sorry but I've never used Hazel so I have no idea how it works (despite that handy documentation you pasted in) or what its limitations are. Without a sample shell script from Hazel, I wouldn't know how to advise you.

On the other hand, I know for certain that the batch control script for transcode-video here:

https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video

...works fine since I use a variation of that myself.

Do you have a Twitter account? I can ask on Twitter for you and perhaps one of my followers or someone else is already using Hazel with transcode-video out there.

-

**Comment by platonium** [comment]
Hi, Don,

Want to thank you so much for providing these wonderful tools.  I'm not techy so just lurk for the most part.  However, this link might help for batch processing:

https://github.com/alextall/Transcode . Haven't used it since I don't have Hazel.

Best,
Plato

**Comment by donmelton** [comment]
@frankeman90 Thanks. Tweeted. Let me know how it goes.

@platonium Thanks for the link. I didn't even know about that.

OK, I'm closing this issue for now.

**Comment by frankeman90** [comment]
Thanks Don!

Getting closer with Hazel :-) I will keep you posted and send screenshots when all is finished!

@Platonium have made som changes to the original script and I dont fully understand where to put my arguments

I would like to add
• All subtitles and if that doesn’t work add Swedish or English subtitles.
• Add all language files (audio) and if that doesnt work Swedish or English

And a silly question – I understand that the transcode-video.sh file should be placed in /usr/local/bin, is there an easy terminal-command that I can use to move the file from downloads to the right place?

Sorry for newbie questions - but this is fascinating and I am trying to learn more and more.

/Andreas



#!/bin/bash
#
# transcode-batch.sh
#
# Copyright (c) 2015 Alex Du Bois
#

about() {
cat <<EOF
$program 1.0 of February 8, 2015
Copyright (c) 2015 Alex Du Bois
EOF
exit 0
}

usage_prologue(){
cat <<EOF
Batch transcode video files using transcode-video.sh. Works best with Blu-ray or DVD rips.
Transcode-video.sh automatically determines target video bitrate, number of audio tracks, etc. WITHOUT ANY command line options.
It is recommended to use Hazel to provide automated queue management and trigger transcode-batch.sh.
Usage: $program [OPTION]... [FILE|DIRECTORY]
--help          display basic options and exit
EOF
}

usage() {
usage_prologue
cat <<EOF
EOF
exit 0
}

readonly program="$(basename "$0")"

# OPTIONS
#
case $1 in
--help)
usage
;;
--version)
about
;;
esac

syntax_error() {
echo "$program: $1" >&2
echo "Try \`$program --help\` for more information." >&2
exit 1
}

die() {
echo "$program: $1" >&2
exit ${2:-1}
}

# Set global variables
#
readonly input="$1"
readonly title_name="$(basename "$1" | sed 's/\.[^.]*$//')"
readonly base_name=`echo $title_name | sed 's/_[^_]*$//'`
readonly crop_dir="_crops/$base_name"
readonly crop_file="$crop_dir/${title_name}.txt"
readonly originals_dir="_originals/$base_name"
readonly finals_dir="_finals/$base_name"
readonly logs_dir="_logs/$base_name"

if [ ! "$input" ]; then
syntax_error 'too few arguments'
fi

if [ ! -e "$input" ]; then
die "input not found: $input"
fi

## Run crop detection and save output to file
#
if [ ! -d $crop_dir ]; then
mkdir $crop_dir
fi

detect-crop.sh $1 &> $crop_file

if [[ -f "$crop_file" ]] && [[ `grep identical $crop_file` ]]; then
crop_option="--crop `grep transcode-video $crop_file | egrep -o [0-9]+:[0-9]+:[0-9]+:[0-9]+`"
else
crop_option=''
fi

# Detect audio streams
#
audio_streams=`ffmpeg -i $input 2>&1 | grep -c Audio:`

if [ "$audio_streams" -gt 1 ]; then
  for i in `seq 1 $audio_streams`; do
audio_options="$audio_options --add-audio $i"
  done
else
  audio_options=''
fi

# Detect subtitles
#
subtitle_streams=`ffmpeg -i $input 2>&1 | grep -v pgs | grep -c Subtitle:`

if [ "$subtitle_streams" -gt 0 ]; then
  for i in `seq 1 $subtitle_streams`; do
subtitle_options="$subtitle_options --add-subtitle $i"
  done
else
  subtitle_options=''
fi

# Begin transcode operation
#
transcode-video.sh --allow-ac3 $audio_options $crop_option $input

# Clean up source and generated files
#
if [ ! -d "$originals_dir" ]; then
  mkdir "$originals_dir"
fi
mv $input "$originals_dir"

if [ ! -d "$logs_dir" ]; then
  mkdir "$logs_dir"
fi
mv "$title_name.mp4.log" "$logs_dir"

if [ ! -d "$finals_dir" ]; then
  mkdir "$finals_dir"
fi
mv "$title_name.mp4" "$finals_dir”



Från: Don Melton <notifications@github.com<mailto:notifications@github.com>>
Svara till: donmelton/video_transcoding <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: måndag 18 januari 2016 21:17
Till: donmelton/video_transcoding <video_transcoding@noreply.github.com<mailto:video_transcoding@noreply.github.com>>
Kopia: frankeman90 <andreas.fransholm@gmail.com<mailto:andreas.fransholm@gmail.com>>
Ämne: Re: [video_transcoding] No-hands-batch (#40)


@frankeman90<https://github.com/frankeman90> Thanks. Tweeted. Let me know how it goes.

@platonium<https://github.com/platonium> Thanks for the link. I didn't even know about that.

OK, I'm closing this issue for now.

**Comment by platonium** [comment]
@frankeman90, sorry wish I knew more - good luck and look forward to your success.

@Don, you are most welcome!

**Comment by methodphoto** [comment]
cp /path/to/file/transcode-video.sh /usr/local/bin/

Or you can use mv instead of cp (move/rename instead of copy) if you do you need

mv /path/to/file/transcode-video.sh /usr/local/bin/transcode-video.sh

Or 
open /usr/local/bin/ 

Then drag the script in the folder.

If it doesn't work you might need to change permissions

chmod 755 /usr/local/bin/transcode-video.sh

For the first part, drag the file from where it exists in the finder into the Terminal window after you have typed cp and it completes the path.

If you get the Hazel script running make sure you publish it.

Richard
