### ISSUE TITLE
Hazel needs fulls paths for the script to work

### ISSUE THREAD

**Issue by frankeman90** [donmelton/video_transcoding#42]
**BACKGROUND**
I am getting closer building a full hands-off solution to convert movie files with 
*Drop in one folder, Hazel transcodes, adds subtitles and more ... final movie lands in Plex without any interaction.*

I tell Hazel to run shell script on folder contens with below rule:
**transcode-video --quick --add-all-subtitles --add-audio all --m4v "$1"**

At first look it seems to work. But I have found out that it is unstable end often ends up with errors. After some googling I found out that:
**The which command does not function as expected within a Hazel shell. What does is simply specifying the actual path of each binary and adding an exception to the checkdep function.**

I have tried but my knowledge in shell is limited and I am unsure how to get this to work. 

I know that I must change above rule in  Hazel to
**/usr/local/bin/transcode-video --quick --add-all-subtitles --add-audio all --m4v "$1"**

<img width="663" alt="skarmavbild 2016-01-23 kl 08 27 22" src="https://cloud.githubusercontent.com/assets/16753542/12529143/388df150-c1ae-11e5-8420-3084b264f8a9.png">

**QUESTIONS**
1. How do I change all the paths in the transcode-video to *full paths* (eg usr/local/bin/XXXX)
2. Is it possible to tell the script to trash the original file if the conversion was successfull and delete the converted .mv4 file if the script was unsuccesful. Needed because this is a hands-off solution and I dont want unsuccessfully transcoded movies to show up in Plex, then I would rather take the original file. 

**FORUM-THREAD TALKING ABOUT HAZEL AND SHELL SCRIPTS**
http://www.noodlesoft.com/forums/viewtopic.php?f=4&t=1942&p=8096#p8096

Will post the whole process and get you a link when I get this to work!

**Comment by alextall** [comment]
@frankeman90 You can avoid using full paths by setting your path with the line below.

```bash
PATH="/usr/local/bin:$PATH"
```

For your next question, you can use `transcode-video`'s exit code. You could try…

```bash
if [ $? == 0 ]; then
# handle successful transcode
else
# handle unsuccessful
fi
```

… below your transcode operation. I would recommend exercising caution with this, however. I like to check my files by hand before deleting anything.

**Comment by donmelton** [comment]
@frankeman90 Did @alextall answer your question sufficiently? (He knows much more about Hazel than I do.) If so, I'd like to close this issue. Thanks.

**Comment by frankeman90** [comment]
Yep! Solved thanks!

Andreas Fransholm





On Fri, Mar 11, 2016 at 6:29 PM -0800, "Don Melton" <notifications@github.com<mailto:notifications@github.com>> wrote:


@frankeman90<https://github.com/frankeman90> Did @alextall<https://github.com/alextall> answer your question sufficiently? (He knows much more about Hazel than I do.) If so, I'd like to close this issue. Thanks.

-
