### ISSUE TITLE
Chapter names not working with HandBrake nightly builds

### ISSUE THREAD

**Issue by martinpickett** [donmelton/video_transcoding#44]
Using version 5.0 of the transcode video script I've been unable to get the --chapter-names option to work. Attached is a .txt version of the chapter names file I was using (I know it needs to be .csv but GitHub wouldn't accept an upload in that format). Also attached is the resultant log file (again in .txt rather than .log).

[GDT.txt](https://github.com/donmelton/video_transcoding/files/120336/GDT.txt)
[The Girl With The Dragon Tattoo.mkv.txt](https://github.com/donmelton/video_transcoding/files/120338/The.Girl.With.The.Dragon.Tattoo.mkv.txt)

I've previously used the bash version of your script and had little issue with chapter names.

**Comment by donmelton** [comment]
@martinpickett You appear to be using `HandBrake 20160124175113-554e833-master (2016012501)` which is a nightly build. Can you try this again with HandBrake version 0.10.3, the stable release?

**Comment by martinpickett** [comment]
That appears to have fixed it. I had forgotten I was using a nightly.

**Comment by donmelton** [comment]
@martinpickett OK, but that still means there's a bug in the HandBrake nightly builds or a change to their API that's causing trouble for `transcode-video`. I'll changed the title of this issue to reflect that and leave it open while I investigate. Thanks again for finding this.

**Comment by donmelton** [comment]
@martinpickett I just confirmed that this is still broken in `HandBrake 20160310191238-d553529-master`, today's build. It appears to be a bug in HandBrake itself. And `transcode-video` is working correctly since the HandBrake team did not change the API.

Please open an issue with the HandBrake team at:

https://github.com/HandBrake/HandBrake/issues

Thanks.
