### ISSUE TITLE
Query-Handbrake-Log showing incorrect time

### ISSUE THREAD

**Issue by martinpickett** [donmelton/video_transcoding#45]
When i run "query-handbrake-log time" (version 5.0) I get a time of 00:00:00 which is clearly incorrect. The other three commands (s, b and r) work correctly. Attached is an example log file.

[MIB chapter 11.mkv.txt](https://github.com/donmelton/video_transcoding/files/126749/MIB.chapter.11.mkv.txt)

**Comment by donmelton** [comment]
@martinpickett The `query-handbrake-log` tool only works for `.log` files from complete transcoding sessions when using the `time` and `speed` information types. In other words, it won't give valid results for a partial (chapter, time range or frame range) or early-terminated transcoding. I'll add a note to the documentation about that.
