### ISSUE TITLE
query-handbrake-log reports wrong time and speed when parsing logs with subtitle scan mode data

### ISSUE THREAD

**Issue by martinpickett** [donmelton/video_transcoding#46]
This is a separate issue to that described in https://github.com/donmelton/video_transcoding/issues/45.

When using the "--burn-subtitle scan" command from transcode-video, the resultant log file produces incorrect value for speed when processed with query-handbrake-log. Attached below are two log files produced from encoding the same file with identical setting except one uses "--burn-subtitle scan" and the other doesn't. You should see 21.032848 fps from one log and 0.0 fps from the other.

[MIB chapter 11.mkv.txt](https://github.com/donmelton/video_transcoding/files/126767/MIB.chapter.11.mkv.txt)
[MIB chapter 11 Subtitles.mkv.txt](https://github.com/donmelton/video_transcoding/files/126768/MIB.chapter.11.Subtitles.mkv.txt)

P.S. You'll also notice the same issue as described in https://github.com/donmelton/video_transcoding/issues/45 affecting both log files, although the one produced with "--burn-subtitle scan" reports the time as NaN rather than 00:00:00.

**Comment by donmelton** [comment]
@martinpickett Although the is a separate issue to what's describe in #45, it's the same problem or limitation. When using time and speed information types, the `query-handbrake-log` tool won't give valid results for a partial (chapter, time range or frame range) or early-terminated transcoding. Sorry about that.

**Comment by martinpickett** [comment]
Attached is the log from a full encode with `--burn-subtitle scan`. I'm getting the same error when using the `speed` keyword. 

[MIB Subtitles.mkv.txt](https://github.com/donmelton/video_transcoding/files/127181/MIB.Subtitles.mkv.txt)

**Comment by donmelton** [comment]
@martinpickett OK, I see why this doesn't work. Unfortunately, It's another limitation. However, this time it's due to using Handbrake's "scan" mode since it fills the `.log` file with what looks like duplicate data. I may be able to handle this case in the future so I'll leave this open while I investigate.

BTW, this is yet another reason I don't like Handbrake's "scan" mode. Besides being unreliable and slow, you get silly side effects like this.

**Comment by martinpickett** [comment]
Thank you, and I'm sorry to have caused you so much trouble.

**Comment by donmelton** [comment]
@martinpickett No trouble at all! It's good to find out these issues. Thanks for opening it.

**Comment by donmelton** [comment]
@martinpickett Sorry this took so long to fix. Turns out the change was trivial:

```
diff --git a/bin/query-handbrake-log b/bin/query-handbrake-log
index 2722370..0eeb66d 100755
--- a/bin/query-handbrake-log
+++ b/bin/query-handbrake-log
@@ -132,7 +132,11 @@ HERE
               if fps_line.nil?
                 fps_line = line
               elsif fps_line_2.nil?
-                fps_line_2 = line
+                if fps_line =~ / ([0.]+) fps$/
+                  fps_line = line
+                else
+                  fps_line_2 = line
+                end
               end
             end

```

I need to do some more testing, but this should go out with version 0.8.1 sometime this week.

**Comment by donmelton** [comment]
@martinpickett OK, version 0.8.1 was just released with this fix. Just `gem update video_transcoding` to get it. Thanks, again!
