### ISSUE TITLE
Need help automating on windows 10

### ISSUE THREAD

**Issue by HolySorcerer** [donmelton/video_transcoding#48]
Sorry if this is the wrong place for this, but my scripting experience is near zero and I figured who better to help automate this than the author.

So I'm just trying to set up a simple script where the transcoder will run on a schedule, search an input directory for .mkv files, transcode them to an output directory, and then delete the original files.  I'm just looking for a simple setup for the mother in laws HTPC.  I'm trying to take most of the effort out of her ripping her dvd collection.

Thank you for your assistance.

**Comment by donmelton** [comment]
@HolySorcerer No, this is the right place to ask that question. Unfortunately, I have no (recent) experience in automation on Windows. Sorry about that. But I'll post a tween to this issue on Twitter and see if anyone else can make useful suggestions.

**Comment by HolySorcerer** [comment]
Is it possible to automate this in Ruby and just execute the Ruby file, either manually or on a schedule?

**Comment by donmelton** [comment]
@HolySorcerer Yes, you can certainly write the automation script in Ruby. And you could base that on this batch control script I wrote in Bash: https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video

**Comment by HolySorcerer** [comment]
So now I guess I have to go and learn Ruby (and scripting in general). 

Is there a reason why your transcode script won't take files with spaces in their names?  Can Ruby not handle spaces?

**Comment by donmelton** [comment]
@HolySorcerer I'm not sure what you mean. Almost all of the videos I transcode have spaces within their filenames. This has never been a problem. Are you properly quoting the the filename inputs?

**Comment by chucker** [comment]
Don't have a Ruby environment on Windows here, so I haven't tested it, but a PowerShell script like this should get you started:

```
Set-Location "Downloads"

foreach ($file in Get-ChildItem *.mkv)
{
    & transcode-video "$file"

    Remove-Item "$file"
}
```

Save it as a `.ps1` using a text editor or e.g. PowerShell ISE.

Then, use Task Scheduler and call the script using `powershell.exe -File %userprofile%\path\to\your\file.ps1`.

**Comment by sashkab** [comment]
Install [Cygwin](http://cygwin.org), then open Cygwin terminal and do some bash scripting:

```
for i in /path/to/files/*mkv; do 
  b=$(basename .mkv)
  transcode-video ${i} -o outdir/${b}.mp4
  # you might want to check exit code here
  mv ${i}{,_transcoded}
done
```

Note about `mv`:   you don't want to delete, but you want to rename it in order to avoid data loss in case something went wrong. 

Note, that for cygwin, drive `C:` will be `/cygdrive/c/`, etc.

**Comment by donmelton** [comment]
@chucker That's great, thanks! One of these days I'll have to learn PowerShell.

**Comment by donmelton** [comment]
@sashkab D'oh! I completely forgot about Cygwin. Good suggestion. Thanks!

**Comment by HolySorcerer** [comment]
I will have to play around with these and see if I can get them working. Unfortunately I don't have any scripting experience, so this is kind of a trial by fire.

**Comment by HolySorcerer** [comment]
Okay, I've tried both Powershell and cygwin without any luck.  Here's what I'm running.

>
for i in /cygdrive/c/media/transcoding/input/*mkv; do
	b=$(basename "${i}" .mkv)
	transcode-video "${i}" -o "/cygdrive/c/media/transcoding/output/${b}.mkv"
	mv "${i}"{,_transcoded}
done
> 

started with this batch file

>c:\cygwin64\bin\bash c:\media\transcoding\transcode.bash

And here's what I get when I run it.

>Jennifer@MediaPC ~
$ /cygdrive/c/media/transcoding/transcode.bash
/cygdrive/c/media/transcoding/transcode.bash: line 1: syntax error near unexpect            ed token `$'do\r''
/cygdrive/c/media/transcoding/transcode.bash: line 1: `for i in /cygdrive/c/medi            '/transcoding/input/*mkv; do


Sorry for the poor formatting.  I'm new to github and am not familiar with it yet.

**Comment by HolySorcerer** [comment]
Oh, and here is the errors that I get trying to run the powershell commands.

> At line:1 char:4
+ for each ($file in Get-ChildItem *.mkv)
+    ~
Missing opening '(' after keyword 'for'.
At line:1 char:17
+ for each ($file in Get-ChildItem *.mkv)
+                 ~~
Unexpected token 'in' in expression or statement.
At line:1 char:16
+ for each ($file in Get-ChildItem *.mkv)
+                ~
Missing closing ')' in expression.
At line:1 char:39
+ for each ($file in Get-ChildItem *.mkv)
+                                       ~
Unexpected token ')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingOpenParenthesisAfterKeyword

**Comment by JamesWTruher** [comment]
it looks like there's a space between 'for' and 'each' in your example:
foreach ( $file in Get-Childitem *.mkv ) {
  
}
PowerShell has both for and foreach keywords:
```
for($I = 0; $I -lt 10; $I++ ) { $I }
```
or
```
foreach($I in 1..10) { $I }
```

**Comment by HolySorcerer** [comment]
Well we're getting closer.  The script ran without errors after removing that space, of course it didn't encode anything, it just erased every .mkv file from the input directory.  I'm thinking that ruby has to be called or activated before trying to run the transcode-video script from powershell.

**Comment by vszakats** [comment]
If settling on a shell script, Busybox for Windows might a more compact (and much less foreign) environment than Cygwin: https://frippery.org/busybox/ (440kB single .exe)

**Comment by HolySorcerer** [comment]
Well I might have the powershell script working.  Its currently encoding a film.  I'll have to give it a test with multiple files in the directory, but it looks promising so far.

Thanks for you patience with me on this.  I haven't had scripting in school yet, so I'm just trying to fumble my way through this.

**Comment by chucker** [comment]
Yeah, you probably want to wrap the Remove-Item call in a condition:

```
if ($LASTEXITCODE -eq 0)
{
  Remove-Item "$file"
 }
```

**Comment by donmelton** [comment]
@HolySorcerer Did your PowerShell script work? If so, I'd like to close this issue. Thanks.

**Comment by HolySorcerer** [comment]
Yup, got everything up and running.  Thanks for the help guys!
