### ISSUE TITLE
Feature Request: option to delete original after successful transcode/convert?

### ISSUE THREAD

**Issue by gingerbeardman** [donmelton/video_transcoding#49]
I often convert mkv to mp4 and then have to manually delete the originals.

It'd be nice if I could just specify --deleteafterwards or something?

Perhaps a bit risky for some, but I like to live dangerously.

Thanks for your consideration!

**Comment by donmelton** [comment]
@gingerbeardman That is _way_ too risky. :) I'm sorry, but implementing this is not something I will ever do. What you want is much better done in your own batch script.

**Comment by gingerbeardman** [comment]
Have done so. Thanks though!

**Comment by donmelton** [comment]
@gingerbeardman It never hurts to ask. :)
