### ISSUE TITLE
MPEG-TS, subtitles and Video Transcoding

### ISSUE THREAD

**Issue by BBagger** [donmelton/video_transcoding#50]
I live in a country where English is a foreign language and movies are 
not dubbed so it is important to be able to preserve the subtitles in videos when editing or transcoding.

I have a lot of videos (mostly movies) which have been recorded on either my DVB-S or my DVB-T receiver. In both cases the stored recording is a straight dump of the transport stream received. So far I have not found any program that can convert the transport stream to anything that an editor or a transcoding program will handle and still preserve the subtitles.

Your excellent Video Transcoding suite of scripts seems to be my best possibility so far. The scripts work beautifully when working with e.g. videos ripped from a DVD. Unfortunately I have been unable to make it work for MPEG-TSs. I have a 7 minute recording I use for all my trials. Running it through 'mediainfo' I get the following:

> General
> ID                                       : 1002 (0x3EA)
> Complete name                            : Kristendommens historie.ts
> Format                                   : MPEG-TS
> File size                                : 120 MiB
> Duration                                 : 7mn 29s
> Overall bit rate mode                    : Variable
> Overall bit rate                         : 2 233 Kbps
> 
> Video
> ID                                       : 2111 (0x83F)
> Menu ID                                  : 1 (0x1)
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L3.0
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 3 frames
> Codec ID                                 : 27
> Duration                                 : 7mn 29s
> Width                                    : 704 pixels
> Height                                   : 576 pixels
> Display aspect ratio                     : 16:9
> Frame rate                               : 25.000 fps
> Standard                                 : PAL
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : MBAFF
> Color primaries                          : BT.601 NTSC
> Transfer characteristics                 : BT.601
> Matrix coefficients                      : BT.601
> 
> Audio
> ID                                       : 2121 (0x849)
> Menu ID                                  : 1 (0x1)
> Format                                   : AAC
> Format/Info                              : Advanced Audio Codec
> Format profile                           : LC
> Muxing mode                              : LATM
> Codec ID                                 : 17
> Duration                                 : 7mn 29s
> Bit rate mode                            : Variable
> Channel(s)                               : 2 channels
> Channel positions                        : Front: L R
> Sampling rate                            : 48.0 KHz
> Compression mode                         : Lossy
> Delay relative to video                  : -907ms
> Language                                 : Danish
> 
> Text #1
> ID                                       : 2031 (0x7EF)-104
> Menu ID                                  : 1 (0x1)
> Format                                   : Teletext
> Language                                 : Danish
> 
> Text #2
> ID                                       : 2135 (0x857)
> Menu ID                                  : 1 (0x1)
> Format                                   : DVB Subtitle
> Codec ID                                 : 6
> Duration                                 : 7mn 25s
> Delay relative to video                  : 3s 878ms
> Language                                 : Danish
> 
> Text #3
> ID                                       : 2136 (0x858)
> Menu ID                                  : 1 (0x1)
> Format                                   : DVB Subtitle
> Codec ID                                 : 6
> Duration                                 : 7mn 25s
> Delay relative to video                  : 3s 878ms
> Language                                 : Danish
> 
> Menu
> ID                                       : 2100 (0x834)
> Menu ID                                  : 1 (0x1)
> Duration                                 : 7mn 29s
> List                                     : 90 (0x5A) () / 91 (0x5B) () / 2031 (0x7EF) () / 2111 (0x83F) (AVC) / 2121 (0x849) (AAC, Danish) / 2135 (0x857) (DVB Subtitle, Danish) / 2136 (0x858) (DVB Subtitle, Danish)
> Language                                 :  /  /  /  / Danish / Danish / Danish

(the title of the video is Danish for 'The History of Christianity')

However, running the video through 'transcode-video –scan' I get this:

`

> + title 1:
>   + stream: Kristendommens historie.ts
>   + duration: 00:07:24
>   + size: 704x576, pixel aspect: 16/11, display aspect: 1.78, 25.000 fps
>   + chapters:
>     + 1: cells 0->0, 0 blocks, duration 00:07:24
>   + audio tracks:
>     + 1, Dansk (LC) (2.0 ch) (iso639-2: dan)
>   + subtitle tracks:

`
Is there any possiblity to make transcode-video handle subtitle tracks in a MPEG-TS?

**Comment by donmelton** [comment]
@BBagger Sorry I took so long to reply. I've been traveling. Unfortunately, my `transcode-video` tool is at the mercy of whatever HandBrake itself can recognize as a subtitle since it uses `HandBrakeCLI` to both scan and transcode.

Have you tried opening your video file with the HandBrake GUI app yet? Does it recognize the teletext subtitle?

BTW, thanks for the detailed issue.

**Comment by BBagger** [comment]
@donmelton Thanks for the quick reply. I did a search on the Handbrake forum and it appears that this has been more or less settles years ago [https://forum.handbrake.fr/viewtopic.php?f=6&t=18923&p=87024&hilit=mpeg+ts+DVB+S+subtitle#p87024](url), especially this post: 

> Re: No support to read subtitles from MPEG-TS files?
> 
>     Quote
> 
> Postby Rodeo » Mon Dec 06, 2010 6:32 pm
> HandBrake doesn't support subtitles from MPEG-TS or non-DVD MPEG-PS sources. It supports the following:
> 
>     VOBSUB (DVD) subtitles from DVD file structures, MP4 and MKV files
> 
>     Closed Captions from MPEG-2 sources (regardless of container, AFAIK)
> 
>     TX3G subtitles from MP4 files
> 
>     UTF-8 and SSA subtitles from MKV files
> 

Later in the post there are references to ProjectX, which I also have seen mentioned elsewhere, so I'll try my luck there.

Again, thank for your quick reply.

**Comment by donmelton** [comment]
@BBagger Thanks for doing that research! I'll close this for now then.
