### ISSUE TITLE
Trouble Selecting Titles Other Than 1

### ISSUE THREAD

**Issue by AwesomeAndy** [donmelton/video_transcoding#52]
Hi Don.  Thank you for all the work you've put into these scripts.  They've been very useful to me.

I had been using the bash scripts for a while and never had any trouble with titles.  I've switched to the ruby scripts and can't get the script to use a title other than title 1 when transcoding an .iso file.  I keep getting an "invalid title index" message.

For instance, I try the following to transcode title 3:
`# transcode-video --title 3 pending/movie.iso`
`/usr/local/bin/transcode-video: invalid title index: 3`
`Try /usr/local/bin/transcode-video --help for more information.`

If I use HandBrakeCLI to scan the file for titles, it shows that title #3 is present (see attached HandBrakeScanLog.txt).

[HandBrakeScanLog.txt](https://github.com/donmelton/video_transcoding/files/164119/HandBrakeScanLog.txt)

If I go back to the old bash script and specify title 3, it transcodes fine.  Is there something I doing wrong with the syntax for the ruby version of the script?

Thanks much!

**Comment by donmelton** [comment]
@AwesomeAndy I notice you're using a nightly build of HandBrake. Can you try again with the official release build, version 0.10.5, while I investigate this more? Thanks.

**Comment by AwesomeAndy** [comment]
I did try it with a 0.10.2 release build and ran into the same issue.  I'll work on compiling the 0.10.5 release and try it with that.  Thank you.

**Comment by donmelton** [comment]
@AwesomeAndy If you get the same error with version 0.10.2, you probably won't see any difference with 0.10.5. The bug is likely on my end.

Next test: Can you try mounting the `.iso` file as a volume and try scanning the directory at the mount point?

**Comment by AwesomeAndy** [comment]
Thanks for your help, @donmelton .  Mounting the `.iso` and using the directory seems to work:

```
# mount movie.iso /media/dvd
mount: /dev/loop0 is write-protected, mounting read-only
# transcode-video --scan /media/dvd
+ title 3:
  + Main Feature
  + vts 1, ttn 3, cells 0->44 (600105 blocks)
  + duration: 01:07:12
  + size: 352x480, pixel aspect: 20/11, display aspect: 1.33, 29.970 fps
  + chapters:
    + 1: cells 0->1, 27327 blocks, duration 00:03:45
    + 2: cells 2->4, 44365 blocks, duration 00:05:00
    ...
```

Unless there's another way around this, I can simply mount the `.iso` files, transcode from the mountpoint, and then unmount them.

**Comment by donmelton** [comment]
@AwesomeAndy Great! For now, that's what I would recommend. But I'll continue to work on this because I think it could be a bug.

**Comment by donmelton** [comment]
@AwesomeAndy See my comments in pull request https://github.com/donmelton/video_transcoding/pull/21.

I think mounting ISO image files rather than using them as direct input really is the correct solution. And I'm glad that's working for you.
