### ISSUE TITLE
Detect-crop fails on windows

### ISSUE THREAD

**Issue by CallumKerrEdwards** [donmelton/video_transcoding#6]
## Description

When running detect-crop on any file, nothing happens except the below error:

    detect-crop: mplayer version unknown

Likely to be another passing issue on windows? For reference my mplayer versions is

    MPlayer Redxii-SVN-r37378-4.9.2 (i686)

## Environment 

* Script Version: 0.1.1
* Handbrake CLI version: Latest stable version 0.10.1 (2015030800)
* OS: Win7 x64 Service Pack 1
* Cygwin version: 2.0.1(0.287/5/3)
* Ruby version: ruby 2.0.0p598 (2014-11-13) [x86_64-cygwin]

**Comment by donmelton** [comment]
@CallumKerrEdwards Thanks for the output of your MPlayer version. That's the bug, all right. I'll need to special case for that but I'm not sure how yet.

This may actually take a few days since I may be away. Sorry about that.

**Comment by donmelton** [comment]
@CallumKerrEdwards Stupid question: where did you get your copy of MPlayer? Did you download or did you build it in Cygwin?

**Comment by CallumKerrEdwards** [comment]
I built it myself, I *think*. It was a while ago, and I know I had to build one of the dependencies myself.

**Comment by donmelton** [comment]
@CallumKerrEdwards Looks like it doesn't matter if you download it or build it. Most of the binaries for Windows have that weird version format. Oh well.

**Comment by donmelton** [comment]
Here's the version I just downloaded:

    MPlayer sherpya-r37368+g52f2adc-4.9.2 (C) 2000-2015 MPlayer Team

**Comment by donmelton** [comment]
OK, I've got a fix. It works on OS X and it should work on Windows, too. I'll check it in shortly and re-release the Gem. Stay tuned...

**Comment by CallumKerrEdwards** [comment]
@donmelton you are fantastic. It must be very late for you, thanks so much.

**Comment by donmelton** [comment]
@CallumKerrEdwards Oh yeah, it's late here. :) Anyway, the fix is in and the Gem has been re-released. Let me know if it works for you.

Thanks again and have a good night!
