### ISSUE TITLE
faststart (moov atoms) for convert-video (MP4)

### ISSUE THREAD

**Issue by cnrd** [donmelton/video_transcoding#60]
Hi

I just realised that the convert-video script, when converting to MP4 does not move the moov atoms to the beginning of the file.

Is this on purpose? As my understanding of the moov atoms being moved to the beginning is used to enable faster streaming and file scrubbing?

It can be enabled in ffmpeg using the following command:
`-movflags +faststart`

**Comment by donmelton** [comment]
@cnrd Yes, I'm aware of the flags and I purposely didn't include those options in the `convert-video` tool when I call `ffmpeg`. (You can achieve the same file layout when transcoding to MP4 format by using `--handbrake-option optimize`.)

This "fast start" MP4 file layout only matters when you're streaming a remote video via a `http://` URL in a Web browser -- which should be a rare occurrence. AFAIK, it doesn't matter for streaming MP4 files from your computer via iTunes or Plex Media Server to an Apple TV or Plex device. At least, it didn't matter the last time I tried. Let me know if I'm wrong about that.

**Comment by donmelton** [comment]
@cnrd Forget to mention... I don't wish to add this "fast start" behavior to `covert-video` because it could significantly slow down the conversion process. It's really not worth it.
