### ISSUE TITLE
HandBrake and x264 cause computer to overheat and crash

### ISSUE THREAD

**Issue by danielcompton** [donmelton/video_transcoding#62]
When I try to use video_transcoding to transcode a video, my computer overheats and crashes after a few minutes. Is it possible to set a CPU threshold percentage, or configure it not to use so many cores?

**Comment by donmelton** [comment]
@danielcompton Sorry to hear that.

The `transcode-video` tool only configures encoding options which are then passed to HandBrake and its x264 library. The `transcode-video` tool does not control, and CANNOT control, the threading behavior of HandBrake and x264. There is no API for that. So I can't treat this issue like some kind of enhancement.

It's HandBrake and x264 that are hammering your CPU. This is typical and even happens on my Retina 5K iMac. However, I've never had HandBrake and x264 crash my machine.

What kind of computer do you have and what is its configuration, i.e. CPU type, amount of RAM, OS, free disk space, typical load, etc.? We need to figure out why your computer is crashing before I can confidently recommend a solution.

That said, I know other people run `transcode-video` within a virtual machine, like VMware or VirtualBox, to control and reduce the number of CPU cores used by HandBrake and x264.

**Comment by danielcompton** [comment]
I'm running a Mac of dubious parentage *cough*Hackintosh*cough*

* i7 4790k
* Water cooling
* 16 GB RAM, plenty free
* 2 TB HDD data disk, 1 TB free
* 512 GB SSD boot disk, 200 GB free

Thinking about it more, I've overclocked the 4Ghz to 4.7Ghz max. It was stable under high load testing, but perhaps Handbrake is even more demanding :)

The first thing to check is what happens if I return it back to standard 4 Ghz clock speeds. Sorry for the noise, I hadn't considered that.

**Comment by danielcompton** [comment]
Yep, just clocked the CPU back to standard and it's running hot but stable. This is all on me. Sorry again for the noise, and thanks for the great tool!

**Comment by donmelton** [comment]
@danielcompton No worries. I'm just glad it was easy to figure out.

BTW, the command line version of x264 does have a `--threads` option but I don't believe this can be changed for the x264 library within HandBrake.

**Comment by kford** [comment]
@danielcompton I haven't used this before but I think it could possibly help you to run handbrake while overclocked, on just one core

http://unix.stackexchange.com/questions/23106/limit-process-to-one-cpu-core

**Comment by donmelton** [comment]
@danielcompton Good news. The `--threads` option does control x264 when used from within HandBrake. Just try this to get a single execution thread with x264:

```
transcode-video --encoder-option threads=1 "/path/to/Movie.mkv"
```

Of course, it really ruins performance. :)

Keep in mind that you can set `threads` to however many cores you want to use (providing you really have that number).

**Comment by donmelton** [comment]
@danielcompton BTW, this means that there actually _is_ a "slow down option," which is what you were originally requesting. I just didn't know about it until I started turning over rocks. :) However, I have no plans to make it more accessible than via the somewhat obtuse `--encoder-option threads=1` syntax because, being a performance geek, I think it's a bad idea.

**Comment by danielcompton** [comment]
Thanks for following up! Running this with 3 threads puts the computer at about it's limit, with a small slowdown over the 4 thread standard clock speed. Very handy!

**Comment by donmelton** [comment]
@danielcompton Thanks for testing that out! I may add that trick to the "FAQ" section of the "README" document. I really appreciate you opening this issue.

**Comment by aloglu** [comment]
Thanks for this issue @danielcompton. I love this tool but my Macbook Pro (i7-4770HQ @ 2.20GHz) gets uncomfortably hot while using it (90-100 °C / 190-210 °F). I am comfortable waiting a couple more hours instead of melting down my notebook, so this really helped. It's stable at 57 °C (134 °F) now using a single thread.

@donmelton, you really should add this trick to the FAQ. Also, thanks for the tool!

**Comment by donmelton** [comment]
@aloglu You are very welcome and thanks for the reminder on this.
