### ISSUE TITLE
Add --tabular option to query-handbrake-log to better format report for spreadsheet import

### ISSUE THREAD

**Issue by donmelton** [donmelton/video_transcoding#64]
Add a `--tabular` option to `query-handbrake-log` in order to better format its output report for later import into a spreadsheet application. Here's the proposed `--help` text output for that new option:

```
    --tabular       use tab character as field delimiter and surpress labels
```

Using a tab character instead of a single space as the field delimiter between the numerical data and file pathname is a more standard way of delineating two separate columns to a spreadsheet application. Suppressing the `fps` and `kbps` labels mean the numerical data is more likely to be treated as numbers and not text when imported into the spreadsheet.

This idea originated during discussion between @bmhayward, @hughker and myself about the bug fix for #61.

**Comment by donmelton** [comment]
@bmhayward @hughker OK, I've implemented this and checked it in but haven't released it as an update yet. If you have the time, can you clone the repository and try it out? Thanks.

BTW, I'll probably release it tomorrow or Monday with the rest of the changes for version 0.9.0.

**Comment by donmelton** [comment]
@bmhayward @hughker OK, version 0.9.0 was just released with this feature. Just `gem update video_transcoding` to get it. Thanks, again!

**Comment by bmhayward** [comment]
@donmelton been AFK the last couple of days getting some R&R this week. I'll give it a look in the morning.

Thanks again!
Brent

**Comment by bmhayward** [comment]
@donmelton --tabular works great!

Thanks!
Brent

**Comment by donmelton** [comment]
@bmhayward Excellent! :)
