### ISSUE TITLE
VBV underflow

### ISSUE THREAD

**Issue by notDavid** [donmelton/video_transcoding#66]
Hi, i have a question i'm hoping you could help me with; If i get a lot of these messages

```
Encoding: task 1 of 1, 0.14 %x264 [warning]: VBV underflow (frame 33, -53440 bits)
Encoding: task 1 of 1, 0.15 %x264 [warning]: VBV underflow (frame 35, -824784 bits)

```
is there some easy fix / modification of settings i should consider?

Here's the log if it helps:  https://gist.github.com/notDavid/32088b06366c96ae2f5237c5a8177efd
(The reason I'm transcoding is to burn in the subtitles so Chromecast can see them...)

Thanks in advance :)

**Comment by t089** [comment]
I was wondering the same thing. Have a look at the [FAQ](https://github.com/donmelton/video_transcoding#should-i-worry-about-all-these-vbv-underflow-warnings):

> Should I worry about all these VBV underflow warnings?
> 
> No, these warnings are simply a side effect of my special ratecontrol system. The x264 video encoder within HandBrake is just being overly chatty. Ignore it. Nothing is wrong with the output from transcode-video.

**Comment by notDavid** [comment]
good to know, thanks!

**Comment by donmelton** [comment]
@t089 Thanks for answering that for @notDavid while I was asleep.

**Comment by dorgan** [comment]
Any way to suppress this output?

**Comment by donmelton** [comment]
@dorgan Unfortunately no, unless you want to redirect all diagnostic output to `/dev/null`. The `VBV underflow` warnings are integrated into the rest of `x264`'s system.

The only other way that I can think of is hacking a special build of libx264 into `HandBrakeCLI`. And I've never wanted to suppress them _that_ desperately. :)
