### ISSUE TITLE
Error: audio and subtitle information not found

### ISSUE THREAD

**Issue by brandonedling** [donmelton/video_transcoding#7]
When running

transcode-video filename.mkv

I get the following error message:

audio and subtitle information not found

Running OS X 10.10.4 (14E11f), Ruby 2.2.1, video_transcoding-0.1.3

**Comment by brandonedling** [comment]
Just did a 'brew update' and 'brew upgrade'. Ruby is now at 2.2.2, but still receiving same error.

**Comment by donmelton** [comment]
@brandonedling And per our conversation on Twitter, I found out you're running Ruby installed via Homebrew.

Can you also include your `transcode-video` command line you were using?

And please add `-vv` (that's "verbose" twice) to that command line to get the debugging information and included the console spew too.

Thanks!

**Comment by brandonedling** [comment]
Here's the terminal output:

Enterprise:Before brandon$ transcode-video -vv 300.mkv 
transcode-video 0.1.3
Copyright (c) 2013-2015 Don Melton
Processing: 300.mkv...
Scanning media title 1 with HandBrakeCLI...
HandBrake 0.10.1 found...
[10:56:39] hb_init: starting libhb thread
HandBrake 0.10.1 (2015030800) - Darwin x86_64 - https://handbrake.fr
20 CPUs detected
Opening 300.mkv...
[10:56:39] CPU: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
[10:56:39]  - Intel microarchitecture Ivy Bridge
[10:56:39]  - logical processor count: 20
[10:56:39] OpenCL device #1: AMD AMD Radeon HD - FirePro D700 Compute Engine
[10:56:39]  - OpenCL version: 1.2 
[10:56:39]  - driver version: 1.2 (Apr 19 2015 20:44:10)
[10:56:39]  - device type:    GPU
[10:56:39]  - supported:      YES
[10:56:39] hb_scan: path=300.mkv, title_index=1
libbluray/bdnav/index_parse.c:162: indx_parse(): error opening 300.mkv/BDMV/index.bdmv
libbluray/bdnav/index_parse.c:162: indx_parse(): error opening 300.mkv/BDMV/BACKUP/index.bdmv
libbluray/bluray.c:2182: nav_get_title_list(300.mkv) failed
[10:56:39] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[10:56:39] dvd: not a dvd - trying as a stream/file instead
Input #0, matroska,webm, from '300.mkv':
  Duration: 01:56:38.69, start: 0.000000, bitrate: N/A
    Stream #0.0(eng): Video: h264 (High), yuv420p, 1920x800 [PAR 1:1 DAR 12:5], 30 fps, 1k tbn, 180k tbc (default)
    Stream #0.1(eng): Audio: aac, 48000 Hz, stereo, fltp (default)
[10:56:39] scan: decoding previews for title 1
[10:56:39] scan: audio 0x1: aac, rate=48000Hz, bitrate=1 English (AAC) (2.0 ch)
[10:56:39] scan: 2 previews, 1920x800, 30.000 fps, autocrop = 0/0/0/0, aspect 2.40:1, PAR 1:1
[10:56:39] libhb: scan thread found 1 valid title(s)
+ title 1:
  + stream: 300.mkv
  + duration: 01:56:38
  + size: 1920x800, pixel aspect: 1/1, display aspect: 2.40, 30.000 fps
  + autocrop: 0/0/0/0
  + support opencl: yes
  + support hwd: not built-in
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 01:56:38
  + audio tracks:
    + 1, English (AAC) (2.0 ch) (iso639-2: eng)
  + subtitle tracks:
HandBrake has exited.

/usr/local/bin/transcode-video: audio and subtitle information not found
Enterprise:Before brandon$ 

-----

I've tried this on two different MKV files, checked permissions on them (I have full R/W) and confirmed that they open and play using the latest version of VLC.

**Comment by donmelton** [comment]
@brandonedling Uh, can you paste that in again and mark it as code this time because Markdown just horked it all up?

**Comment by donmelton** [comment]
@brandonedling Here's documentation on how to format code or console spew with GitHub's Markdown processor:

<https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks>

The reason this is important is that I need to see it in its original format to properly diagnose the problem since that error indicates a parsing problem.

Thanks.

**Comment by brandonedling** [comment]
```
Enterprise:Before brandon$ transcode-video -vv 300.mkv 
transcode-video 0.1.3
Copyright (c) 2013-2015 Don Melton
Processing: 300.mkv...
Scanning media title 1 with HandBrakeCLI...
HandBrake 0.10.1 found...
[10:56:39] hb_init: starting libhb thread
HandBrake 0.10.1 (2015030800) - Darwin x86_64 - https://handbrake.fr
20 CPUs detected
Opening 300.mkv...
[10:56:39] CPU: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
[10:56:39]  - Intel microarchitecture Ivy Bridge
[10:56:39]  - logical processor count: 20
[10:56:39] OpenCL device #1: AMD AMD Radeon HD - FirePro D700 Compute Engine
[10:56:39]  - OpenCL version: 1.2 
[10:56:39]  - driver version: 1.2 (Apr 19 2015 20:44:10)
[10:56:39]  - device type:    GPU
[10:56:39]  - supported:      YES
[10:56:39] hb_scan: path=300.mkv, title_index=1
libbluray/bdnav/index_parse.c:162: indx_parse(): error opening 300.mkv/BDMV/index.bdmv
libbluray/bdnav/index_parse.c:162: indx_parse(): error opening 300.mkv/BDMV/BACKUP/index.bdmv
libbluray/bluray.c:2182: nav_get_title_list(300.mkv) failed
[10:56:39] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[10:56:39] dvd: not a dvd - trying as a stream/file instead
Input #0, matroska,webm, from '300.mkv':
  Duration: 01:56:38.69, start: 0.000000, bitrate: N/A
	Stream #0.0(eng): Video: h264 (High), yuv420p, 1920x800 [PAR 1:1 DAR 12:5], 30 fps, 1k tbn, 180k tbc (default)
	Stream #0.1(eng): Audio: aac, 48000 Hz, stereo, fltp (default)
[10:56:39] scan: decoding previews for title 1
[10:56:39] scan: audio 0x1: aac, rate=48000Hz, bitrate=1 English (AAC) (2.0 ch)
[10:56:39] scan: 2 previews, 1920x800, 30.000 fps, autocrop = 0/0/0/0, aspect 2.40:1, PAR 1:1
[10:56:39] libhb: scan thread found 1 valid title(s)
+ title 1:
  + stream: 300.mkv
  + duration: 01:56:38
  + size: 1920x800, pixel aspect: 1/1, display aspect: 2.40, 30.000 fps
  + autocrop: 0/0/0/0
  + support opencl: yes
  + support hwd: not built-in
  + chapters:
	+ 1: cells 0->0, 0 blocks, duration 01:56:38
  + audio tracks:
	+ 1, English (AAC) (2.0 ch) (iso639-2: eng)
  + subtitle tracks:
HandBrake has exited.

/usr/local/bin/transcode-video: audio and subtitle information not found
Enterprise:Before brandon$
'''

**Comment by donmelton** [comment]
@brandonedling Thanks!

**Comment by donmelton** [comment]
OK, I see the bug. I caused it last night with the Windows fix. Dammit. I'll fix it later today.

Thanks so much!

**Comment by brandonedling** [comment]
Dammit, Don! You're not perfect? SO disappointed. ;) 

In all seriousity, no worries at all.

**Comment by donmelton** [comment]
@brandonedling LOL! :)

**Comment by donmelton** [comment]
@brandonedling OK, the fix is in. Just `gem update` and you shouldn't get the error anymore.

Sorry about the stupid bug and thank you so much for the quick bug report!

**Comment by brandonedling** [comment]
BTW, works perfect now. Thanks again!

B.

From: Don Melton
Reply-To: donmelton/video_transcoding
Date: Friday, May 8, 2015 at 12:18 PM
To: donmelton/video_transcoding
Cc: Brandon Edling
Subject: Re: [video_transcoding] Error: audio and subtitle information not found (#7)


@brandonedling<https://github.com/brandonedling> OK, the fix is in. Just gem update and you shouldn't get the error anymore.

Sorry about the stupid bug and thank you so much for the quick bug report!
