### ISSUE TITLE
warning: Insecure world writable dir /usr/local in PATH, mode 040777

### ISSUE THREAD

**Issue by tyler351** [donmelton/video_transcoding#70]
Hello, I am trying to run transcode-video on Mac OS but I keep running into an issue. 

Whenever I run transcode-video, I get a response of 

```
/usr/local/lib/ruby/gems/2.3.0/gems/video_transcoding-0.10.0/lib/video_transcoding/tool.rb:33: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/usr/local/bin/transcode-video: No such file or directory @ rb_file_s_stat - /Volumes/Macintosh
```

Any thoughts?

**Comment by donmelton** [comment]
@tyler351 It seems the permissions to your `/usr/local` directory are in some whacky state right now as far as OS X is concerned. And I have no idea how that would happen.

The `/usr/local/` directory is where Homebrew, Ruby and the `video_transcoding` Gem should be installed. For me, that directory is always world writable so the "insecure" part of that message is possibly what matters here.

Did you just install Homebrew for the first time before this happened? What happens when you try to run other Ruby Gems?

**Comment by tyler351** [comment]
This would be the first time for me. From everything I can tell that directory is writable

**Comment by tyler351** [comment]
I'll see do some digging around and see what I can find. Thanks for the quick response!

**Comment by donmelton** [comment]
@Just search the Web for `warning: Insecure world writable dir /usr/local in PATH, mode 040777` and you'll find plenty of information. This appears to be a common problem, although I can't recommend any of the solutions I've seen so far.

Can you give me the output of this command so I can see your permissions?

```
ls -ld /usr/local/
```

Thanks.

**Comment by tyler351** [comment]
so with that command i get:
drwxrwxrwx  21 root  wheel  714 May 29 18:22 /usr/local/

**Comment by tyler351** [comment]
so with that command, i get this:

drwxrwxrwx  21 root  wheel  714 May 29 18:22 /usr/local/




Tyler Keeton
(336)406-8477
tylerkeeton17@gmail.com

**Comment by donmelton** [comment]
@tyler351 OK, that's your problem then. The permissions , owner and group for your `/usr/local` directory is wrong. It should look something like this instead:

```
drwxrwxr-x  21 user  admin 714 May 29 18:22 /usr/local/
```

... where `user` would be your login username. See the difference?

Do you understand how to change this yourself at the command line?

**Comment by tyler351** [comment]
Ah ok. Yeah I see that. 

I don't know at the command line. Ha just now getting into this type of stuff

**Comment by donmelton** [comment]
@tyler351 OK, let me see if I can help. Try these commands:

```
sudo chown YOUR_USERNAME_HERE /usr/local
sudo chgrp admin /usr/local
sudo chmod 775 /usr/local
```

And do them in that order.

**Comment by tyler351** [comment]
Ok, that got rid of the warning. 
now I'm left with:
/usr/local/bin/transcode-video: No such file or directory @ rb_file_s_stat - /Volumes/Macintosh

(I really appreciate your help with this. I kind of jumped into this head first. Probably could have done some homework first haha)

**Comment by donmelton** [comment]
@tyler351 What command did you type to produce that output?

**Comment by donmelton** [comment]
@tyler351 BTW, I suspect your entire Homebrew installation is horked because the permission on your `/usr/local` directory were so screwed up originally. You may have to reinstall Homebrew and the `video_transcoding` Gem.

**Comment by tyler351** [comment]
yeah, i thought about that too. I'm going to reinstall everything and go from there.

Thanks again for the help

**Comment by donmelton** [comment]
@tyler351 You are taking that news well, sir. Ouch. If it's any consolation, I've had to do it myself a few times.

Anyway, let me know how that goes.

**Comment by tyler351** [comment]
haha its not anything super important at the moment. Just something i'm tinkering with. Sometimes theres a bump here and there and you just gotta do what it takes to get over that bump hahaha

will do! Thanks a lot for taking time to help me out, much appreciated

**Comment by donmelton** [comment]
@tyler351 No problem! I'll close this for now then.
