### ISSUE TITLE
Why does detect-crop NOT crop on both axis by default?

### ISSUE THREAD

**Issue by faithfracture** [donmelton/video_transcoding#71]
I'm curious why detect-crop doesn't display crop values for both axis by default? If a video has bars on both axis (lots of music videos and DVD special features do this), I'd really rather have the video expand all the way to the edge of the screen on whichever axis it can. I know I can pass `--no-constrain` to get the values for both axis, I'd just like to know what the benefit of _not_ doing this is? If I use handbrake directly, it will resize the output video geometry accordingly so the video is not stretched along one axis. Does `transcode-video` not use this option by default, or is there some other reason for this?

**Comment by donmelton** [comment]
@faithfracture Good question. While there is some windowboxed content available (per your examples), the vast majority of Blu-rays and DVDs are either letterboxed or pillarboxed. So this typically isn't a big issue. The main reason I constrain the crop to a single axis is to maintain the same scale for Blu-rays on standard 1080p output devices like TVs. The other reason has to do with getting HandBrake and MPlayer to agree on the crop most of the time, which they would hardly ever do without the axis rule or other constraints in the algorithm.

I'm closing this now, but feel free to continue commenting here.

**Comment by faithfracture** [comment]
Ah, ok. So it sounds like the reasons are because most video is either 4:3 or 16:9 (ish) and usually only needs it in one direction and mplayer and handbrake don't like each other. So from a standpoint of just "I want to get rid of the black bars all the way around", defining all four crop values won't result in any kind of weird deformation. I really just wanted to check if there was some other underlying reason for "cropping to the optimal shape". Thanks.

**Comment by donmelton** [comment]
@faithfracture Ah. Now I understand your concern better. Sorry about that.

There's no reason you can't crop from both axes. And your aspect ratio will remain the same (e.g. `1:1` for Blu-rays) as long as you don't scale at the time of transcoding by using the `--720p` option or something similar.

Just be ready for a bit more manual review when using the `--no-constrain` option because, as I indicated, HandBrake and MPlayer will disagree far more often.

**Comment by faithfracture** [comment]
Ok great, that's what I needed to know. It didn't seem like it would be bad to do, just wanted to check. I don't mind doing a little extra leg work for the few files I actually need to do that with. Like you said, most videos are one way or the other, so it's pretty uncommon.
