### ISSUE TITLE
Unsatisfied dependencies on Debian 8

### ISSUE THREAD

**Issue by bighungry** [donmelton/video_transcoding#73]
Installing ffmpeg on Debian 8 is currently pretty broken. I've gone down the rabbit hole of getting into unstable sources and still cannot managed to get all of the package dependencies to play nice. Any chance of adding support to use avconv instead? It was recommended here: http://superuser.com/questions/286675/how-to-install-ffmpeg-on-debian

**Comment by donmelton** [comment]
@bighungry No, I don't plan to support `avconv`. Partly because Debian is the only environment where this has ever been a problem. What happens when you simply make a symbolic link from `ffmpeg` to `avconv` in your `$PATH`?

**Comment by bighungry** [comment]
I'm not super attached to Debian specifically so I think I'll jump to
another OS. I've been wanting to rebuild this box anyway. Thanks for the
quick response.
