### ISSUE TITLE
transcode-video help does not list --no-constrain-crop and --fallback-crop options

### ISSUE THREAD

**Issue by bpharriss** [donmelton/video_transcoding#74]
Issue #56 resulted in the new options `--no-constrain-crop` and `--fallback-crop` to be added to transcode-video in 0.8. However, the `--help` for transcode-video has not been updated to include these options. I would humbly suggest the proposed help text that was written up in #56 is appropriate as-is to be included.

EDIT: Sorry, somehow 0.7 of transcode-video was still lurking on my system, and that was what I was running against. Nuked it out, and see the help correctly now. Apologies.

**Comment by donmelton** [comment]
@bpharriss No worries. I was out of town and AFK when you filed this and only reading it now. My apologies for noticing it so late. BTW, I've had that same thing happen to me with other tools way too often to admit. :)
