### ISSUE TITLE
Version check error on Ubuntu

### ISSUE THREAD

**Issue by jtgallucci** [donmelton/video_transcoding#77]
My Mac Pro died so I'm attempting to get the Ruby tools running on Ubuntu.  I have HandBrakeCLI installed, but when attempting to run I get thee following error:

`/usr/local/bin/transcode-video: HandBrakeCLI version 0.10.0 or later required
`
Is anyone aware of a workaround for this?

Thank You,

Justin

**Comment by donmelton** [comment]
@jtgallucci Sorry to hear about your Mac Pro. :(

Which version of `HandBrakeCLI` do you have installed? Look at the first line output with this command:

```
HandBrakeCLI --preset-list
```

If it's not version 0.10.0 or later then you need to upgrade. There's no way to work around that limitation.

**Comment by jtgallucci** [comment]
Hi Don-

Thanks so much for your help.  Yes, it is unfortunate about my MacPro, but the goon news is that since its 3 years old I have an excuse to buy a newer model.  Oh, wait a minute...never-mind.

I added the repository for HandbrakeCLI and updated so I should have the latest version , but I'm not sure what version number the script is looking for:

`jgallucci@ZEUS:~$ HandBrakeCLI --preset-list
HandBrake rev5474 (2014032499) - Linux x86_64 - http://handbrake.fr

< Devices

   + Universal:  -e x264  -q 20.0 -r 30 --pfr  -a 1,1 -E faac,copy:ac3 -B 160,160 -6 dpl2,auto -R Auto,Auto -D 0.0,0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -X 720 -Y 576 --loose-anamorphic --modulus 2 -m --x264-preset fast --h264-profile baseline --h264-level 3.0

   + iPod:  -e x264  -q 22.0 -r 30 --pfr  -a 1 -E faac -B 160 -6 dpl2 -R Auto -D 0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -I -X 320 -Y 240 --modulus 2 -m --x264-preset medium --h264-profile baseline --h264-level 1.3

   + iPhone & iPod touch:  -e x264  -q 22.0 -r 30 --pfr  -a 1 -E faac -B 160 -6 dpl2 -R Auto -D 0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -4 -X 960 -Y 640 --loose-anamorphic --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 3.1

   + iPad:  -e x264  -q 20.0 -r 30 --pfr  -a 1 -E faac -B 160 -6 dpl2 -R Auto -D 0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -4 -X 1280 -Y 720 --loose-anamorphic --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 3.1

   + AppleTV:  -e x264  -q 20.0 -r 30 --pfr  -a 1,1 -E faac,copy:ac3 -B 160,160 -6 dpl2,auto -R Auto,Auto -D 0.0,0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -4 -X 960 -Y 720 --loose-anamorphic --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 3.1 -x qpmin=4:cabac=0:ref=2:b-pyramid=none:weightb=0:weightp=0:vbv-maxrate=9500:vbv-bufsize=9500

   + AppleTV 2:  -e x264  -q 20.0 -r 30 --pfr  -a 1,1 -E faac,copy:ac3 -B 160,160 -6 dpl2,auto -R Auto,Auto -D 0.0,0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -4 -X 1280 -Y 720 --loose-anamorphic --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 3.1

   + AppleTV 3:  -e x264  -q 20.0 -r 30 --pfr  -a 1,1 -E faac,copy:ac3 -B 160,160 -6 dpl2,auto -R Auto,Auto -D 0.0,0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -4 -X 1920 -Y 1080 --decomb=fast --loose-anamorphic --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 4.0

   + Android:  -e x264  -q 22.0 -r 30 --pfr  -a 1 -E faac -B 128 -6 dpl2 -R Auto -D 0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -X 720 -Y 576 --loose-anamorphic --modulus 2 --x264-preset medium --h264-profile main --h264-level 3.0

   + Android Tablet:  -e x264  -q 22.0 -r 30 --pfr  -a 1 -E faac -B 128 -6 dpl2 -R Auto -D 0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -X 1280 -Y 720 --loose-anamorphic --modulus 2 --x264-preset medium --h264-profile main --h264-level 3.1

>

< Regular

   + Normal:  -e x264  -q 20.0 -a 1 -E faac -B 160 -6 dpl2 -R Auto -D 0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 --loose-anamorphic --modulus 2 -m --x264-preset veryfast --h264-profile main --h264-level 4.0

   + High Profile:  -e x264  -q 20.0 -a 1,1 -E faac,copy:ac3 -B 160,160 -6 dpl2,auto -R Auto,Auto -D 0.0,0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -f mp4 -4 --decomb --loose-anamorphic --modulus 2 -m --x264-preset medium --h264-profile high --h264-level 4.1

>`

Thanks again!

Justin

**Comment by jtgallucci** [comment]
P.S. here's the repository I added:

` sudo add-apt-repository ppa:stebbins/handbrake-releases`

**Comment by donmelton** [comment]
@jtgallucci The version you‘re using:

```
HandBrake rev5474 (2014032499) - Linux x86_64
```

… is a nightly development build and not an official release. While `transcode-video` is compatible with nightly `HandBrakeCLI` builds, yours appears to be SVN revision 5474, and that‘s prior to the 0.10.0 release. Also, notice the date after that number—it's from March in the year 2014, so it's quite old. If you plan to use a nightly build, you‘ll need revision 6536 or later.

**Comment by jtgallucci** [comment]
Thanks Don-

I did see the date, but I assumed that it was an error because I had just
gotten the latest version of the repository. However, it appears the
repository I'm using must be out of date. Thank you for helping me identify
the issue. You can feel free to close this out. Apologies for the oversight
on my end.

-- 
Justin Gallucci

**Comment by donmelton** [comment]
@jtgallucci No worries. I'll close this for now but let me know if you're still having trouble with your Ubuntu setup.

**Comment by ntodd** [comment]
Just as a heads up, it appears more recent and nightly linux HandBrakeCLI builds have `rev0` in the `--preset-list` output.

Using the deb from https://launchpad.net/~stebbins/+archive/ubuntu/handbrake-git-snapshots/+files/handbrake-cli_20160803204647-6b5d91a-master-zhb-1ppa1~xenial1_amd64.deb I get the following:

`HandBrake rev0 (2014100499) - Linux x86_64 - http://handbrake.fr`

Is there any other way to check for the version?  This build is from just a 8/3/16, but fails the version check.

**Comment by donmelton** [comment]
@ntodd Ugh. If the HandBrake developers keep changing stuff like this, the version checking code in `handbrake.rb` will be larger than all the other code in the project.

I don't want to add a `--force flag`. That just seems like the wrong way to solve this. More likely, I'll remove the version checking entirely.

Thanks for letting me know about this.
