### ISSUE TITLE
Not possible to install mp4v2

### ISSUE THREAD

**Issue by berdot** [donmelton/video_transcoding#83]
Download location has changed https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mp4v2/mp4v2-2.0.0.tar.bz2

**Comment by donmelton** [comment]
@berdot Thanks for the information, but this really isn't an issue for the Video Transcoding project. If you're trying to install `mp4v2` via Homebrew then do a `brew update` first and you'll find the download location is correct in the formula. And it should install fine.
