### ISSUE TITLE
Batch --add -subtitle assistance

### ISSUE THREAD

**Issue by platonium** [donmelton/video_transcoding#84]
Could someone give me some pointers on having subtitles added to the batch script?  

When I transcode-video --add-subtitle eng in terminal command line, the subtitle passes through to the transcoded mkv.

When I add the same --add-subtitle eng to the batch script, the transcoded mov does not include subtitle tracks.

Thank you so much.

**Comment by donmelton** [comment]
@platonium So, when you change the line from my sample `batch.sh` script from this:

```
    transcode-video $crop_option "$input"
```

... to this:

```
    transcode-video $crop_option --add-subtitle eng "$input"
```

... it doesn't work?

Do you get any errors?

Honestly, I have no idea why this should fail.

**Comment by platonium** [comment]
Thanks, I decided to try again.

Transcode-video command looks like this: 

 transcode-video --add-subtitle all --add audio all $crop_option "$input" -o /Volumes/Seagate\ 1000/scratch\

Output is this:

/usr/local/bin/transcode-video: ambiguous option: --add
Try `/usr/local/bin/transcode-video --help` for more information.

If take out the --add, the batch file works.

Ideally, I'd like to make the transcode-video command:

transcode-video --add-subtitle eng,zho --add audio eng,zho $crop_option "$input" -o /Volumes/Seagate\ 1000/scratch\

**Comment by donmelton** [comment]
@platonium The problem is that `--add audio` should be `--add-audio`. Notice the hyphen between the two words? That's required because it's a single option name.

**Comment by platonium** [comment]
So embarrassed-now everything works great.  Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sun, Sep 18, 2016 at 9:57 PM -0700, "Don Melton" <notifications@github.com<mailto:notifications@github.com>> wrote:


@platonium<https://github.com/platonium> The problem is that --add audio should be --add-audio. Notice the hyphen between the two words? That's required because it's a single option name.

-

**Comment by donmelton** [comment]
@platonium No problem. Let me know if you have any other issues.
