### ISSUE TITLE
handbrakecli nightly install

### ISSUE THREAD

**Issue by platonium** [donmelton/video_transcoding#91]
Am excited to try the new release.  Is there a simple way to update to the nightly build of handbrake cli?

**Comment by platonium** [comment]
BTW, I tried this: sudo brew cask install caskroom/versions/handbrakecli-nightly

but I got this: 

==> Tapping caskroom/versions
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-versions'...
remote: Counting objects: 206, done.
remote: Compressing objects: 100% (203/203), done.
remote: Total 206 (delta 19), reused 12 (delta 1), pack-reused 0
Receiving objects: 100% (206/206), 76.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (19/19), done.
Checking connectivity... done.
Tapped 0 formulae (223 files, 274.2K)
==> Satisfying dependencies
complete
==> Downloading http://download.handbrake.fr/nightly/HandBrakeCLI-20160910140502

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'handbrakecli-nightly' with message: Download failed: http://download.handbrake.fr/nightly/HandBrakeCLI-20160910140502-cc9af94-master-osx.dmg
The incomplete download is cached at /Users/iMac/Library/Caches/Homebrew/Cask/handbrakecli-nightly--20160910140502-cc9af94.dmg.incomplete

**Comment by donmelton** [comment]
@platonium The easiest way to install the `HandBrakeCLI` nightly build is to download it directly and install in your path. I've found the Homebrew Cask method to be somewhat problematic.

**Comment by platonium** [comment]
Thank you.  Have never done that before.  Is there a guide someone could point me to?

On Oct 15, 2016, at 9:02 AM, Don Melton <notifications@github.com<mailto:notifications@github.com>> wrote:


@platonium<https://github.com/platonium> The easiest way to install the HandBrakeCLI nightly build is to download it directly and install in your path. I've found the Homebrew Cask method to be somewhat problematic.

**Comment by donmelton** [comment]
@platonium I'm not sure if there's a guide online, but I'll try to explain here:

Go to this page:

<https://handbrake.fr/nightly.php>

...and download the Mac build. I assume your platform is macOS? Anyway, make sure you get the one whose name begins with `HandBrakeCLI`.

Next, open the disk image file and copy the `HandBrakeCLI` executable binary to your local disk.

You'll then need to move the executable binary into a directory listed in your `PATH` environment variable. On Unix-style systems like macOS, that directory might be /usr/local/bin.

**Comment by platonium** [comment]
Worked great.  The new settings seem to be working out well.  Thank you so much.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Oct 15, 2016 at 10:44 AM -0700, "Don Melton" <notifications@github.com<mailto:notifications@github.com>> wrote:


@platonium<https://github.com/platonium> I'm not sure if there's a guide online, but I'll try to explain here:

Go to this page:

https://handbrake.fr/nightly.php

...and download the Mac build. I assume your platform is macOS? Anyway, make sure you get the one whose name begins with HandBrakeCLI.

Next, open the disk image file and copy the HandBrakeCLI executable binary to your local disk.

You'll then need to move the executable binary into a directory listed in your PATH environment variable. On Unix-style systems like macOS, that directory might be /usr/local/bin.

-

**Comment by donmelton** [comment]
@platonium Great to hear! Let me know if you have any other issues.
