### ISSUE TITLE
Unable to update my transcode-video installation from 0.10.0 to 0.12.0 using Ruby 2.2.5 for windows.

### ISSUE THREAD

**Issue by Boyerstown** [donmelton/video_transcoding#92]
Here is the command issued along with the output...

C:\VideoToolsCLI\video_transcoding-0.12.0>gem install video_transcoding
ERROR:  Could not find a valid gem 'video_transcoding' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by donmelton** [comment]
@Boyerstown Thanks for filing this! Like I said on email, I have no idea why the Ruby Gem mechanism would get an SSL failure like this, but maybe someone else would know. I'll ask on Twitter...

**Comment by jaredharley** [comment]
@Boyerstown @donmelton It looks like this might be a recurring issue with Ruby and SSL: http://guides.rubygems.org/ssl-certificate-update/

**Comment by donmelton** [comment]
@jaredharley That looks like the problem to me. Nice work and thanks!

@Boyerstown I'll close this now but feel free to keep commenting here.

**Comment by Boyerstown** [comment]
@jaredharley Thanks! I was able to successfully update Ruby Gem and install the latest version of Transcode-video.

@donmelton Thanks for getting me a quick answer to my issue.  Also, great job with the video tools! 

C:\VideoToolsCLI\video_transcoding-0.12.0>gem install video_transcoding
Fetching: video_transcoding-0.12.0.gem (100%)
Successfully installed video_transcoding-0.12.0
Parsing documentation for video_transcoding-0.12.0
Installing ri documentation for video_transcoding-0.12.0
Done installing documentation for video_transcoding after 2 seconds
1 gem installed

**Comment by Boyerstown** [comment]
Thanks Everyone with this issue!
