### ISSUE TITLE
Remove TV Episode rip/transcode pain

### ISSUE THREAD

**Issue by cadeon** [donmelton/video_transcoding#95]
IMHO this is the biggest pain left in the dvd-ripping world, dealing with dvds with TV episodes on them. 

The _ideal_ solution would be some kind of online database, like CDDB, that fingerprints the disc and lists all the episodes on the disc by title. Then something could be scripted to name the ripped/transcoded files correctly using that information. 

I'm going to assume this database doesn't exist, though, because honestly we have enough problems getting similar databases to correctly identify feature film dvds. Building the TV series DVD DB would be a monumental task. There are a couple TV episode databases out there, but they are keyed on air date, not DVD title number. 

So, assuming we can't have the ideal solution, the next one down would be to have some kind of an interface where the script identifies the titles on the disc, notices that there are several titles with similar lengths, and then assumes it's a TV episode DVD. 

From there we could have different handling, such as an interactive prompt to name each title, or a command line switch to specify season and episode number, and auto-naming the files from there. e.g. South Park - S03E05.mkv. It's safe to assume that most TV Episode DVDs are sequential (not all are, but 80% or more are) so this approach would save a ton of work (identifying and renaming the output files) for the end user in those cases. 

If there are already solutions for this, perhaps in wrapper scripts around these, I'd love to hear about them :)

**Comment by donmelton** [comment]
@cadeon My apologies but I didn't receive a notification from GitHub when you opened this issue. I only found it by checking the website itself.

What you're asking for here is way outside the scope of my goals for `transcode-video`. It will never be a tool to lookup metadata of the kind you're describing. That is a world of code bloat and compatibility problems that I will not visit.

The metadata issues need to be resolved during the process of ripping your discs, not transcoding. But once the correct movie or TV episode file names are determined, there are tools out there which can look up metadata based on filename and add it to your transcoded output.

And even if you don't add the metadata then, server software like [Plex](https://www.plex.tv/) can add it dynamically for presentation as long as your filenames are correct.

If you're using macOS, I would recommend [MetaMovie](http://www.appfacture.com/en/metamovie/) and [MetaTV](http://www.appfacture.com/en/metatv/) from [AppFracture](http://www.appfacture.com/en/) for adding and editing metadata.

I'm unfamiliar with the tools for other platforms, but I know that there are several. A good place to find tools is at [VideoHelp](http://www.videohelp.com/).

Also, there are two useful websites for the determining the canonical names for movies and TV episodes, [TheMovieDB](https://www.themoviedb.org/) and [TheTVDB](http://thetvdb.com/).

But really, the big problem is not finding a database for the metadata. Or even it looking it up. The big problem when you're ripping discs, especially Blu-rays, is figuring out which tracks are which episodes. This can make you crazy. Not to mention true insanity dealing with the problem of determining which tracks contain, or are fully, forced subtitles.

And there's no database for that. At least, not that I know of.

Anyway, I hope these pointers are at least of some help. I'm going to close this issue now but feel free to continue our dialogue here.

And that's for submitting an issue!
