### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by ntodd** [donmelton/video_transcoding#98]
Would there be interest in adding docker support?  I have built [an image](https://hub.docker.com/r/ntodd/video-transcoding/) and could add usage instructions to the readme.  It's a 1-line command to get running on Docker for Linux, Mac and potentially Windows (once it supports interactive mode).

**Comment by donmelton** [comment]
@ntodd What would Docker support mean? It doesn't seem like a feature that needs to be added to the tools themselves. Seriously, I've never used Docker so I don't have any experience with it.

**Comment by ntodd** [comment]
@donmelton It would provide an option for people using Docker to download and run a pre-made container with all the dependencies and the gem installed.  No need to install (and maintain) ffmpeg or any of the other dependencies on your local machine.  Essentially, docker users could run a single command and could jump straight to the usage section.  It would not require any changes to the code.

See [What is docker?](https://www.docker.com/what-docker) for their overview.

**Comment by donmelton** [comment]
@ntodd I know what Docker is, I just don't have any experience using it. But the big question is, how do you envision Docker support being added? Since there's no additional code, what's the change you're suggesting? Packaging? That seems contrary to making this project already being a Gem. What you're suggesting seems like a whole new project.

**Comment by ntodd** [comment]
It could be as simple as an addition to the README's installation section:

---

Docker users on Mac and Linux can also download and use a pre-built image by executing the following command:

```
docker run -itv `pwd`:/data ntodd/video-transcoding /bin/bash
```

This will download the image, mount your current directory and load an interactive bash session where you can execute the video_transcoding cli tools.

---

Totally OK if you aren't interested.  I packaged it up for myself and figured others might benefit as well.

**Comment by donmelton** [comment]
@ntodd OK, adding something to the README sounds reasonable. What are the security implications of installing someone else's Docker package? In other words, I don't want to point to your build without confidence that it will remain safe.

**Comment by ntodd** [comment]
I am not a security expert by any means, but [the documentation](https://docs.docker.com/engine/security/security/) claims that containers are heavily sandboxed.  Processes and networks are isolated.  Additionally, Docker for Mac runs on a linux VM in Hypervisor.framework, so that's an additional layer of protection for Mac users.  The command in the README does mount the current working directory as a host volume in the docker container, but that would only allow files in the current directory to be altered by the container, not full filesystem access.

You may not want to support it, but the Dockerfile is very simple and could be added to this project directly.  I did build it on a non-standard ubuntu 16.04 ruby image (the official ruby image is Debian Jessie and some dependencies are not available in apt-get), but I can move everything into a single Dockerfile.  Just let me know your preference.

**Comment by ntodd** [comment]
@donmelton I created a repo that includes the necessary Dockerfiles and a brief usage overview: https://github.com/ntodd/video_transcoding_docker

**Comment by hughker** [comment]
Thanks @ntodd I just tested out your docker and it worked great.

**Comment by donmelton** [comment]
Thanks, @hughker!

@ntodd Is that repository of yours essentially source only? And the image is built by Docker dynamically? If so, then that sounds a lot safer to me.

**Comment by ntodd** [comment]
@donmelton Yes, Dockerfiles are essentially build scripts.  The final image is then pushed up to Docker Hub where people can download and run it using the `docker run` command.

**Comment by ntodd** [comment]
Opened pull request #99

**Comment by donmelton** [comment]
@ntodd Being just a build script sounds much safer. I'll consider adding this to the README document now.

And I'll comment on your patch later today. Thanks for submitting that.

**Comment by donmelton** [comment]
@ntodd OK, I've added Docker virtualization software installation instructions to the "README" document for version 0.12.3 which I just released. I didn't use your patch since I completely reworded the text.

Thanks again for making this enhancement request!
